docs/source/plugin.rst, sopel/config/core_section.py, sopel/module.py, sopel/plugin.py, sopel/trigger.py
* `plugin.action_commands` is now `plugin.action_command`
* `plugin.commands` is now `plugin.command`
* `plugin.nickname_commands` is now `plugin.nickname_command`
The legacy imports in `sopel.module` have the old names preserved by using the `as` keyword.
Should be the last thing we need to do for #1619 (except make sure to call out the renames when writing the changelog for 7.1). I did a manual find-and-replace in all files to rename all Sphinx references to these decorators, but the small number of changes it turned up made me suspicious and I'd love a second set of eyes to double-check those. Yes, even though I also went through and reviewed all ~600 matches of "commands" in the source code & doc files.
=> plugin: rename plural decorators to be consistent

docs/source/configuration.rst, sopel/config/core_section.py, sopel/irc/__init__.py
It was asked by someone on IRC so I added some config options to control extra wait penalty on longer messages, and one thing led to another I also added a setting to control the maximum wait time because why not.
I've to say that @dgw was right again, but maybe even more "on the nose" than ever before:
```
07:22:51 <+dgw> It's some arcane magic from AT LEAST a decade ago.
https://github.com/sopel-irc/sopel/blame/d610029b3933c2ddd6751a7523dd12a30cf4ae8b/irc.py#L139
07:23:24 <+dgw> actually 11
https://github.com/sopel-irc/sopel/blame/c79635a1627813028d48b2cd0a5e226cd116bae5/irc.py#L135
07:23:28 <+dgw> "Initial commit"
07:23:33 <+dgw> can't get older than that
[...]
07:25:19 <+dgw> also, like half the code in Sopel makes me go hmm
```
=> irc, config: config options for flood penalty on longer messages

sopel/cli/config.py, sopel/cli/plugins.py, sopel/cli/run.py, sopel/cli/utils.py
Part of #1565 for `sopel.cli`.
=> cli: modernize docstrings

docs/source/bot.rst, docs/source/index.rst, docs/source/package.rst, docs/source/plugin.rst, docs/source/plugin/anatomy.rst, docs/source/plugin/bot.rst, docs/source/plugin/decorators.rst, docs/source/plugin/internals.rst, docs/source/plugin/what.rst, sopel/plugin.py
I moved the content of `source/plugin.rst` to `source/plugin/*.rst` files and then worked around that structure:
* a glossary
* what is a plugin (explain what it is, plugin types, and plugin name)
* anatomy of a plugin (plugin callables, jobs, setup & shutdown, and about plugin configuration)
* interact with the bot (how to use `bot` to talk, join channels, and stuffs)
* `sopel.plugin` (plugin decorators, already explained in anatomy of a plugin)
* `sopel.plugins` (internals, no need to touch that)
I took the same approach I used for the core configuration: one part is a thorough explanation of the topic and the other part is the good old `autodoc`. I really like it!
I think it's possible to do even more, and that should be done later, either by me or someone else, in this version or a …
=> docs: the plugin chapter

docs/source/_static/custom.css
Main motivation: Class/Module members/attributes were too close together in production docs. Finally got motivated to fix it.
Might want to amend the commit/PR title if that spacing is the only tweak. Thinking I might find a few more before this is actually ready to go, but who knows? I might not.
=> docs: add space before attribute lists

sopel/loader.py, sopel/plugin.py, test/test_loader.py
=> loader, plugin: load decorated callables only

sopel/coretasks.py, sopel/irc/__init__.py, sopel/irc/abstract_backends.py, sopel/irc/backends.py, test/test_irc.py
Basic implementation to fix #300 (no configuration, no alternative, nothing):
1. on connection, if we receive a "nick already used" event, we change the current nick, adding an extra ` _` to its end
2. on auth with a nickserv account, if `bot.nick` is not `bot.settings.core.nick`, we try to use `NickServ GHOST`
3. when `bot.settings.core.nick` QUIT, we try to get back to that nick
Maybe this should be optional, maybe we could have a list of nick aliases to use for that purpose. But I wanted to show what is possible with the current state of the code. It tested it by using a copy of a config file, and checking that the second instance ghost the first one and get its nick back.
From another user point of view, here are the logs:
```
15:25:05 → Exibot joined (~Exibot@hostmask)
15:27:33 → …
```
=> core: change/recover in-use nick; fix obsolete USER command syntax

sopel/modules/tld.py
In short, this fixes Sopel being unable to find known-valid TLDs. But it also makes things _better_ than before. No more ugly, unmaintainable regex!
* Pulls from IANA for verifying that a TLD is recognized
* If a TLD is not in the IANA list, it stops and says so
* If the given TLD exists in the IANA list, return at least a confirmation of existence
* If the TLD exists in the Wikipedia article we've been using for years, also include more details from there
* Wikipedia table data is now transformed into an in-memory dictionary using `HTMLParser`
Both the IANA and Wikipedia data sources are cached locally, persisted/restored to/from the bot's database on shutdown/startup, and periodically updated by a plugin job (minimum age 7 days).
I think about the only thing I didn't do was add …
=> tld: comprehensive rewrite

sopel/modules/isup.py, test/modules/test_modules_isup.py
Unbelievably, `isup` has been sometimes (often?) returning "looks fine" for sites that send back error status codes, e.g. HTTP 4xx, 5xx. Those should be considered "down".
I also threw in a couple other little tweaks, the important one being that a bare name like `google` will no longer assume `google.com` as the input. (There's one last TODO left for myself before this PR is actually _ready_ for review, about properly handling full URLs that contain a `.` but refer to a LAN name.)
=> isup: fix error-series HTTP status codes; get away from assuming TLD

sopel/bot.py, sopel/modules/find.py, sopel/modules/translate.py, sopel/modules/url.py, sopel/test_tools.py, sopel/tools/__init__.py, test/test_tools.py
In an attempt to fix #1341, I decided to create a new class that specifically deals with `tools.Identifier` as its keys: nothing more, nothing less, just `Identifier`.
My idea is that we *want* `SopelMemory` to consider `"nick"` and `Identifier("nick")` as two separated keys, and what we need is a specific **type** of memory, one that is specifically designed to store and retrieve values from `Identifier` key. So that's what I did here.
=> tools: new `SopelIdentifierMemory` class

sopel/tools/__init__.py
It's really silly that anyone who wants to use the `time` submodule has to do `import sopel.tools.time` even if they've already done `from sopel import tools`. This makes that unnecessary.
The intention here is to make `from sopel import tools` the only import needed to use the `tools`, `tools.events`, `tools.time`, and `tools.web` modules, without any extra nonsense.
=> tools: make `time` and `web` always accessible by importing `tools`

sopel/modules/announce.py
Tin. Closes #1306.
- Not against a live server. I started writing unit tests but got lost in @Exirel's mocks. 😅 Maybe he'll have time to help me finish later.
=> announce: send announces to TARGMAX channels at once, if advertised

sopel/coretasks.py
Took a WIP fix for #1780 I found lying around the branches and extended it.
Better late than never (just look how long this PR sat open…)
=> coretasks: better SASL handling

sopel/config/types.py, sopel/modules/admin.py, test/config/test_config_types.py
All I wanted was to add a new type of attribute (something like a `FlagAttribute` to simplify how boolean attributes are handled in config). But then, I discovered an interface I really don't like.
So instead I wrote some unit-test, refactored some bit. I would like to go further, but I need some approval first.
Also, all these tests are still good and shouldn't go to waste or kept in a forgotten local branch.
=> config: small refactoring and unit tests for types

sopel/coretasks.py
Fix #1974 
@dgw if this can be merged in priority, as this bug prevent from using SASL in dev (I don't use SASL so I didn't notice).
=> core: fix invalid usage of r-string for SASL auth token

sopel/coretasks.py, test/test_coretasks.py
This is a follow-up to #1974 & #1976, which should prevent a similar regression from being introduced in the future.
Considered putting the new utility function in `sopel.tools`, but figured it's not useful to anything outside `coretasks`.
=> core, test: make SASL PLAIN token generation testable (and test it)

.travis.yml
It took a few weeks for Travis CI to add Python 3.9 stable to the available versions, but it finally arrived.
This CI configuration has been [validated](https://travis-ci.org/github/sopel-irc/sopel/builds/739190149) on a test branch.
Letting this jump the usual merge order might make sense, after which it should be possible for me to just "kick" older PRs through Travis' web UI and make them rerun with the added job. Could be annoying if they continue under-allocating build workers to the .org platform, but migrating onto .com is currently a last-resort thing due to the migration function _still_ being labeled "Beta" (some things like build logs do _not_ transfer).
=> ci: test on Python 3.9

sopel/coretasks.py
=> coretasks: assume + only if core.modes does not start with + or -

sopel/coretasks.py, sopel/modules/admin.py
No one asked for this, but I did it anyway: `bot.write` accepts a list (any iterable) of arguments as its first parameter and will automatically join them with a space.
It means that this:
bot.write(('COMMAND arg %s' % param,))
Can be written as:
bot.write(('COMMAND', 'arg', param))
Which I prefer and is better in every way. So I checked the code and fixed them whenever possible.
I didn't modify one `bot.write` in `coretasks` because it's already fixed in #1941 and I don't want to create unnecessary merge conflict.
_This PR is very "hashtag first world problem" and "hashtag totally not a maniac"._
=> coretasks, admin: minor style fix for bot.write

sopel/bot.py
Fix #1830
Check for `SystemExit` while loading plugins, and prevent the bot to crash.
=> bot: prevent sys.exit when loading plugin to crash the bot

sopel/plugins/rules.py, sopel/test_tools.py, sopel/tools/__init__.py, test/plugins/test_plugins_rules.py, test/test_tools.py
Fix #1887 
* moved everything into `sopel.plugins.rules`, directly into each rule class
* removed/deprecated a bunch of stuff from `sopel.test_tools` (this entire module should probably be deprecated and removed at some point anyway)
* reworked imports in `sopel.test_tools`
* changed how the `example` decorator runs a test (this should be transformed further, probably in a future PR, for 7.1 or 8.x)
* removed obsolete tests and fixtures
* made sure the doc is still OK
=> plugins: command-regexp functions are now private

sopel/coretasks.py
This debug output is only relevant if the MODE message received pertains to a channel. We can stop emitting log entries for MODE messages that pertain to users only (target is a nick & has only 2 args).
=> coretasks: reduce "useless MODE message" logspam

sopel/modules/version.py
Tweak the docstring of the `.version` command so it is more accurate and informative
=> version: tweak docstring for clarification

sopel/modules/tld.py
Allows viewing last update time for both caches, forcing the cached data to update, and clearing the cached data from both bot memory and the bot's database.
Perhaps a *bit* messier than it could be, but I'm tired of resetting my test bot's database values for tonight.
Not mentioned in commit log: This change means anyone running from source will have to manually delete the 'tld' plugin's stored plugin values from the database, as the timestamp format has changed.
=> tld: add .tldcache command

requirements.txt, sopel/modules/url.py
urllib3 1.26 changed its `UnicodeError` to a custom exception type, breaking some of our `url` plugin's tests (plus the real-world behavior they check, of course). Now `urllib3.exceptions.LocationParseError` is raised (a subclass of `urllib3.exceptions.LocationValueError`) instead.
The solution is threefold:
1. Distrust urllib3's point releases; pin it to 1.26.x or lower now
2. Catch the custom exception type's superclass now
3. Stop catching `UnicodeError` and drop our support for urllib3<1.26 in Sopel 8 (or switch to urllib3 2.0+ only, if it's released by then)
Probably will backport this to 7.0.x and cut a new release. Don't want to touch that branch any more, but I think it's going to be impossible to get a working new Sopel install on v7.0.6 because of this change.
=> requirements, url: adapt to urllib3 exception type change

sopel/modules/isup.py, test/modules/test_modules_isup.py
Follow-up to #1940, wherein @Exirel requested more specific error messages than just "seems down".
=> isup: more specific errors

sopel/modules/admin.py, sopel/modules/pronouns.py, sopel/modules/py.py
Once #1859 and #1950 implement their part, this will fix #1001 
I didn't changed all the reply-on-error messages, because most of them are fine. If someone wants to nitpick, they will be able to do some PR (hey, it's hacktoberfest or something). The most important part was to make sure admin checks command args.
Also I added some
=> admin, pronouns, py: argument checking, logging, and better reply on error messages

sopel/__init__.py, sopel/modules/find_updates.py
#1937 cleaned up some unused stuff that should not have been unused. Regardless of how we got here, it's time to put that stuff back in working order.
Coming soon: a companion PR in the website repo to actually generate the right JSON values for this.
Yes, I meant to leave that last checkbox unchecked. I need to implement the website piece, or at least mock up what the JSON will look like and test on a local dev server. That sounds like a weekend project. 😅
=> find_updates: restore unstable release handling

sopel/modules/adminchannel.py
Check the formatted topic against the IRC server's `TOPICLEN`, if sent, and present an error to the user if the topic is too long.
Bonus import cleanup and grammar fix, because I can't resist such things.
Maybe talking about "bytes" is too technical—but the alternative is trying to give a mini-explainer about character encodings… It's probably fine?
=> adminchannel: use `TOPICLEN` token from `ISUPPORT` if available

setup.cfg, sopel/bot.py, sopel/irc/__init__.py, test/test_irc.py
By way of killing (or at least gravely wounding) two birds with one stone, this is my valiant attempt to resolve #1328, and also close #1322—which was left open pending a change like this to make use of the stored hostmask when sending messages. (I say "attempt" mostly because certain @sopel-irc/rockstars might disagree with subtle code style decisions I made; the new logic itself is almost fully covered by new or updated unit tests.)
`bot.say()` now has the ability to calculate a `safe_length` for messages, and use that instead of the arbitrary default value of 400 from `tools.get_sendable_message()`. There is also a new optional parameter, `trailing`, which replicates a common pattern I've seen in my own and other plugins to append some arbitrary "continuation string" to a message that …
=> bot, irc: in `bot.say()`, fill IRC line if possible & add optional truncation indicator

docs/source/configuration.rst, sopel/config/core_section.py, sopel/modules/ip.py, sopel/modules/meetbot.py
Inspired by that raw-logs-not-working problem someone brought to our IRC the other day, which turned out to be due to quotes in the config file, I decided to make some documentation adjustments.
I might have also tried to earn a few bonus points by making `meetbot` enforce its own documented restriction on the meeting log path, which it said should be absolute but which it then allowed to be relative anyway.
=> Path setting and doc tweaks; meetbot enforcement change

sopel/modules/admin.py
Tin.
This was requested on our IRC channel. Instead of just telling the user how to write their own command to do it, I realized that such a feature probably *does* belong in the admin plugin that ships with Sopel.
- Note: I'm relying on tests and other code I've patched recently to prove that `max_messages` works as intended
=> admin: add .chanlist command to show what channels Sopel is in

sopel/coretasks.py, sopel/irc/__init__.py, sopel/irc/utils.py, sopel/logger.py, sopel/plugins/__init__.py, sopel/plugins/handlers.py
This is the final step for 7.1 in #1738. Making these commits was literally just me going through about 1,400 find-in-files results for the string "module". Fortunately I was able to skip a lot with negative regex lookarounds (e.g. decorators, object attributes).
I mixed in a few little tweaks to other stuff, because without them it would have been a _very_ small PR indeed.
In summary:
* coretasks: audit for outdated uses of "module" vs. "plugin" (6fa4bb1)
* irc: audit for outdated use of "module" vs. "plugin" (650e672)
* Some of this actually changes an argument name, something we might not want to do right now (and in fact the "module" moniker goes all the way down into the `CapReq` type from `irc.utils`).
* More importantly, it seems that nothing actually *uses* the `cap_req()` …
=> Audit docs (mostly) for incorrect use of the term "module"

sopel/formatting.py, sopel/modules/choose.py, test/modules/test_modules_choose.py, test/modules/test_modules_isup.py
Briefly, this resolves #1877. No longer will unterminated formatting, or leading/trailing formatting characters, cause formatting issues in the `.choose` command's output.
The custom "strip"/"cleanup" function that makes it all possible comes replete with <del>16</del> <del><ins>20</ins></del> <ins>23</ins> passing cases and 8 expect-fail cases for future enhancements—though I'm sure there are weird cases I haven't covered with the existing test params. Suggestions welcome, and/or we can just see what breaks once this hits the wild.
=> choose: safely handle formatted options

sopel/module.py, sopel/plugin.py
Enough people expressed dismay that our upcoming migration to `sopel.plugin` (from `sopel.module`) would get rid of the plural `commands` decorator family. So we can have both, and plugin devs may choose depending on how they decorate stuff.
```py
@plugin.command('justone')
def one_name(bot, trigger):
pass
@plugin.commands('multiple', 'names')
def two_names(bot, trigger):
pass
```
I gave the aliases very short docstrings that just link back to the main entry, so Sphinx wouldn't duplicate the whole shebang.
Locally built preview:
@Exirel, is adding tests for the aliases worthwhile? I don't feel like bothering. 😝
=> plugin: keep old-school plugin devs happy w/plural command decorators

sopel/modules/tld.py
Without this, some TLDs like `.бел` won't be included in the data table.
Originally added while chasing a different (Heisen)bug (#1945), but unlike that bug, this one was reproducible across multiple parses of the wiki page.
=> tld: small tweak to parser's handling of superscript

setup.py, sopel/cli/run.py
Updates to Python 2.x stopped months ago. Any future release is certain to be installed and run after support stopped, therefore there's no need for wasting CPU cycles on date comparisons.
=> cli, setup: hard-code Python 2 EOL message

sopel/modules/tld.py
Use the Wikipedia API to fetch only [article content](https://en.wikipedia.org/wiki/Special:ApiSandbox#action=parse&format=json&page=List_of_Internet_top-level_domains&prop=text&utf8=1&formatversion=2) instead of scraping the *entire* page.
I'd like to use a better parser, but we probably don't want to add dependencies to the larger sopel repo just for this.
`make qa` currently fails in the same way it does on `master`.
=> tld: Use Wiki API

sopel/coretasks.py
=> core: quit after SASL Auth failed

sopel/bot.py, sopel/config/__init__.py, sopel/config/types.py, test/test_config.py
Fix #1570
To implement this, I added new methods and changed the bot's `setup()` method:
* `sopel.config.Config.get_defined_sections()` retrieves all defined sections, so it's easier to know which sections of the config file are defined in order to check them for unexpected settings
* `sopel.bot.Sopel.setup()` now calls a new method called `post_setup()`, to start the scheduler and perform post-setup checks
=> config: warn if unexpected settings exist

docs/source/plugin.rst, docs/source/plugin/anatomy.rst, sopel/module.py, sopel/modules/seen.py, sopel/modules/version.py, sopel/plugin.py, sopel/trigger.py, test/test_plugin.py, test/test_trigger.py
This is part of #1683: it replaces `sopel.module.intent` by `sopel.plugin.ctcp`. This does not change how "intents" are managed internally by Sopel, which should be done later, possibly in Sopel 8 or maybe Sopel 9.
Also, because CTCP is mostly used for ``ACTION``, this is now the default: you can use `ctcp`, `ctcp()`, or `ctcp('ACTION')` to achieve the same result.
I updated the doc and tests accordingly.
=> plugin: replace intent by ctcp

sopel/irc/utils.py, test/irc/test_irc_utils.py
`sopel.irc.utils.safe` wasn't tested, now it is. Also with a better docstring.
=> irc: test sopel.irc.utils.safe function

test/test_tools.py, test/tools/test_tools_time.py
More tests for `sopel.tools.time`.
=> tools: more tests for sopel.tools.time

docs/source/plugin/anatomy.rst, sopel/bot.py, sopel/modules/adminchannel.py, sopel/plugin.py, sopel/tools/target.py, test/test_bot.py, test/test_plugin.py, test/test_tools.py, test/tools/test_tools_target.py
This wasn't requested, and probably not needed that much. However, when reading the code for #1981 I realized that we repeat a lot of code, so I figured out I could add these:
* `bot.has_channel_privilege(channel, level)` will tell you if the **bot** itself has the right privilege level,
* `plugin.require_bot_privilege` is a new decorator that uses this new method,
which is probably useful only for channel administration. Probably.
Anyway, it has tests, and it gave me some ideas for the future (in particular, how we could manage more complex privilege check). So it's good!
OK, after second thought, I realized I could improve the `sopel.tools.target.Channel` class, by adding privilege related methods, and use one of these methods into the bot.
However, I found out that there is no test for …
=> plugin: new `require_bot_privilege` decorator

sopel/modules/tell.py
Because our users apparently think they're still mentioning users on discord and need this.
Removes @ if at start of nicknames
=> tell: remove @ from start of nicknames

sopel/modules/instagram.py, sopel/modules/reddit.py, sopel/modules/tld.py, sopel/modules/wikipedia.py, sopel/modules/wiktionary.py
This updates every core plugin I could find with an existing handler for "too long" output (`instagram`, `reddit`, `tld`, `wiktionary`, & `wikipedia`) to use `bot.say()`'s new `trailing` parameter from #1958.
Two things that _might_ be worth amending, if others think my thought process or assumptions were wrong:
* `instagram`: I rearranged the output to put the caption (most likely to be over-length) at the end. A subsequent commit to this branch (to `wikipedia`) showed a neat hack that would allow leaving the caption where it was, in the middle of the line, but it seems to make the most sense at the end anyway.
* `reddit`: I did _not_ change submission output to use `trailing`, because:
* The title is the very first thing in the output
* The submission's link might also be very long, and …
=> modules: use `bot.say()`'s `trailing` parameter

sopel/coretasks.py, test/test_coretasks.py
As per the discussion in #1496 this makes Sopel send a `PROTOCTL NAMESX`  command when:
1. we receive a RPL_ISUPPORT message from the server
2. multi-prefix is not an available capability
3. NAMESX is now activated
=> coretasks: NAMESX when multi-prefix is not available

sopel/coretasks.py
Now that the bot tracks advertised ISUPPORT tokens, there's no longer any reason to guess based on enabled capabilities. If WHOX is advertised in ISUPPORT, use it. If it isn't advertised, don't use it. Simple.
Eliminated the function call for efficiency, since it's easy to put back if the logic becomes more complex again in the future. There were only two call sites.
This could have unintended consequences if servers that advertise the account-tracking capabilities Sopel used as heuristics before don't advertise the WHOX token in ISUPPORT, but (unless deeper research proves otherwise) that sounds like incorrect implementation on the server side.
Related: #1496
=> coretasks: WHOX availability checks use ISUPPORT

sopel/plugin.py, sopel/test_tools.py, sopel/tests/pytest_plugin.py
Since the last refactoring, the only purpose left for `sopel.test_tools`  was to provide utility functions for `sopel.plugin.example`. Since this feature always requires pytest, I figured that it would be better to nuke `sopel.test_tools` in Sopel 8 and to move everything still relevant to that plugin.
A second round of refactoring in Sopel 8 might be done at some point to rework how pytest is used to discover example test, but that's for another time and certainly not something to do in this PR.
=> tests: deprecate test_tools; replace with tests.pytest_plugin

sopel/loader.py
This is (hopefully) the last PR needed to close (eventually) #1565, by improving docstrings of `sopel.loader`.
At some point, I might want to deprecate `sopel.loader` by moving its best parts in `sopel.plugins`, but that's another story for another day.
=> loader: improve docstrings

sopel/coretasks.py
Working on #1565, for the `coretasks` core plugin. I wanted to do a quick first draft for @dgw to review.
I'm not really proud of these docstrings. On the other hand, I think we need a full chapter to explain how Sopel initialize the connection, deal with SASL, WHO/WHOX/NAMES, and stuffs. So it's not really my biggest concern.
My biggest concern is the lack of test for this plugin. I might add them here, maybe. We'll see.
=> coretasks: trying to improve docstrings

sopel/plugins/__init__.py, sopel/plugins/handlers.py, sopel/plugins/jobs.py, sopel/plugins/rules.py
Part of #1565 for `sopel.plugins`.
Most of the changes are missing `.` and removing initial capital letter in `param/return` tags.
Then I tried to improve the docstrings for `sopel.plugins.handlers`, in a somewhat better version.
=> plugins: improve docstrings according to project standards

sopel/irc/isupport.py, test/irc/test_irc_isupport.py
Reduce boilerplate necessary for plugins that use `isupport.CHANMODES` by returning `{"A": "", ...}` instead of raising AttributeError if the server hasn't given us info.
See https://github.com/sopel-irc/sopel/pull/1980#discussion_r554754569
=> isupport: return empty CHANMODES if unavailable

sopel/coretasks.py, sopel/tools/target.py, test/test_coretasks.py
Depends on #2015. Implements most of #1789. Groundwork for #1842.
Teach Sopel to track all channel modes in `channel.modes`. Uses `isupport.PREFIX` to check valid user priv modes and `isupport.CHANMODES` to see what's valid and what's expecting arguments. Also reduces the number of panic WHOs we need to send.
Sends a MODE query after a JOIN is received to populate initial modes and implements RPL_CHANNELMODEIS.
It may or may not be worth also sending a `MODE +b` and parsing that to get the initial ban list. Would require implementing RPL_BANLIST.
It may be good to test sending WHO and MODE after a channel join, I didn't see it tested but my attempt wasn't working and it's late.
=> coretasks: track all channel modes

sopel/modules/adminchannel.py
Allow `.topic` for all users in channels without `+t` set.
Keeps topic mask related things op-only.
Depends on #1980. Improved with #1982. Fixes #1842.
=> adminchannel: allow non-op .topic in -t channels

sopel/bot.py, sopel/irc/__init__.py, sopel/irc/backends.py, sopel/trigger.py
This is related to  #1647. It doesn't fix it but we may consider it done nonetheless.
What I looked at was how we use datetime internally and in various plugins, to check if everything was working fine. Result is: no, but it's OK, I fixed it with this PR.
The biggest issue I found was a repeated usage of `timedelta.seconds` that I replaced by `timedelta.total_seconds()`.
=> sopel: using utcnow and fixing minor issues with datetime

docs/source/configuration.rst
=> doc: add examples to configure auth

sopel/modules/safety.py
Resolves #2008 with a new domain list for checking URL `safety` against known malware/adware sites.
- left as an exercise for CI because my WSL is slow 🙃
=> safety: switch from malwaredomains (dead) to StevenBlack hosts list

sopel/modules/find.py
Attempted fix for #1188
So it was kind of messy because working with backreference to negate them is (not) surprisingly hard to do. I got [some help from StackOverflow](https://stackoverflow.com/questions/8055727/negating-a-backreference-in-regular-expressions) but I had to let go of the "you can escape the separator to use it inside the substitution/editing text ".
But heh, on the other hand, as one of the authors of the previous regex, if you want both / and | as separator AND having both in a substitution message:
> you're shit out of luck because this is the fucking regex of death as it is.
PS: it was on @dgw 's task list, but I did it anyway out of curiosity for regex backreference.
=> find: use slash or pipe in sed-like command

sopel/modules/remind.py
Fix #1746 
Add a new `reminders` command with subcommands:
* `.reminders` will use the `count` subcommand by default
* `.reminders count` will count all reminders in the current target (either the current channel or in private messages)
* `.reminders forget` will forget all reminders in the current target (either the current channel or in private messages)
* using a third argument will limit each action to that target
* using `*` (wildcard) as the target will act on all possible targets, i.e. all the channels and in private messages
For example `.reminders count *` will give you the sum of all reminders from every channels and every private message for **you** (and you only); and using `.reminders forget` in a private message will make the bot forget about your private reminders only. …
=> remind: .reminders count/forget command

sopel/plugins/rules.py, test/plugins/test_plugins_rules.py
When I implemented the new rule system, I made the methods that were necessary to be backward compatible with the bot's doc, which is used by the help plugin, but nothing more.
However, now that I have extended that to all type of rules (including commands and URL callback), it was time to add the appropriate methods for all types of rules.
=> rules: add get-all methods for all types of rules

docs/source/_static/custom.css, docs/source/plugin/bot.rst
As many questions have arisen on IRC about formatting and stuff, I figured I could improve the documentation about that. There is now a new section in the chapter "Interact with the bot" about working with the bot "with style".
Reviewers may be confused as to why I had to add custom roles and CSS class, but worry not, that's the only way to do it properly.
We may want to add further warnings about control code, because formatting in IRC depends on the client's implementation.
=> docs: do it with style: interact with the bot

sopel/modules/find.py
This simply applies the bold formatting to whatever the new replacement text is rather than the "meant" text.
=> find: format replacement text instead of "meant"

docs/source/plugin.rst, docs/source/plugin/advanced.rst, sopel/coretasks.py
Fix #2017 and add a new chapter for advanced tips and tricks.
=> coretasks: update event priorities from high to medium

sopel/logger.py
When `core.logging_channel` is used, errors early in startup cause an exception that halts the bot. (bdc10e037dc2bea81bf87871a2c18c61fe02cf99, current master)
sopel.cfg
```ini
[core]
host = fake.local
logging_channel = #services
owner = mal
enable = version
foo = bar
```
Start the bot: `sopel start -c sopel.cfg`
```
File "sopel/logger.py", line 32, in emit
if not self._bot.backend.is_connected():
AttributeError: 'NoneType' object has no attribute 'is_connected'
```
<details><summary>full logs</summary>
```
(env) [mal@nova sopel-test]$ sopel start -c sopel.cfg
Sopel 7.1.0.dev0 (running on Python 3.8.5)
https://sopel.chat/
Loaded config file: /home/mal/sources/sopel-test/sopel.cfg
[2021-01-23 03:18:54,137] sopel.bot            INFO     - Loading plugins...
[2021-01-23 03:18:54,142] …
```
=> logging: don't crash if backend is uninitialized

sopel/coretasks.py
This takes care of a random note I left myself a while ago, which didn't justify its own issue.
Avoid `dict()` constructor; always use `{}` literal instead.
`bot.memory['retry_join']` is better as a `SopelMemory` object, as it's modified from threaded code.
=> coretasks: tweak dict usage

sopel/modules/reddit.py
Just a grammar issue that's been annoying me for too long already. Tested with a very imaginative "random" Reddit submission ID, 123456 😼
Before (emphasis added):
> [reddit] I'm thinking about getting a dog and YouTubed ways to train them. Then I came across this video (http://www.youtube.com/watch?v=b9upM4RbIeU&feature=g-vrec) to r/funny | 0 points (50.0%) | **1 comments** | Posted by cocobunny | Created at Thursday, October 25, 2012 15:53:08 -0500
After (emphasis again added):
> [reddit] I'm thinking about getting a dog and YouTubed ways to train them. Then I came across this video (http://www.youtube.com/watch?v=b9upM4RbIeU&feature=g-vrec) to r/funny | 0 points (50.0%) | **1 comment** | Posted by cocobunny | Created at Thursday, October 25, 2012 15:53:08 -0500
=> reddit: show singular "comment" in post output when appropriate

sopel/tools/time.py, test/tools/test_tools_time.py
Fix #1824 
Expose intermediate functions: one to split a time in seconds into a tuple of (years, months, days, hours, minutes, seconds) and the other that take that information to return a tuple of 2-value tuple with (value, unit).
Also, while I was working on making `second_to_human` more reusable, I added a `granularity` parameter, because why not.
=> tools.time: improve seconds_to_human

sopel/loader.py, sopel/plugins/rules.py, sopel/tools/__init__.py, test/test_loader.py
See #1887.
This is only a draft, because it introduces a major change in `loader.clean_callable`: since `compile_rule` becomes deprecated, it is not used anymore by `loader.clean_callable`. It means that this function doesn't compile patterns anymore. So, even though it doesn't change *anything* for plugins that don't tinker with `loader` themselves (but why would they?), it doesn't generate any change and it should be transparent.
The documentation says that `sopel.loader` is for internal purpose, that it may and probably will change without warning, and that the documentation for this module is here for internal dev only. So, technically, it's **not** a breaking change, because that part of the API is documented as **not public**.
However, if we want to minimize the risk of a plugin …
=> tools, loader, plugins.rules: deprecate compile_rule

sopel/modules/url.py
Close #1870
And because nothing is simple: I also added aliases for `urlpban` and `urlpunban` to ban/unban patterns instead of URL directly.
=> url: urlexclude/allow commands; auto-title ignores URLs in ANY other command

sopel/modules/url.py
Tin. Goes slightly beyond the previous error messages with a special case for failing to fetch all URLs in a list of 2+. Fixes #1946.
=> url: restore error output when not all `.title` URLs could be fetched

sopel/tools/__init__.py
Allows specifying which stack frame to show in the traceback, if the default (the most recent) isn't helpful. Sometimes the parent caller or a more distant ancestor is more informative to the end user.
Inspired by challenges encountered when working on #2044. This should be merged first if approved.
I seriously considered making `stack_frame` just a plain integer, and not requiring the negative sign, just because 99% (maybe even 100%) of all use cases are going to want a frame relative to the _end_ of the list generated by `traceback.extract_stack()`. But it's more intuitive to make the argument the same value as the list index used inside the decorator…
=> tools: add `stack_frame` kwarg to `deprecated` decorator

sopel/bot.py
Tin. Replace #1809 
I had to mark callbacks to prevent raising the same warning more than once.
I accept the trade-off: this won't cover 100% of cases and I'm fine with that. It'll cover the most common one, when it was common to declare URL callbacks in the `setup` hook because `@url` didn't work well.
=> bot: emit warning when memory['url_callbacks'] is used manually in a plugin's setup

sopel/modules/currency.py, sopel/modules/meetbot.py, sopel/modules/pronouns.py, sopel/modules/wikipedia.py
What does this do? What problem does it solve? Does it resolve any GitHub issues?
=> modules: add missing help messages

sopel/bot.py
Tin. They were a stopgap, and they have served their purpose.
=> bot: deprecate (un)register_url_callback() functions

sopel/config/types.py, test/config/test_config_types.py
Was going to move the helper functions used in `ValidatedAttribute` when `parse == bool`, but it would've required some ridiculous polymorphism. Better to just leave the old stuff—which will also make it easier to mark as deprecated.
Maybe we need to add tests that cover the `default` parameter to some or all of these setting types? I'll chew on that.
When complete, this will implement and close #2019.
=> config.types, test: add `BooleanAttribute` setting type

sopel/irc/isupport.py, sopel/modules/announce.py, test/irc/test_irc_isupport.py
=> irc.isupport, announce: fix unexpected error (get) from .announce

docs/source/configuration.rst, sopel/bot.py, sopel/config/core_section.py, sopel/coretasks.py, sopel/irc/__init__.py, sopel/irc/backends.py
In an attempt to fix a bug (see #2038) I added more logs (not sure it will be that useful in the end) and changed slightly how the bot manage its PING and timeout:
* remember the last time a PING was sent
* check for PING more often
* make the PING interval configurable (`core.timeout_ping_interval`)
* check for timeout more often (but keep the same delta)
* clear the buffer on timeout and IRC error
My current test didn't allow me to check if it actually solves the issue, but the change could help with that and it's still better than before anyway.
In theory, I could have removed the `os._exit` in `sopel.cli.run`, because locally it works quite nicely without it now, but that will be for another time.
I assign this PR to @dgw as he needs to install this branch on a test instance, and see …
=> irc: timeout and logs

sopel/cli/config.py, sopel/cli/plugins.py
=> cli: various user-friendly error messages

sopel/bot.py, sopel/irc/__init__.py, sopel/modules/reddit.py, sopel/modules/tld.py, sopel/modules/wikipedia.py, sopel/modules/wiktionary.py, test/test_irc.py
Addresses a shortcoming of the `trailing` parameter, which alone is insufficient to handle some common output patterns used by Sopel's own core plugins.
For example, the `wikipedia` plugin outputs article snippets in between quotation marks. Long snippets are truncated and the quote closed by the `trailing` parameter, but short snippets never invoke `trailing`. They lose both the closing quote AND the URL linking to the full article.
With these now _two_ optional parameters (`truncation` and `trailing`), it will be easier for plugins to include variable-length data in "the middle" of a message and still guarantee that any important information at the end of the line will be shown.
~~The name `finial` is the best idea I could think up while writing this patch, but there's probably a better …
=> irc: more ways for `bot.say()` to help with overlength messages

sopel/modules/find_updates.py
Even if there haven't been enough check failures to trigger a warning to Sopel's owner, it still needs to skip trying to print the `info` about whatever new release is available because that variable doesn't exist.
Missed in #1779 / 951fccaccf5f4bdb70058a326543c1d82354c453, oops.
Relying on reporter (@RhinosF1) to see if the bug is still reproducible with this patch.
=> find_updates: return in ALL the appropriate failure cases

sopel/modules/currency.py
This fixes two gaps in the `currency` plugin's error handling:
1. `KeyError` was not handled. Such an exception could result if the exchange rate API returns valid JSON that doesn't contain the expected keys (perhaps an error reply).
2. `rates_updated` was refreshed before executing all code that could prematurely terminate the update operation, leading to some (but not all) of the data being stale for at least 24 hours until the next full `update_rates()` run.
Additionally, catching `KeyError` will allow the bot to continue converting the input as normal if it has rates cached.
- Theoretically, at least. I don't have a good way to generate API errors at will. A good future enhancement would be writing a test suite for this plugin in `test/modules/test_modules_currency.py` that explicitly …
=> currency: improve error handling

dev-requirements.txt, sopel/modules/find_updates.py, test/modules/test_modules_find_updates.py
Validates the behavior fixed in #2052.
- On Python 3.8, _and_ (accidentally) 3.3. The latter's the version I was worried about breaking, anyway.
Haven't milestoned this yet, as I'm not sure if I want to add a new dependency (even only for dev) on 7.1.x this late. Looking for second opinions before I decide!
=> find_updates, test: create test to verify error case behavior

sopel/config/core_section.py, sopel/modules/admin.py, sopel/modules/currency.py, sopel/modules/help.py, sopel/modules/safety.py, sopel/modules/tell.py, sopel/modules/url.py
This just eliminates a bunch of deprecation warnings that we probably don't want to ship in 7.1.0.
These should have been fixed as part of #2044, but past-me was apparently quite lazy. 🙃
However they were also the inspiration for, and an easy way to test, #2058. 🙂
=> core, modules: replace deprecated uses of `parse=bool` in settings

sopel/modules/currency.py, test/vcr/modules/currency/test_example_exchange_cmd_0.yaml
exchangeratesapi.io was bought and started requiring an API key. 🙄
Rather than just replace it with another Fixer-compatible service, I decided to build out the logic for choosing a provider because I found _two_ good replacements (partly thanks to @xnaas). Setting `fixer_io_key` still uses Fixer regardless of the chosen `fiat_provider`, for backward compatibility reasons, but also logs a warning at each rate update.
Every time I touch the VCR.py cassettes, I worry that something about the format will be incompatible with one of the older Python versions and break CI. We'll see. If something does break, I'll try re-recording with py3.3 (which I can run locally, somehow).
=> currency: API switch & backup option

sopel/tools/__init__.py
No more `stderr()` calls!
One notable exception: If a `core` section setting uses some deprecated behavior, that warning will not be logged in the usual way because logging isn't set up yet. The bot _has_ to load its core settings before it can get logging up, since that's where the logging itself is configured. Core plugins' `StaticSection`s get loaded later, after logging is available, so they work as expected.
We core devs will just have to pay attention to the console output during testing in the future if any more config stuff used by the `core` section gets deprecated. It's not something that end-users (or even plugin devs) will need to worry about.
- Before: Lots of deprecation warnings from core plugins about using `BooleanAttribute` instead of `ValidatedAttribute` with …
=> tools: Convert `deprecated` decorator to use logging output

sopel/modules/wiktionary.py
I noticed that fetching etymology from Wiktionary would fail sometimes, even though the section was there. Tracked down the exact code path with the help of `pdb`. Two related fixes:
* Don't check for extraneous `id` attributes in the HTML when in `etymology` mode (in `wikt()` function)
* Allow for multiple citations (`<sup>`/`</sup>` pairs) in one line when stripping HTML (in `text()` function)
I really want to convert this to a proper parser, but don't want to further delay 7.1. Onto the idea pile it goes.
=> wiktionary: fix fetching etymology containing citations

sopel/modules/currency.py
The current code only adds more precision when converting bitcoin. Other crypto currencies are also valued such that they return very small numbers.
This change finds the required amount of digits to display at least 2 non-zero decimals.
It also adds thousands separators to the reply.
One issue was reported by make qa, but in help.py (ambiguous variable name l)
=> currency: add thousands separator, dynamic precision, and optional HTTPS for Fixer

sopel/tests/factories.py, sopel/tests/mocks.py, sopel/tests/pytest_plugin.py, test/modules/test_modules_isup.py
tl;dr: Threaded callables can cause race conditions during tests, but the `MockIRCServer` is in a perfect position to make sure they don't (and it now does so).
I had a very interesting time this past weekend, trying to write tests for #2063 that simply wouldn't work, no matter what I did, until eventually the idea came to me: "Try it with the plugin callable set to unthreaded." After that, and an IRC discussion wherein @Exirel reminded me that the `bot.running_triggers` property exists, those tests got written and merged.
Now this new feature inspired by the above process is ready to be "formally" proposed. I spent some time on the documentation for it, proved the concept by running the test suite on _three_ local Python versions (2.7, 3.3, and 3.8), and am reasonably confident that this …
=> tests: `MockIRCServer` methods should block by default

sopel/modules/find.py
Tin. I did a `s/something //` replacement to delete an extra word recently and realized that the line contained two useless bold formatting bytes anyway, because that's how the logic was written and I didn't think of this case during review of #2014.
=> find: don't output useless bold formatting for empty replacement

docs/source/plugin.rst, docs/source/plugin/test.rst, docs/source/tests.rst, sopel/tests/mocks.py, test/tests/test_tests_mocks.py
After discussing #2065 it appears that "how to test a plugin" isn't well documented, so here is a PR for that.
I think there are more that can be written, in particular about factories and how to use them.
I also added a convenient method to clear `backend.message_sent`, so you don't have to do it manually. It's useful when you have a bunch of automated messages, or when you don't want to write more than one test method for different yet very similar use cases (for example: trigger by a regular user vs admin vs owner).
=> docs: plugin tests & minor improvement

sopel/modules/pronouns.py
Adds 2-word common pronoun sets. 
Closes #2068 
I didn't check it on my machine because it feels trivial. Let me know if you want me to test it properly.
=> pronouns: add 2-word pronouns aliases

.github/ISSUE_TEMPLATE/config.yml, NEWS, README.rst, contrib/sopel.cfg, docs/source/cli.rst, docs/source/configuration.rst, sopel/config/__init__.py, sopel/config/core_section.py, sopel/modules/find_updates.py, sopel/trigger.py
Tin.
I elected to leave the tests alone, since those could just as well use `irc.example.com` and work exactly the same way.
Updated the NEWS entry for v6.6.0 just so future release archives and changelog pages on the website won't point people to an abandoned channel on freenode. Probably could leave it alone, but it's easy to update along with everything else.
=> Substitute Libera Chat for all public-facing references to freenode

sopel/loader.py
Our own `trim_docstring` function is OK, but definitely not perfect. What it returns can be inconsistently indented depending on whether the docstring passed in is single- or multi-line, or whether a multi-line docstring starts on line 0 or line 1 (next to or below the `"""`). It's nice to have consistent indentation.
I don't have any strong feelings about where to implement this. Maybe it would make more sense to apply `inspect.cleandoc()` inside the logic of `trim_docstring` instead of using `inspect.getdoc()` on the callable. Either way, our help infrastructure will be easier to improve if we eliminate anything like this that can cause inconsistent output.
- ~~Not tested yet (see notes)~~ CI did its job
- Well, I did when I wrote the patch last year…
I know this has a merge conflict; …
=> loader: use `inspect` to make callable docs consistent

sopel/modules/currency.py, test/vcr/modules/currency/test_example_exchange_cmd_0.yaml
ratesapi.io appears to have been bought, too. exchangerate.host is now the default, and the only keyless API included.
Thanks for buying fucking everything, apilayer, I hate it.
This is why `currency` will be one of the first plugins I extract to a standalone package in preparation for 8.0. Just keeping it working is becoming a game of reverse whack-a-mole.
=> currency: switch default to exchangerate.host; remove ratesapi.io

.travis.yml
Oldest tested Python platform is now Python 3.6, set to reach end-of-life in December 2021.
This will help us conserve build credits, since Travis CI shifted to requiring manual grants of credits for open source projects on their newer infrastructure, leaving behind the straightforward system that had been in place for many years on their .org platform.
Somewhat related to this: We will be focusing more attention on a move to GitHub Actions in the coming weeks...
Doing this separately from #2062 as it's time-sensitive: Travis will shut down the .org platform and force us onto their strictly metered .com infrastructure in just over a week, so it's important to get this merged as soon as the 7.1.0 release is cut and stretch our credit balance as far as possible while we hopefully migrate …
=> build: remove EOL Python versions from Travis config

.github/workflows/ci.yml
As of right now, the GitHub Actions CI workflow will run on forks too.
This PR checks the workflow context to see if events are for the 'sopel-irc' owner, and only runs jobs if so. This check can/should be moved/updated as new jobs are defined, or if the event/branch filter for the CI workflow changes.
> <sup>1</sup>As best as possible. Confirmed that adding this prevents from running on my fork.
=> gha: only run jobs when events are for 'sopel-irc' owned repos

sopel/modules/tld.py
Tin. Using `del bot.memory[key]` is not safe; the keys used by this plugin must be reset to their default values.
Workaround in 7.1.0 is to run `.tldcache update` immediately after `.tldcache clear`, or to run ONLY the `update` subcommand.
This is what I get for trying to be cute with the loop-based approach.
=> tld: fix `.tldcache clear` command breaking `.tld` until manual update

sopel/config/types.py, test/test_config.py
Makes `default=True` work correctly for `BooleanAttribute`s - see: url.py not working in 7.1.0.
I'm not sure why that stub was overridden, but I can't think of a reason BoolAttr would need to behave differently from the normal `BaseValidated._parse()`. @dgw?
Includes lazy test of default default and default=True. It might belong in test/config/test_config_types.py but that's harder and I'm out of time and brain to melt.
=> config: fix BooleanAttribute default=True

sopel/plugins/rules.py, test/plugins/test_plugins_rules.py
Invalid URLs can crash Sopel's URL handling, as reported on IRC by @RhinosF1. The traceback is included below for reference.
We handle it now by simply skipping any URL that causes the underlying library (`urllib.parse` from Python's standard library) to throw a `ValueError` when `plugins.rules.URLCallback.match()` tries to determine its scheme.
Includes a new test verifying the behavior—and more importantly, the lack of an exception being thrown.
Also fixes an incorrect classname in one of the other `URLCallback` tests, in a separate commit.
```
[2021-06-05 10:03:52,811] sopel.exceptions     ERROR    - Fatal error in core, handle_error() was called.
Buffer:
Last Line:
@account=mirahezebots :MirahezeRC!~MirahezeR@miraheze/bots PRIVMSG #miraheze-feed :famepediawiki 5* 14[[07Yasir Tech14]]4 …
```
=> plugins.rules: `URLCallback` shall handle invalid URLs by ignoring them

docs/source/configuration.rst, sopel/config/__init__.py
No issues to reference or anything. Just was pointing someone on IRC to docs that would explain an error they got, and noticed that the docs I was referencing weren't actually quite up-to-date any more.
- Didn't bother with tests; no code touched. 😝
- It doesn't touch code.
Specifically requesting Exi to review, because he was the last one to touch logging and I want to be sure the revised docs reflect his intentions for the different files (esp. `errorfile` vs. `exceptionfile`).
=> docs: fix some outdated stuff about configuration/logging

sopel/coretasks.py
`who_reqs`, which is used to track `WHO` requests to the server, had flipped
keys/values and was never getting cleared upon `RPL_ENDOFWHO`.
Eventually, this would lead to an endless loop while the bot tried to
get an unused "querytype" (`randint`) in order to track `WHO` replies.
Now, key/values are in a more useful order (channel --map--> querytype).
Also, the unneccessary loop used to ensure unique values for the query type was
removed. A `RPL_WHOREPLY` includes the channel name in the response, so
confirming that the querytype for a channel matched is sufficient. The same
querytype could even be used for every channel without issue.
=> coretasks: fix bad WHO tracking endless loop

test/cli/test_cli_run.py, test/cli/test_cli_utils.py, test/test_config.py
If a developer has ENVs set for CLI overrides (i.e., `SOPEL_CONFIG`, `SOPEL_CONFIG_DIR`), some tests in `test/cli/*` will fail due to those ENVs leaking into tests. Specifically, tests that assume:
- `options.config == 'default'`
- `options.configdir == config.DEFAULT_HOMEDIR`
Adding a `autouse=True` fixture to clear those specific vars resolves this, while retaining proper testing of ENV overrides as implemented.
Also, in the same vein, added tests for ENV overrides for actual config settings too.
**Notes**
<sup>1</sup> No lie this time! Last two PRs actually failed the CLI tests referenced in this PR but I still checked the box :sweat_smile:
=> tests: fix+add ENV override tests

sopel/trigger.py
As far as I can see, trigger.py only ever has `args=thing.split()`, so will only ever be a list. Either the docs should reflect that, or we should tuple() those.
=> trigger: document that `args` is a list

sopel/coretasks.py, test/test_coretasks.py
Reduce "possibly malformed MODE" logspam, and warn with useful info if we still have extra args.
I can't think of a case where we would need a legitimate empty arg, and the continued presence of the previous comments seems to agree, so... Let's just assume a trailing space is a meaningless trailing space.
(If we're *short* args, we'll... still get an uncaught `IndexError`. Should that be handled better?)
=> coretasks: Strip Unreal's extra empty MODE arg

sopel/coretasks.py, test/test_coretasks.py
RPL_CHANNELMODEIS should contain all channel modes, and we sometimes use `MODE {channel}` to sync, so we should discard our old knowledge of the modes when we get the response.
=> coretasks: Clear prior modes on RPL_CHANNELMODEIS

docs/source/configuration.rst, sopel/config/core_section.py
Add an example for having Sopel authenticate to ZNC, inspired by a user in IRC confused by `auth_username` not working with `auth_method=server`.
Also corrects/clarifies/creates a few other things:
- auth_password: used for server auth too, not just user
- please click the directives, I don't want to have to remember to update things in two places
- auth_method=userserv also uses auth_target
- when is auth_username ignored/required (previously: infinite docloop)
=> docs: config/auth: clarify auth_username, etc

sopel/modules/tell.py
This is one trivial tweak plus one trivial bugfix bundled into one PR, because it would be extremely silly to make two.
- Fixed a TODO that should have been done for 7.1.0: use `NICKLEN` from `bot.isupport`
- Fixed hardcoded "tell" in the error message when `tellee == bot.nick`
- Note that this is not tested code, so I only used `make quality`
=> tell: use correct verb when `tellee == bot.nick`; use `NICKLEN` if available

docs/source/plugin/bot.rst, sopel/plugin.py, sopel/tools/__init__.py, sopel/trigger.py
Very often we get questions on IRC on how to get a list of users from a channel. I thought the doc was explicit enough and I was wrong. Therefore, I try to fix that issue by adding more documentation in the "Interact with the bot" chapter.
At some point, we might want a chapter just about channels, users, and privileges, but that'll be for another day. I tried to update the doc just enough to fit into the 7.1.1 release, without delaying it too much.
This new doc gives me even more ideas of methods to add on the channel object, and that too will wait Sopel 8.
=> docs: more details about users in channels

sopel/modules/safety.py
One single comment in the StevenBlack list contains one single Unicode character that the 'ascii' codec doesn't like.
This will never be necessary on the master branch, which is about to permanently remove support for Python 2; py3 uses `utf-8` by default in its `str` constructor.
- It pained me to run Sopel under py2 again, but I did it for science.
=> safety: prevent UnicodeDecodeError on startup under py2

docs/source/configuration.rst
Noticed that while the docstring for `core_section.CoreSection.owner` specifies that it's always required, the "Owners & Admins" docs chapter didn't say anything about it, which could lead users to be confused.
- Doesn't touch any `.py` files, so I didn't run those.
- N/A, like the above
Don't know yet if we'll need a 7.1.2 release, but I'm sure it'll happen. This is the first PR for it, apparently.
=> docs: be even more specific that `owner` is ALWAYS required

docs/source/configuration.rst, docs/source/plugin/anatomy.rst
We were going to make `core.owner` optional in Sopel 8, but that's not wise. The setting is used to send important notices to the bot's owner, and so it has to be set with a proper value even if `core.owner_account` is being used for verification (e.g. `plugin.require_owner`).
**Can** be merged with a `[skip ci]`, as it only touches docs.
**Should** be cherry-picked back to 7.1.x with a `[skip ci]` so as not to burn Travis credits.
=> docs: clarify relationship between `owner` and `owner_account` (again)

sopel/modules/pronouns.py
Checks:
- all five provided ("they/them/their/theirs/themselves")
- prefix matches ("they/them[/...]", common)
- subject/object/possessive ("they/them/theirs", common)
- ellipsised ("they/.../themself", for compatibility with sopel 7.0 and pronoun.is)
~~Also fixes a typo ("eirslef").~~
~~Closes~~ #2068
Furthers #2069
```
< mal> .setpronouns ze
< Sopel> mal: Thanks for telling me! I'll remember you use ze/hir/hir/hirs/hirself. Or, if you meant one of these, please tell me: ze/zir/zir/zirs/zirself
< mal> .setpronouns ze/hir
< Sopel> mal: Thanks for telling me! I'll remember you use ze/hir/hir/hirs/hirself.
< mal> .setpronouns they/.../themself
< Sopel> mal: Thanks for telling me! I'll remember you use they/them/their/theirs/themself.
< mal> .setpronouns they/them/theirs
< Sopel> mal: Thanks …
```
=> pronouns: accept they/them and they/them/theirs

sopel/coretasks.py, test/test_coretasks.py
If the server advertises a `BOT` token in `005 ISUPPORT`, Sopel will set that mode on itself unless that modechar appears in the value of `core.modes` in its configuration.
Implements part of #2079.
- By the power of `pytest`, yes!
The default value of `core.modes` is `B`, which is the conventional modechar to advertise for `BOT`. Thus this won't do much on most networks unless the user overrides `core.modes` and doesn't know about this mode.
Note to self: Prepped a support table update for IRCv3 [here](https://github.com/ircv3/ircv3.github.io/compare/master...dgw:sopel-bot-mode?expand=1).
=> coretasks: handle `BOT` ISUPPORT token & mode

sopel/coretasks.py, test/test_coretasks.py
Completes part of #971, adding support for the `userhost-in-names` IRCv3 CAP, with fallback to the older `UHNAMES` ISUPPORT token.
- **Note:** Have not explicitly tested `UHNAMES`, but [the `userhost-in-names` spec](https://ircv3.net/specs/extensions/userhost-in-names) says it's "the same extension".
=> coretasks: add `userhost-in-names` CAP and `UHNAMES` ISUPPORT token

docs/source/configuration.rst, sopel/config/core_section.py, sopel/coretasks.py, sopel/irc/__init__.py, sopel/irc/backends.py
Tin. Followed Libera's instructions for generating a certificate and added its fingerprint to our official Sopel bot's account in NickServ, then stuck around in my human-operated client to observe. **Flawless victory:**
```
[00:53:18] -NickServ- SopelTest!~sopel@68.168.def.abc has just authenticated as you (Sopel)
^ my home IP ^
```
**@dgw pls update IRCv3 support info for Sopel when this is merged**
This lays some groundwork for expanding into SCRAM challenges, as implied by a new TODO comment, but implementing those will take some more research. I had some pseudocode for it in there, but obviously removed it before committing (otherwise linting would probably fail).
As far as actually getting SCRAM into Sopel goes, the options are:
- choose a library — possibly …
=> coretasks, irc: implement CertFP / SASL EXTERNAL authentication

sopel/irc/__init__.py, sopel/irc/backends.py
Print rawlog with `repr()` so we don't need a hex editor to find problems with whitespace or non-printable characters.
Don't `.strip()` messages headed for rawlog, which currently obscures problems with whitespace.
Add logging (warning) and rawlogging of messages that couldn't be decoded, which were previously silently ignored. New rawlog prefix: `<<!`
Each part of this is a breaking change if any madman is parsing the rawlog, but I don't think we consider that part of the API...
QA passes, but this does change handling of IRC's message separators in ways that may have corner cases I haven't found:
- Switches asynchat to break messages on `b'\r\n'` instead of `b'\r'`. Do any real-world daemons use only `\n`?
- Puts the `\r\n` back on before decoding/logging. I'm not sure how far that goes …
=> irc: Use repr() and don't strip() rawlog, log charset guess failures

sopel/modules/admin.py
Adds a `.raw` command to `admin.py` to allow commanding the bot to send a raw IRC message, e.g. `.raw OPER Sopel ThisIsABadIdea123`
=> admin: add .raw command to send raw IRC messages

sopel/coretasks.py, test/test_coretasks.py
Reduces churn in `bot.users` and `bot.channels` on networks that support the `chghost` CAP, since they send a flood of QUIT, JOIN, and MODE lines to connected clients without `chghost` support in order to emulate the CHGHOST behavior.
Checks another box in #971. Also fixes a likely typo in a nearby coretasks test.
[`chghost` spec](https://ircv3.net/specs/extensions/chghost) for reviewers' reference.
=> coretasks, test: support CHGHOST command/capability

sopel/coretasks.py, test/modules/test_modules_url.py, test/plugins/test_plugins_rules.py, test/test_bot.py, test/test_loader.py, test/test_plugins.py, test/tools/test_tools_jobs.py
Tin. `coretasks` and all tests (except `test_module.py`, for obvious reasons) now use the members of `sopel.plugin` only.
One more step on the road to #1738. This isn't actually part of the task list there, but it still feels good.
Hopefully will not conflict with #2116, which already uses `plugin` for all its newly added decorator calls.
=> Replace (almost) all usage of `sopel.module` with `sopel.plugin`

sopel/plugins/__init__.py, sopel/plugins/handlers.py
Tin. Part of #1738.
Also reindented the touched docstring to follow our current conventions re: block roles (e.g. `.. seealso::`).
Removed unnecessary `list(ListAttribute)` typecast.
=> plugins: don't search in `~/.sopel/modules` by default any more

sopel/bot.py, test/test_bot.py
Plugins doing this will receive warnings through the entire remaining lifetime of 7.x (at least several months, perhaps up to a year-ish), and it's high time to push plugin devs away from using anything but the `plugin.url` and `plugin.url_lazy` decorators.
As pointed out in a comment below, also deprecates `bot.search_url_callbacks()` (which should have been deprecated along with its register/unregister siblings).
- Or rather, we have already tested that the functionality replacing it works as intended.
Sopel 9.0 will drop the `(un)register_url_callback` functions, finally ending the era of plugins manually managing their own URL callbacks. That will feel _almost_ as good as dumping Python 2. 😁
This could have been one commit, and I didn't test the intermediate state. Initially I was …
=> bot: remove `bot.memory['url_callbacks]` and use internal state

sopel/modules/wikipedia.py
If a channel's language setting is loaded from the deprecated `wikipedia.lang_per_channel` config value, Sopel will log a warning:
```
[2021-07-03 01:37:59,890] sopel.modules.wikipedia WARNING  - Language for #dgw loaded from the deprecated
config setting, wikipedia.lang_per_channel
```
Targeted to 7.1.x branch for v7.1.2. Should have been done in #1916.
- flake8 doesn't pass because I have the newer version we use on `master`, but should pass in 7.1.x CI
=> wikipedia: log a warning if `lang_per_channel` is used for a channel

sopel/formatting.py
Following up on an old TODO comment, now possible because we no longer support Python 2. Making this an Enum means it's safe against plugins accidentally (or intentionally) overwriting the color values.
This isn't the appropriate time to address such an issue, but the color name 'TEAL' doesn't exist in mIRC's documentation, nor is it listed at the "[horse docs](https://modern.ircdocs.horse/formatting.html#colors)" I also don't know why 'OLIVE' is an alias to 'ORANGE'.
No color names have been changed *yet*, but I did add comments to point out the issue during future improvements.
If a plugin is using the 7.x `formatting.colors` class as documented and intended, no problem. Any code pulling funny business like overriding color names for convenience _will_ have problems, but we're not going …
=> formatting: `colors` is now an Enum

sopel/tools/_events.py
Anyone using these as intended should see no ill effects, but using an `Enum` class will actively thwart plugins that try to do something silly like override a numeric name.
Really, it's the same thing as #2122 but for the numeric events instead.
=> tools.events: convert to `Enum`

sopel/modules/invite.py
Avoids "Unknown error" output to IRC and exception traceback log dump.
Before:
```irc
<grym> .invite hasn't been doing what i need >.> 
<Sopel> Unexpected error (Target channel name must not be a nick.) from grym at 2021-07-05
15:49:16.901922. Message was: .invite hasn't been doing what i need >.> 
```
After:
```irc
<dgw> .invite hasn't been doing what i need >.>
<SopelTest> dgw: Target channel name must not be a nick.
```
=> invite: handle expected possible exception

conftest.py
Tin. IIRC some of the behavior I'm removing was to work around issues that were only reproducible under Python 3.3 _on Travis CI_ (and not in my local 3.3 env), making them doubly irrelevant now that we switched to GitHub Actions _and_ only support py3.6+.
=> conftest: remove hacks/shims for running tests on Python 3.3

sopel/plugins/rules.py
We have dropped support for Python 2, and this eliminates yet another TODO comment left in the code.
=> plugins.rules.URLCallback: use `yield from` expression

docs/source/configuration.rst, sopel/config/core_section.py, sopel/db.py
Specifying a `core.db_url` setting overrides the other `core.db_*` settings and just uses the provided URL directly.
Resolves #2057, more or less, though the envvar name isn't exactly what was mentioned in that feature request.
- With my local `sqlite:` URL, retrieved from `bot.db` via `sopel-ipython`. Presumably if that works, it'll work with MySQL/PostgreSQL/whatever else.
It should now be trivial to simply copy the value of the `DATABASE_URL` environment variable on Heroku into the `SOPEL_CORE_DB_URL` variable expected by Sopel, instead of splitting it into components.
Adding support for the envvar name `DATABASE_URL`, if it happens, can be done separately.
=> config, db: support `db_url` setting to override the individual options

sopel/loader.py, test/test_loader.py
Way back, before the `plugin` (or `module`) decorators were a thing, "modules" of the time were written by directly assigning attributes of each callable to add the required properties for the bot's loader.
We don't support that any more. Code like that is probably five or more years old *at minimum*, and should be updated.
Also drops related tests, of course.
Did I think about raising some kind of warning instead of silently correcting the values as Sopel 7.x and earlier have been doing? Yes. I decided against it, because that would just replace one kind of legacy fallback mode with another. Rip off the band-aid.
=> loader: drop compatibility code for old-style Phenny/Jenni modules

sopel/modules/translate.py
Tin (fix #2152).
Also I added some logging, because why not.
=> translate: catch requests exceptions

sopel/modules/pronouns.py
Adds the ability to clear one's pronouns. 
Closes #2137
~~`make qa` reports a bunch of issues but unrelated to my change.~~ @dgw edit: It's because the checks were run on py2, which is no longer supported.
=> pronouns: add `.clearpronouns` command

sopel/bot.py
This reverts commit 3986227c4971e68530ae07113426187e95967046.
```
<+Exirel> 
Because Sopel still uses `search_url_callbacks`, and have to.
14:01:55 <RhinosF1> 
it does
14:02:21 <+Exirel> 
Yup. So yeah, we need to find a better solution than that.
14:04:19 <RhinosF1> 
I can hack beta if anything needs testing
14:07:20 <+Exirel> 
I think we should not trigger a warning on `search_url_callbacks` in 8.0, make it a no-op in 9.0, and remove it in 10.0.
```
Revert 3986227c4971e68530ae07113426187e95967046.
=> Revert "bot: deprecate `search_url_callbacks()` method"

sopel/tools/time.py, test/tools/test_tools_time.py
As a side note, the absolute fallback default time format has been changed here to use `%z` (UTC offset) instead of `%Z` (zone name), since the zone name is almost never useful and the offset is actually handy to have in tests. And in the output, too...
After faffing around _way_ too much with the tests, I'm not _entirely_ sure any more if their passing actually means anything. Sure, `tools.time.format_time()` seems to do what I expect in an interactive console, but… that's not a unit test.
I don't _think_ this warrants "Breaking Change" treatment since the only user-facing behavior change is the output when _no_ other time format source is passed to `format_time()` and it uses the tweaked default… but opinions may vary. Maybe aware `datetime` objects being legal now should be called out. …
=> tools.time: handle aware datetimes too in `format_time()`

sopel/irc/utils.py
=> irc: MyInfo namedtuple with proper type hint

sopel/cli/plugins.py
=> cli.plugins: keep plugin meta info on loading error

requirements.txt
requests 2.26 switched from chardet to charset-normalizer on py3, and that seems to be [broken on py3.3](https://app.travis-ci.com/github/sopel-irc/sopel/builds/234445467) specifically. It installs, but requests throws an error on loading anyway for some reason. Easiest solution is just to pin the requests version, since especially on py3.3 we don't care about any of the new stuff.
=> requirements: pin requests on py3.3 to fix install/build

sopel/modules/wikipedia.py
It took me literally ten minutes to write and test this, albeit not _that_ thoroughly. Should fix #2158, though the reason I opened that issue is I thought it would take more effort/time…
```
<Sopel 7.1.2> [wikipedia] Gurmukhi - Letters | "This article contains IPA phonetic symbols. Without proper
rendering support, you may see question marks, boxes, or other symbols instead of Unicode
characters. For an introductory guide on IPA symbols, see Help:IPA. The Gurmukhī alphabet contains
thirty-five base letters (akkhara, plural akkharā̃), traditionally arranged in seven rows of five
letters each. The first three letters, or mātarā vāhak ("vowel carrier"), […]"
<This PR> [wikipedia] Gurmukhi - Letters | "The Gurmukhī alphabet contains thirty-five base letters (akkhara,
plural akkharā̃), …
```
=> wikipedia: skip messagebox template contents

sopel/modules/translate.py
Should resolve #2021 by outputting a friendly error instead of what has become an "Unexpected error" involving concatenating `NoneType` to `str` thanks to the output-prefix consistency pass we did in 7.1.
The logic in this plugin could do with a refactor, especially making `translate()` raise an exception instead of returning garbage. But I'm not up for that tonight, and it wouldn't be appropriate to do that for a 7.1.x bugfix release anyway.
=> translate: handle failure/error better in `.mangle`

sopel/modules/tell.py, test/modules/test_modules_tell.py
Tin; bugfix to resolve #2157.
Also gets rid of the weird "lingering comma" behavior that that issue describes in passing, as a welcome side effect.
Using a custom/bespoke function to do this for now. As mentioned in #2157, we probably should think about adding formatting-safe string-stripping functions like this and what `choose` uses to Sopel's API. Core plugins surely aren't the only ones to run into such edge cases with leading/trailing formatting bytes.
=> tell: do not lstrip leading formatting

sopel/modules/reddit.py
Including the `$` end-of-string anchor means that the plugin won't get triggered for reddit post URLs that include `?sort=new` etc. First of all, they should be included. Second, and more importantly, comment links work regardless of query parameters.
=> reddit: don't anchor to end of post links

sopel/config/types.py
Turns out *a lot* of plugins use `ValidatedAttribute(..., parse=bool)`, and this is hardly a breaking change. It makes the most sense to tie this warning to a major version, rather than forcing plugin authors to require a minimum minor release of Sopel.
There's no technical reason to change this. It's a philosophical choice that came up for me when reviewing other plugins that make use of bools in their config sections. This warning just isn't useful immediately after deprecation; plugin authors can adopt the new type voluntarily, but Sopel doesn't need to force it in 7.x. Migrating to this new type can be part of the 8.0 migration guide, as a new major release of Sopel _would_ be a natural point to bump plugin requirements. (That goes double for anyone using our cookiecutter template, …
=> config.types: silence `parse==bool` warning until 8.0

sopel/modules/announce.py, test/modules/test_modules_announce.py
Fixes #2165.
Python 3 `dict.keys()` returns a `dict_keys` object, which is not subscriptable unlike the return value in py2.
Also made the generator return a consistent type (always tuple), and updated the documentation (not that it's actually used anywhere by Sphinx). Added a test, too, because let's (try to) not have this plugin bite us again.
- I ran both the new test and `make quality` on both py3(.8) and py2(.7), and the patch _should_ be clean against both. Since this can't be a straight cherry-pick back to `7.1.x` due to the new test file needing different headers, I have pre-prepped an `announce-py2-backport` branch for myself with the appropriate code style.
=> announce: make `_chunks()` helper safe against more input types

sopel/modules/wikipedia.py
Not going to say this will work in all cases, but it should handle MOST just fine. It's definitely better than the `KeyError` spat out before. Closes #2167.
=> wikipedia: handle transcluded sections better

sopel/bot.py, sopel/irc/__init__.py, test/test_irc.py
Tin. I was always a bit annoyed by the `say` method that does too much on its own, and I know that @half-duplex wanted a way to know the safe length for an IRC message without having to reinvent the wheel each time. I hope this will help, even if just a little.
Working on this part, I saw that `hostmask` is used but not defined by the abstract class, so I took this opportunity to use `abc.ABC` and the `abc.abstractmethod` decorator.
By doing so, I also replaced the `KeyError` when the hostmask is not defined to return `None` instead. This is a very minor breaking change. I'm not sure anyone is using `bot.hostmask`, and they probably don't use it when the bot is not connected/hasn't join a channel yet.
=> irc: add safe_text_length and use abc.ABC for AbstractBot

sopel/tools/__init__.py, test/test_tools.py
Tin. We aren't going to miss these rule-regex functions (already moved into the relevant `plugins.rules` types) and convenience stuff from the pre-py3 days.
=> tools: follow through on all `removed_in='8.0'` deprecations

sopel/modules/wikipedia.py
Tin. The "unexpected setting" warning we added in #1973 should alert bot owners if this is still kicking about in their files.
I also unrolled a couple if/else blocks into if-return because… I felt like it.
I should probably make a patch for 7.1.x that logs a warning if the language for a channel is loaded from this old setting.
=> wikipedia: remove deprecated `lang_per_channel` config setting

sopel/loader.py
Tin. It's `removed_in='8.0'`, and here we are.
- Perhaps unsurprisingly, no tests even used this function.
=> loader: remove deprecated `trim_docstring()` function

sopel/modules/reddit.py
It's entirely impractical to try to handle post and comment links in separate callables, because comment links contain an entire post link. Before, this was handled by anchoring the post URL pattern at the end, but that broke Sopel handling e.g. `?sort=confidence` if someone sorted the comments before copying the link into IRC.
Lookaround assertions didn't appear to prevent matching the post link contained in every comment link, so this solution seemed like the only way forward. It's a nice tidy dispatcher pattern, really.
Fix #2175.
=> reddit: handle post and comment links in one regex

sopel/coretasks.py, sopel/plugins/rules.py, test/plugins/test_plugins_rules.py
Filter out `PRIVMSG` and `NOTICE` commands that have the `bot` (or `draft/bot`) tag. Other events should be left alone until there's a decorator to opt back into them, or Sopel itself will no longer even be aware of bot users' existence on networks that implement one of these tags (which per [the spec](https://ircv3.net/specs/extensions/bot-mode) "SHOULD" be added to all commands sent, _and_ numerics caused, by a bot client).
A later pull request can introduce the needed decorator and changes to Rule constructors for certain callables to allow `bot` messages (à la `@plugin.echo`). Trying to keep stuff in manageable chunks so nobody gets burned out on reviews. 😸
Part of #2079.
- Once again, by the power of `pytest`!
I really want to skip over the part where we have to support _only_ …
=> coretasks: activate `message-tags` and use it to ignore other bots' tagged messages

sopel/bot.py, sopel/config/__init__.py, sopel/config/types.py, sopel/db.py, sopel/irc/abstract_backends.py, sopel/irc/isupport.py, sopel/irc/utils.py, sopel/logger.py, sopel/modules/admin.py, sopel/modules/currency.py, sopel/modules/remind.py, sopel/plugin.py, sopel/plugins/exceptions.py, sopel/plugins/handlers.py, sopel/plugins/jobs.py, sopel/plugins/rules.py, sopel/tests/factories.py, sopel/tests/mocks.py, sopel/tools/__init__.py, sopel/tools/jobs.py, sopel/tools/target.py, sopel/trigger.py, test/irc/test_irc_abstract_backends.py
In Python 2, there was 2 styles:
* `class ClassName:`
* `class ClassName(object)`
And they behaved differently, and using `super()` is different too. However, in Python3, both are equivalent to doing the second style, and we can use `super()` directly. I remember having to work with Py2.4 compatible code in my career, and this "new style class" stuff was... a pure nightmare. I'm just glad we can get rid of this.
Also, there is now `abc.ABC` that allows to describe an abstract class as being abstract. This is interesting because it doesn't require to add `raise NotImplementedError` anymore: a few decorators and it's all good!
One last thing: I added few type hint here and there, and I had fun with `TypeVar`. It's looking good!
Note: I think I want a "housekeeping" or "cleaning code" label …
=> sopel: use python3 style class and abc.ABC

sopel/irc/utils.py
Tin. We've reached the documented `removed_in` point for this obsolete prop.
Another thing that's not listed at #1738 but is still technically part of that initiative.
- Again, no test code references this, so I'm leaning on CI to run that against 4 Python versions faster than I can run it against even just one.
=> irc.utils: remove deprecated `CapReq.module` property

sopel/cli/utils.py
Tin. Another unused, deprecated function that wasn't covered by tests anyway, so it's really easy to tear out.
=> cli.utils: remove deprecated `redirect_outputs()` function

sopel/bot.py
Tin. But for completeness, a list:
* `msg()` was replaced by `say()` a LONG time ago
* the `register()`/`unregister()` methods are semi-internal plugin stuff, and were replaced by other methods in 7.1
=> bot: remove deprecated methods for 8.0

sopel/bot.py, sopel/module.py
Tick one more box off #1738 by adding a deprecation warning at import time.
=> module: import-time deprecation warning

docs/source/tests.rst
The `test_tools` submodule was removed in #2139, but the docs weren't updated. Yes, it was my fault.
- (Checked by rote: No code changes)
=> docs: remove `test_tools` from "Testing tools" page

sopel/coretasks.py
Originally [flagged as](https://lgtm.com/projects/g/sopel-irc/sopel/snapshot/ecf4f1db80a7be5af44438e152aa3dfcf0d39818/files/sopel/coretasks.py?sort=name&dir=ASC&mode=heatmap#L1064) an unused local variable by LGTM, but turned out to be a real bug.
Could be worth cutting a 7.1.5 release.
=> coretasks: correctly abort SASL PLAIN on invalid server reply

sopel/modules/reddit.py
reddit.py doesn't correctly handle redd.it shortlinks (anymore), and doesn't handle reddit.com shortlinks at all.
```irc
< xnaas> https://redd.it/qhoy7z
<+Sopel> Unexpected error (no such group) from xnaas at 2021-10-29 15:15:13.406136. Message was: https://redd.it/qhoy7z
```
This makes the "comment" group optional, and adds the "submission" group name and reddit.com domain to the shortlink regex.
=> reddit: fix shortlinks

sopel/plugin.py
Tin. I noticed a typo while working on something else (which isn't yet solved, but that's another story).
- If `make qa` didn't catch the typo, it's not going to complain about the correction. 😜
If we have another 7.1.x release, this is worth including, but I'm not starting a new milestone just for this.
=> plugin: add missing ' to command's docstring

sopel/__init__.py
The locale.getlocale() check currently looks for "UTF-8" only, however on windows with powershell and UTF8 enabled the return value is "utf8" so this check still fails.
Fixes #2173
=> Update to check for proper UTF8 on Windows

sopel/modules/wikipedia.py
```irc
< xnaas> TIL the Wikipedia plugin doesn't activate for mobile links
< xnaas> just standard url plugin output
< xnaas> rip in pieces
```
Previous:
```irc
< mal> https://en.m.wikipedia.org/wiki/1989_(Taylor_Swift_album)
< Sopel> [url] 1989 (Taylor Swift album) - Wikipedia | en.m.wikipedia.org
```
New (matches non-mobile behavior):
```irc
< mal> https://en.m.wikipedia.org/wiki/1989_(Taylor_Swift_album)
< Sopel> [wikipedia] 1989 (Taylor Swift album) | "1989 is the fifth studio album by American singer-songwriter Taylor Swift. It was released on October 27, 2014, by Big Machine Records. Following the release of her genre-spanning fourth studio album Red (2012), noted for pop hooks and electronic elements, the media questioned the validity of Swift's status as a country artist. Inspired …
```
=> wikipedia: handle mobile links

sopel/tools/web.py
Fixes #2203 on Python 3.4+ hosts. Anything older, well, we're not going to ship a reimplementation of Python's `html.unescape()` function (and everything else that actually makes it work) in a patch release when we've already dropped support for those Python versions on master. This bug just isn't a showstopper. It's not worth that.
- Well, locally `make quality` raises E741 on a variable name in `sopel/modules/help.py`, but that's nothing to do with this patch and it's not going to be an issue on the older version of flake8 configured for use on 7.1.x.
- Proof that the kind of link in #2203 works now:
```
<dgw> https://matrix.to/#/#element-community-testing:matrix.org
<SopelTest> [url] You're invited to talk on Matrix | matrix.to
```
=> web: use `html.unescape()` when available (Python 3.4+)

sopel/modules/clock.py
Adds functionality for user to unset their timezones if desired
=> clock: add unset functionality

docs/source/irc.rst, sopel/bot.py, sopel/coretasks.py, sopel/irc/modes.py, test/irc/test_irc_modes.py, test/test_coretasks.py
Following the work on #2098 I was able to refactor that part of the modestring parsing I had in mind since a long time ago. My main goal was to extract the parsing logic, and separate it from the application of new modes & privileges to users.
So now there is a `sopel.irc.modes` module that contains only modestring parsing (with the appropriate tests), and this module is then used in the `coretasks` plugin. There is close to 0 change in behavior, but there is at least two I can remember:
1. it now uses `deepcopy` to get the existing channel modes to prevent any mutability issues
2. before, when something went wrong (unknown mode type), `channel.modes = modes` wasn't done; this is now fixed
No tests on coretasks have been modified, although I used them locally to ensure that 1. it worked …
=> irc: rework parsing of modestrings

sopel/modules/reddit.py, test/modules/test_modules_reddit.py
Addresses a regression introduced by #2202 (itself a regression fix, ironically), which added `reddit.com` to the `short_post_url` pattern and made it possible for a post or comment URL to match BOTH that and `post_or_comment_url`.
Since URLs match individually, and not as part of the line, all we need to make sure a shortlink really is one is to ensure that the link ends after the submission ID and optional trailing slash.
- Better than the author of #2202 did, no doubt.
- This does not absolve me of failing to throw a battery of tests at the change myself. Past experience should have taught all of us by now that messing with `reddit.py`'s URL matching invites madness.
To the PR template's question: This does not resolve any GitHub issues, because @xnaas doesn't "submit GitHub issues …
=> reddit: fix matching twice for reddit.com without www.

sopel/irc/isupport.py, test/irc/test_irc_isupport.py
Fixes #2198 by no longer sorting PREFIX entries and returning an OrderedDict.
=> isupport: maintain PREFIX ordering

sopel/coretasks.py
Inspired by a recent PR to the "horse docs" site (ircdocs/modern-irc#146), which adds a paragraph about this.
The result of "test[ing] the functionality of the things this change touches".
<details>
<summary>stdout/logging</summary>
```
...
[2021-11-27 20:43:25,272] sopel.coretasks      INFO     - End of client capability negotiation requests.
[2021-11-27 20:43:25,307] sopel.coretasks      CRITICAL - RPL_WELCOME indicated the server did not accept the bot's
configured nickname. Requested
'ThisIsAVeryLongNickThatRizonWillTruncateBecauseItsLongerThan30Characters';
got 'ThisIsAVeryLongNickThatRizonWi'. This can cause unexpected
behavior. Please modify the configuration and restart the bot.
[2021-11-27 20:43:25,310] sopel.coretasks      INFO     - Joining 1 channels (with JOIN throttle OFF); …
```
=> coretasks: alert owner if nick in `RPL_WELCOME` does not match config

sopel/plugins/__init__.py
We can use `collections.OrderedDict.move_to_end()` now.
Yes, I know CI is going to fail pending resolution of #2210. Hoping the revert will happen soon and Python 3.9.x will get the "expedited release" that a maintainer requested at the Python bug tracker.
=> plugins: execute TODO that was waiting for end of py2 support

sopel/modules/reddit.py
Displays the link flair, if present, after the submission title.
I found this stale branch because it interfered with tab-completion for #2208. Rebase incoming; just wanted to open the PR first so the original history will be preserved.
~~Not checking the test/QA boxes yet, since I last touched this code nearly a year ago. CI will take care of checking that QA passes (once I rebase), and testing the behavior will have to happen after all that settles.~~ CI passed; live test worked as expected.
```
<Sopel> [reddit] How many of you are big travelers but still go with a cash back set up? (self.CreditCards) | 20 points
(84.0%) | 8 comments | Posted by OpossomMyPossom | Created at Sunday, December 05, 2021 20:44:43 -0600
<SopelTest> [reddit] How many of you are big travelers but still go with …
```
=> reddit: add flair text to link/submission output

sopel/modules/adminchannel.py
`configureHostMask` has had an unmatchable caret in one of its regular expressions since 2014. The fix for master/8.0 will be more like a minor refactor; this is just a patch to fix the obvious bug for stable.
Merging to `backports-7.1.7`, which is where I've been staging all of the backported patches that were originally merged to `master`. Doing it this way (instead of sending this to `7.1.x`) lets me avoid an annoying rebase later.
=> adminchannel: fix unmatchable caret in regex

sopel/modules/adminchannel.py, test/modules/test_modules_adminchannel.py
The "Big boy" version of #2221.
This is perhaps the most roundabout way to resolve a single LGTM alert in Sopel's history, but it improves a lot of stuff about the `adminchannel` plugin's `configureHostMask` helper function:
- Fix a broken regex (unmatchable caret, the thing LGTM complained about)
- Reduce the number of distinct cases
- Add comments explaining what each case is supposed to do
- Use exceptions to alert the caller about invalid input instead of a weak sentinel value of `''` (empty string)
- Add test cases to make sure that everything behaves as expected
Notably, adding tests also picked out a couple of edge cases that weren't handled, which I then also fixed.
The "Big boy" version of #2221.
- Well yes, that's what the new file under `test/` is for.
=> adminchannel: fix, simplify, and comment hostmask utility function

sopel/modules/wiktionary.py
Multi-paragraph etymologies no longer get truncated to only the _last_ line.
If the concatenated etymology is too long to fit in an IRC line, it's safely truncated by the existing logic to handle overly long output.
This patch definitely makes me want to give wiktionary the same kind of makeover that wikipedia got a while back. Which is to say: a proper parser-based implementation instead of...whatever you call this.
=> wiktionary: allow for multi-line etymologies

sopel/bot.py
Create `bot.plugins` as suggested by @Exirel on IRC. Uses a property and a MappingProxyType to make bot.plugins and bot.plugins[*] immutable. Needed for cleanliness in #2133
=> bot: add plugins property

docs/source/api.rst, sopel/tools/__init__.py, sopel/tools/web.py
This fixes #2203 for 8.0. (The patch for 7.1.6 is a separate PR against the maintenance branch, #2204.)
Python 3.4 added the `html.unescape()` function to its standard library, and current versions of Python have MUCH better HTML-entity-replacement implementations than ours. Let's just use the included batteries.
This patch deprecates `tools.web.entity()` and the associated constant `r_entity`. `tools.web.decode()` no longer uses them, and in fact should probably be considered for deprecation itself. (Not done yet; deciding that will come separately, along with its siblings' TODO comments.)
Note that the import of `web` in `tools/__init__.py` had to be moved below the definition of `tools.deprecated()` to avoid causing a circular dependency error. Might as well do it now, since we'll …
=> tools, tools.web: rework `web.decode()` to use modern stdlib

sopel/cli/run.py, test/cli/test_cli_run.py
Fix  #1584 by removing the legacy parser completely, fixing the doc and the help message. Options are no longer available without a subcommands, which is a breaking change. However, it makes everything else better (the doc, the usage, the code etc.) and it's Sopel 8 and it's the right way to do a command line tool.
=> cli: remove legacy mode for run script

sopel/modules/version.py, sopel/plugins/handlers.py
Exposes `plugin._module.__version__` (or `None`) in plugin metadata, and adds `.version plugin_name`.
```irc
<!mal> .version
< Sopel> [version] Sopel v8.0.0.dev0 | Python: 3.9.5 | Commit: blahblah
<!mal> .version coretasks
< Sopel> [version] coretasks v8.0.0.dev0 (built in)
<!mal> .version mypackage
< Sopel> [version] mypackage v9.9.9
<!mal> .version test
< Sopel> [version] test (version unknown)
<!mal> .version fake
< Sopel> [version] I don't have a plugin named 'fake' loaded.
```
This will confuse any daring person with a sopel module named sopel, but that's a risk I'm willing to take.
It does work for individual .py files that contain a `__version__`.
=> Expose plugin versions, enable retrieval with `.version`

docs/source/plugin/bot.rst
This is a first attempt at a documentation about time management for Plugin author. I think way more could be written, yet it will do for now. I don't want to have something blocked in a perpetual draft state because "it could be better". Of course it can be better, and it'll be. In future PRs.
=> docs: about time for plugins

Makefile, dev-requirements.txt, requirements.txt, setup.cfg, sopel/bot.py, sopel/modules/bugzilla.py, sopel/modules/currency.py, sopel/modules/meetbot.py, sopel/modules/reddit.py, sopel/modules/remind.py, sopel/modules/search.py, sopel/modules/url.py, sopel/plugin.py, sopel/plugins/__init__.py
I wanted to add type annotation, and make sure they actually work, i.e. that mypy could validate them. So I installed it, ran it, and... got a load of errors. So tried to fix them, one by one.
Some are easy to fix: for sqlalchemy or pytest, all I had to do was to upgrade the dependency. Given that we are now Py3.6+ only, it was fairly easy and shouldn't be a problem. At least I hope it won't. At least, the test suite is still running fine on my end (Py3.8), and I'm doing this PR to check how it behave on the CI too. If it doesn't work, I'll see what I can do!
Some are trivial to fix: install a type library:
* types-pkg-resources
* types-pytz
* types-requests
Some errors are more complicated, and some are limitation of what is available in Py3.6 (compared to what you can do with 3.8 and …
=> sopel: type hint and basic setup

sopel/db.py, test/test_db.py
Tin, really. Up to now it's been possible to delete a _user_ (nick group) from the database, but not possible to forget about a channel or plugin without manually writing SQL for `db.execute()`. Seemed like deletion of value groupings should be as parallel as possible, just like management of individual values is between the three types.
I see these as most useful for cleaning up channels that the bot is leaving permanently, or for plugin authors to add graceful "uninstall preparation" features to clean up whatever detritus the plugin has left in the database.
There's a deprecation & rename in here too, moving `delete_nick_group()` to `forget_nick_group()`, but I kept it in a separate commit so it's easy to drop if that seems like a bad idea to the rest of y'all.
I'm continuing to try and …
=> db: add `forget_channel()` and `forget_plugin()` methods

sopel/modules/wikipedia.py
Sometimes note templates include inline style tags. Since their contents appear just like any other data to the parser, it will output the CSS unless told to ignore them.
I'm not going to start a 7.1.8 milestone just for this, because it's quite the edge case. But if some other more important bug crops up that _is_ worth starting a milestone for, this should be included.
=> wikipedia: refine no-consume logic for section hatnotes

docs/source/plugin/internals.rst, sopel/plugins/rules.py
One PR, two issues:
* LGTM issues that are better fixed than ignored
* ~Type hint warning for documentation~
* Update documentation to replace the mixin by the abstract named rule class
* Fix a deprecated usage of an abstract method decorator in Rule
=> plugins.rules: fix conflicting attributes in base classes

docs/source/api.rst, sopel/tools/__init__.py
These four functions were for backward compatibility, as they all stand in for features removed in Python 3. Sopel no longer supports Python 2, and it's long past time for plugin authors to use the correct Python 3 functions instead of these.
Honestly, no one should be using these any more in almost-2022. Think of the deprecation warning(s) as a wake-up call to modernize your code!
Excluded the now-deprecated module members from coverage reporting, in an attempt to keep our coverage percentage focused only on code we intend to keep. Also excluded these members from the docs. Compare [deploy preview](https://deploy-preview-2228--sopel-unstable-docs.netlify.app/api.html#sopel.tools.get_sendable_message) to [current unstable](https://unstable.docs.sopel.chat/api.html#sopel.tools.iteritems).
=> tools: deprecate more Python 2-like shims

requirements.txt, sopel/modules/isup.py, test/modules/test_modules_isup.py
Annoying little update from requests 2.27 that has a different behavior and doesn't work exactly the same way with requests_mock.
This fix works for both 7.1.x and 8.x.
=> isup: catch up errors from get site and from requests differently

sopel/tools/target.py
Tin, really. Python has [this feature](https://docs.python.org/3.9/reference/datamodel.html?highlight=__slots__#slots) where you can tell it to store instance attributes in a "slot", and using it can make small objects more time- and space-efficient by eliminating the need to look up attributes in the instance's `__dict__`.
This can save some significant memory when Sopel is in many and/or large channels. For example, without this patch (in bytes):
- Size of empty channel: 1200
- Size of channel with 100 users: 84560
- Size of channel with 1000 users: 817944
And with this patch (also in bytes):
- Size of empty channel: 680
- Size of channel with 100 users: 72608
- Size of channel with 1000 users: 705304
An empty channel is reduced by nearly half, and channels with some significant user …
=> tools.target: use slots for Channel and User types

sopel/db.py, test/test_db.py
Having `get_nick_id()` default to `create=True` may cause unexpected behavior if invalid nicknames are passed to it via plugins' use of the getter and setter methods.
We are taking this opportunity to fix the API design itself, with no period of deprecation and warnings, since this particular method is mostly used only by the database object itself, and isn't really intended for direct use by plugins.
I've also added some more assertions and error-case checking to some of the related tests for `sopel.db`. The tests required minimal changes to continue passing; only cases where some manual setup was using `get_nick_id()` as a shortcut to make sure the nick would exist in the database before running the test case needed to be changed.
A code search on GitHub for `get_nick_id` returned very …
=> db, test: do not create nick ID by default

docs/source/api.rst, docs/source/plugin/bot.rst, sopel/bot.py, sopel/config/core_section.py, sopel/coretasks.py, sopel/db.py, sopel/irc/__init__.py, sopel/modules/adminchannel.py, sopel/modules/clock.py, sopel/modules/find.py, sopel/modules/invite.py, sopel/modules/meetbot.py, sopel/modules/seen.py, sopel/modules/tell.py, sopel/modules/translate.py, sopel/modules/url.py, sopel/tests/factories.py, sopel/tools/__init__.py, sopel/tools/identifiers.py, sopel/tools/target.py, sopel/tools/time.py, sopel/trigger.py, test/test_coretasks.py, test/test_db.py, test/tools/test_tools_identifiers.py
This PR contains various changes with the end goal to use the server's casemapping instead of the hardcoded one. Sadly, this includes breaking changes.
* The bot has a new method `make_identifier`: it uses the `CASEMAPPING` parameter from isupport to select the appropriate casemapping function (from `sopel.tools.identifiers`)
* The `Identifier` class has several changes:
* `Identifier` now lives its best life in `sopel.tools.identifiers`, mostly to prevent cyclic import errors. This comes with some more documentation.
* `Identifier` doesn't override `str.__new__` anymore, I figured out a way to use `__init__` instead, and it works fine.
* `Identifier` has a new argument: `casemapping`. It's a callable that **must** take one parameter (a string) and return a string.
* The default value of …
=> irc: implement CASEMAPPING parameter for ISUPPORT

docs/source/plugin/internals.rst, sopel/plugins/handlers.py
Tin: I fixed two warning/error:
* Sphinx autodoc seems unable to properly manage `typing.TypeVar`, so I created a class declaration for the one used in `plugins.rules`,
* A new method wasn't returning explicitly, and `mypy` doesn't like that so I fixed that as well, given it's in `plugins.handlers`
Two quick fixes.
=> rules: fix sphinx auto-doc warning and mypy error

docs/source/conf.py, sopel/db.py
We've updated to SQLAlchemy 1.4.x on the development branch, and we should use the correct intersphinx base URL for that release series. SQLAlchemy has renamed its `ResultProxy` type to just `Result`, and along the way I also spotted a bare PEP number that could be a ref.
Surprisingly, that was the _only_ occurrence of `PEP` (case-sensitive) in the whole project.
=> db, docs: update intersphinx & fix some references

sopel/coretasks.py, sopel/irc/__init__.py, sopel/tools/identifiers.py, test/test_coretasks.py, test/tools/test_tools_identifiers.py
Tin.
This is based on #2231 which made it very easy to do: all commits are squashed into one that must be removed once that PR is merged.
=> irc: implement CHANTYPES parameter for ISUPPORT

sopel/coretasks.py, sopel/modules/adminchannel.py
Tin, kind of.
There's a bit more esoteric detail in the commit messages if anyone's interested, but the short version is that we really should be moving toward a world where `bot.nick` always represents the bot's _current_ nick in use—even if that doesn't match the config.
While we aren't there yet, this is a step (or two) forward on that path. I've made it so that `coretasks`' `NICK` event handler updates the bot's nick if it changes, and only warns for a change _away_ from the config value.
On the way to writing this patch, I discovered that `bot.change_current_nick()` would send a `NICK` command to the server along with updating the `bot._nick` value. That's probably a bad idea, actually, and I didn't use it (also because it's redundant to send `NICK thenickwealreadyhave`). We should …
=> adminchannel, coretasks: improve handling of bot's current nick

docs/source/plugin/anatomy.rst, sopel/loader.py, sopel/plugin.py, sopel/plugins/rules.py, test/plugins/test_plugins_rules.py, test/test_plugin.py
You know, it's fun when you find an unmerged branch hanging around during a local cleanup.
It needs rebasing, which I'll handle in a moment, but it will fill a gap in the plugin decorator library. After #2089 we're missing a way for plugin authors to opt back into getting messages from other bots. Most will probably appreciate the filtering Sopel now does on their behalf, but I'm sure there are a few who [relied on the old behavior](https://xkcd.com/1172/)…
- ~~I will make sure of this after rebasing.~~ It was true! And I even remembered to upgrade the dev-reqs before running tests.
=> loader, plugin, plugins.rules: add `allow_bots` decorator

sopel/modules/translate.py
This is a semi-temporary fix for #2241. It's still not perfect (still allows using unsupported or nonexistent language codes), but there will be additional options available in Sopel 8.0 and beyond. Goal for this is to avoid adding any new dependencies in 7.1.x.
=> translate: update `langcode()` helper to support Chinese

sopel/modules/reddit.py
The reddit plugin currently does not handle preview links like this, which users sometimes mistakenly post ("Copy image link" instead of "Copy link").
https://preview.redd.it/rgcetuc1rmf81.jpg?width=576&auto=webp&s=61de9945ce109cefe95cda589c18d434b2d23553
It falls through to url.py, which fails to find a title.
This changes the reddit.py image link handling to also catch preview links, and show both the comment and full-res links in that case.
pytest is currently exploding on master and I don't know why so uh. CI is doing my QA for me
=> reddit: handle image preview links

sopel/modules/xkcd.py
Yeah, `.xkcd` search hasn't been working very well because Bing decided to start returning `m.xkcd.com` URLs much of the time.
Interestingly, adding `-site:m.xkcd.com` made Bing return NO results, not the normal (non-mobile) link. That's why this patch modifies the regex to validate the result instead.
I'm not sure what's up with the optional protocol prefix, but didn't want to touch it in a patch intended for stable branch.
```
11:20:16 <dgw> .xkcd team chat
11:20:16 <Sopel> dgw: Could not find any comics for that query.
11:27:01 <~dgw> ,xkcd team chat
11:27:03 <SopelTest> [xkcd] Team Chat | Alt-text: 2078: He announces that he's finally making the jump from
screen+irssi to tmux+weechat. | https://xkcd.com/1782
```
Back in November I tried to fix this on the `search` plugin side with a …
=> xkcd: account for Bing search returning mobile URLs

sopel/modules/url.py
The sky is not falling if this plugin can't connect to a found URL, nor is it The End Of The World As We Know It if a title isn't found.
These are debug/info events, not errors/warnings.
This is not marked as a resolution of #2207 because it doesn't technically address the core problem reported there. If sent to IRC as described, the "Traceback" can still become "part of [the] url". I will touch `IrcLoggingHandler` in a separate PR to address that.
=> url: bring additional sanity and calm to log output

sopel/logger.py
Tin. Stupid-simple "fix" for #2207.
/cc @RhinosF1
I discovered while trying to test this on top of #2249 that setting `logging_channel_level = DEBUG` causes some serious problems. That probably warrants its own issue, but since @Exirel will probably be the one to review this I wanted to see if he has any advice first before I go digging around in things to write up a real report.
=> logger: convert newlines to spaces in IRC logging handler

sopel/irc/__init__.py
I noticed a couple of typos, but decided to give the whole file a good once-over to make a pull request worthwhile.
- Doesn't touch code.
- Ditto.
The intent is to backport all relevant fixes to `7.1.x`, hence the milestone. I'm not sure if 100% of the patch will apply since some things have changed on `master` since the split, so there's a chance that the best approach will be a separate PR for the stable branch (in which case I'll reassign this one).
=> irc: fix some typos & formatting in docstrings

sopel/modules/search.py
This applies the warning from #1418 (intended to help users avoid weird behavior as described in #1415) to _all_ search queries that contain multiple `site:` operators and return no result, regardless of which search engine is used.
For the combo `.search` command that uses both Bing and DDG, the warning triggers only if both engines return nothing.
I will finally declare #1415 closed after this patch, as we've done all we can do about it from the client end.
=> search: consistently warn about excessive "site:" operators if no results

sopel/modules/url.py
Update the user-agent string to Chrome 96, the 2nd most popular UA listed on
https://techblog.willshouse.com/2012/01/03/most-common-user-agents/
=> url: bump user-agent

docs/source/lifecycle.rst, docs/source/package.rst, sopel/bot.py, sopel/config/types.py, sopel/db.py, sopel/lifecycle.py, sopel/logger.py, sopel/module.py, sopel/tools/__init__.py, sopel/tools/web.py
The `deprecated()` function is used everywhere, whenever we need to deprecate something. Sometimes, that somethings is right where this function is defined: in `sopel.tools`, causing cyclic import errors.
In an effort to reduce cyclic import errors, and to organize the code a bit better (mostly by removing everything from `sopel/tools/__init__.py`), this function is moved to its own sopel's submodule: `sopel.lifecycle`.
Documentation has been updated accordingly, and every part of Sopel that used `sopel.tools.deprecated` is now using `sopel.lifecycle.deprecated`.
In order to prevent yet another cyclic import error, `deprecated` no longer uses `sopel.tools.get_logger` to get the logger for an external plugins (that isn't using the namespace), but tries to mimic its behavior for namespace …
=> sopel: move deprecated() to sopel.lifecycle

sopel/config/types.py
Tin, according to the step for 8.x of #1626.
=> config: deprecate using a comma instead of a newline in ListAttribute

docs/source/plugin.rst, requirements.txt, sopel/__init__.py, sopel/lifecycle.py, sopel/plugins/__init__.py, sopel/plugins/handlers.py, test/plugins/test_plugins_handlers.py, test/test_plugins.py
Tin. Performance of `pkg_resources` can be quite slow (just search all of GitHub issues for "pkg_resources slow"); [its use is discouraged](https://setuptools.pypa.io/en/latest/pkg_resources.html) by the `setuptools` project itself, in favor of the newer modules such as `importlib.metadata`.
Needs a backport package until we no longer support Python 3.9. stdlib gained `importlib.metadata` in Python 3.8, but the ability to "select" in `entry_points()` won't be added until Python 3.10. I don't mind this, because it takes an implied dependency (`setuptools` was required to install Sopel but not listed in `requirements.txt`) and makes it explicit until we can use the stdlib version. My requirement specifier gives the minimum version of the `importlib_metadata` backport that supports …
=> core: replace `pkg_resources` with `importlib.metadata`

test/test_loader.py
Tin. We weren't checking the presence/absence of `echo` or `allow_bots` attrs or verifying that the correct default values are set for them. Also noticed a `clean_callable` test with no idempotency check.
- They're literally tests. 😏
=> test: add some missing attributes to loader tests

sopel/modules/find.py
I once noticed that the order of operations in `collectlines()` didn't really make sense, and I'm finally doing something about it.
No, I probably won't bother backporting this to 7.1.x.
=> find: shameless micro-optimizations

sopel/modules/tell.py
This fixes a regression introduced in v7.1.3 by #2162, backported to the 7.1.x branch as 0dec496727ff57c569de17a3f6ffe611abec118e. (Yep, this one's a _mea culpa_.)
Previously, the code was sort-of safe due to a strange use of `trigger.group(2).lstrip([…])`. The new code, using `trigger.group(2).split()` instead, did not ensure that it actually gets enough values out of the split. I chose instead to make sure enough "words" exist in the command before performing the split.
Thanks to monaco (@hedho) for reporting this via logs on our IRC channel.
=> tell: catch missing message before it causes an exception

sopel/modules/search.py
Aside from removing the shadowing of `bytes`, the only notable change is that `bing_search()` now also decodes the URL just like `duck_search()` has been for ages. I felt like making that consistent.
Everything else is just whitespace.
=> search: fix/tweak miscellaneous code style issues

sopel/modules/search.py
Prerequisite: sopel-irc/sopel.chat#37
Tin. I don't mind one bit bundling this with the next bugfix release. We're just changing the link so it's guaranteed to keep working even if GitHub kills off git.io entirely without warning (kind of like they announced it would stop accepting new links without warning, so I don't think this is paranoid).
=> search: replace git.io link with shortcut defined on sopel.chat

sopel/modules/seen.py
Fixes a bug on `master` reported on IRC by monaco (@hedho), related to `trigger.time` changes from #2099.
I chose to eliminate the bug by using Unix timestamps instead of `datetime` objects. `<datetime_obj>.timestamp()` [has been around since Python 3.3](https://docs.python.org/3.9/library/datetime.html#datetime.datetime.timestamp), so we're safe to use it with 8.x's minimum requirement of Python 3.7.
=> seen: modify/fix stored value & delta calculation for Aware `trigger.time`

sopel/tools/_events.py
Tin. This will have to be mentioned in the migration guide.
Goes along with ircdocs/modern-irc#177, which explains the change.
See also ircdocs/modern-irc#42 for more history/discussion.
I'm just curious to see what Coveralls does now after it marked the most recent merge commit as failed because it somehow thought coverage had decreased to 0%. Hopefully whatever caused that has been fixed, otherwise my next patch will probably be ripping Coveralls out of our CI jobs…
=> events: rename and extend invite-related numerics

sopel/modules/pronouns.py
We don't have to wait until the 12th of Never for pronoun.is to have an API. Parsing tab-separated values is easy, and the file is already sorted according to approximate frequency for us according to their readme.
Includes a kill-switch config setting in case the repo ever gets deleted or reorganized, or the file format changes.
Speaking of something that's over-complicated for what it does (as Exi said on IRC yesterday)… this also finds the shortest unique set of pronouns for each option to use in links. The only outlier cases now are `they/them/their/theirs/themsel(ves|f)`, which won't be abbreviated as `they/.../themsel(ves|f)`. I might or might not find the motivation to fix that.
=> pronouns: fetch list from the pronoun.is GitHub repo at start

sopel/plugins/rules.py, test/plugins/test_plugins_rules.py
Bot Mode spec has been ratified (ircv3/ircv3-specifications#495). Since we haven't published a release with support for this message tag yet, it's a very easy decision to take *right now* that we'll only support the finalized spec and not the WIP version.
=> rules: drop `draft/bot` tag

sopel/bot.py, sopel/cli/run.py, sopel/irc/__init__.py, sopel/irc/abstract_backends.py, sopel/irc/backends.py, sopel/irc/utils.py, sopel/logger.py, sopel/tests/mocks.py
**TL;DR**: Tin. Close #1414.
Wouhou! This is it, that's the big PR for Sopel 8 that replaces the backend made with the now deprecated `asynchat` (and `asyncore`) module by a backend made with `asyncio`—and it wasn't easy. It might be complicated to review this, even more with all the added stuffs that feel unnecessary (like a heavy dose of type annotation).
I've tested it myself on two networks: Libera (with SSL on), and a private network (without SSL), and it all worked fine, ping timeout was handled properly, server timeout as well, ctrl+c is working fine as far as I can tell, even tho the sequence is a bit complicated if you try to interrupt the bot at the startup sequence (servers tend to wait quite some time before replying to a `QUIT` command and closing the connection).
So what's …
=> bot, irc: IRC backend using asyncio

dev-requirements.txt, docs/source/conf.py, sopel/irc/abstract_backends.py, sopel/tools/identifiers.py
Basically, tin. Was reminded this week of the `sphinx-rfcsection` plugin I started working on a few months ago, and decided to follow through with its intended first use case.
- It's going to get tested again by the preview docs Netlify generates for our PRs, e.g. [here](https://deploy-preview-2275--sopel-unstable-docs.netlify.app/api.html#module-sopel.tools.identifiers).
=> docs: use `sphinx-rfcsection` plugin (and fix some typos)

sopel/modules/url.py
If url.py can't connect to a server because of things like certificate issues (https://expired.badssl.com/), DNS (http://fake.host.local/), etc, it currently dumps most of a page of exception tracebacks into logs. This is useful to nobody, and it shouldn't do that.
This patch replaces the page of tracebacks with the following:
`sopel.modules.url    DEBUG    - Unable to reach URL: 'http://fake.host/': HTTPConnectionPool(host='fake.host', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f95ef238340>: Failed to establish a new connection: [Errno -2] Name or service not known'))`
I think that's quite sufficient for troubleshooting without being excessively spammy.
=> url: remove traceback from debug log when fetching URL fails

sopel/config/core_section.py
It was agreed in #2256 that we should probably not be hunting for CA paths ourselves. This removes that, and allows `ssl` to use its default (openssl's default). This _should_ be an invisible change.
To rebase this on top of or beneath #2256: discard this PR's backends.py changes (`wrap_socket()` had no sane default for ca_certs)
Contemporary caveats apply.
=> config: don't manually hunt for CA paths

sopel/modules/wikipedia.py
This PR coalesces repeated whitespace in MediaWiki excerpts (#2259)
- **NOTE:** I do see 9 test failures, 72 errors, but this is the same result against the current `HEAD` (984e1b9)
=> Add workaround for excessive whitespace in MediaWiki excerpts (fixes #2259)

sopel/loader.py, sopel/plugin.py, sopel/plugins/rules.py, sopel/trigger.py, test/plugins/test_plugins_rules.py, test/test_loader.py, test/test_module.py, test/test_plugin.py, test/test_trigger.py
Sopel 8's steps of #1683:
* replace `trigger.tags['intent']` by `trigger.ctcp` (same for `PreTrigger`)
* replace `plugin_callable.intents` by `plugin_callable.ctcp`
* replace `AbstractRule.match_intent` by `AbstractRule.match_ctcp`
* update tests and documentation accordingly
* add various type hint
=> loader, rules: use (pre)trigger.ctcp instead of tags

sopel/modules/url.py
- .title for e.g. reddit would say "Sorry, couldn't title that" followed by the reddit.py callback output
- last_seen_url (therefore `.title` sans args) was missing callback'd/excluded URLs
- tighten some security dumbs (except the safety part in #2279)
- no point in checking ip without DNS lookups if an attacker has $5 and a namecheap account
- add type hints
- some other tidying.
Related for some remaining issues: #2281
Fixes #2054
Fixes #2055
=> url: fix .title vs url callback plugins

sopel/modules/emoticons.py
Fixes the table becoming narrower after unflipping, and that the legs were thinner.
Also adds `.tback` as an alias for `.unflip`, because I'm used to it from somewhere and it's not a conflict with anything else.
=> emoticons: table consistency & `.unflip` command alias

sopel/config/core_section.py, sopel/irc/__init__.py, sopel/irc/backends.py
This resolves a TODO comment and two LGTM ignores regarding failing to specify a minimum SSL/TLS version for connections. It also introduces a new core config option, `tls_ciphers`, since python 3.10 tightens the defaults.
=> backends: allow setting TLS version and ciphers

sopel/plugins/rules.py, test/plugins/test_plugins_rules.py, test/test_bot.py
Fix #2295 by switching from a scalar object (tuple of datetime and return value) to the `RuleMetrics` object, which can tell if the rule is limited or not based on the internal state.
I had to deactivate the "admin" thing locally to test it live, and it works!
=> rules: properly track rate limits of rules

setup.py, sopel/cli/run.py
This PR corrects the warning message emitted by Sopel when running on Python prior to 3.8 to give the correct EOL for CPython 3.7
=> Remove Python EOL warnings

pytest.ini, setup.cfg
pytest can be configured in setup.cfg instead of its own pytest.ini to further reduce the number of files hanging around in the project root.
I'd have done this in the checkstyle.sh PR, but I didn't notice it =\
=> pytest: configure in setup.cfg

sopel/modules/safety.py, sopel/modules/url.py
This fixes (or works towards fixing) a bunch of issues with safety.py:
- `.safety` doesn't say what the current state is
- Uses VirusTotal API v2 (though they have no current plans to deprecate it) instead of v3
- Doesn't find URLs in messages containing anything else ("`foo http://example.com`" fails)
- Doesn't make local cache accessible to other plugins
- Doesn't use already-cached VT results in local mode
- Doesn't allow configuration of local or strict defaults
- url.py was not checking the domain blacklist and was also failing to handle "`foo http://example.com`"
- Other tweaks and improvements
=> safety: rework

sopel/cli/run.py
I missed this in #2278 :neutral_face:
Since `ca_certs=None` is now valid, the warning is nonsense. If the setting is truly invalid, Sopel will quit with an exception:
```
ValueError: Invalid value for core.ca_certs: Value must be an existing or creatable file.
```
or
```
ssl.SSLError: [X509: NO_CERTIFICATE_OR_CRL_FOUND] no certificate or crl found (_ssl.c:4123)
```
(Though after the latter, it'll still attempt to reconnect after shutting down??)
=> cli: remove ssl cert warning

sopel/modules/url.py
Making mypy happy with `url.py`.
=> url: fix various type error

.coveragerc, sopel/irc/backends.py, sopel/plugins/rules.py, sopel/tools/memories.py, test/test_bot.py, test/tools/test_tools_memories.py
This started with our instance of Sopel running from source with the bot becoming unresponsive after a user quit the server: there was a bug in how `SopelIdentifierMemory` deals with `None in memory`. This caused an unexpected exception at the wrong place, which put the bot in a weird unstable state from which it doesn't recover.
I also fixed the case where an SSL connection error would block the bot in an infinite restart loop.
I'm still not sure the message handling is safe, but at least *this particular cause* is fixed.
=> irc, memories: fix handling QUITs, and prevent infinite failed-connection retries

sopel/coretasks.py
Log output containing `Identifier(nickname)` isn't super useful. It just wastes bytes in the log file.
Oh yeah, it also looks weird.
The instance I noticed appears to have come from 5e5bce244467c673aa90e999a0904444873d35de, released in Sopel 7.1.0, which I guess tells ya how much I usually look at INFO messages. Only even noticed today because I was skimming through stdout to check for any more glitches after merging #2306.
=> coretasks: always log nicks as strings

sopel/tools/__init__.py, test/test_tools.py
Fixes a bug reported on IRC by deadyeti, where text containing both emoji and spaces (tweets, in their case) was not split correctly in `tools.get_sendable_message()`, resulting in the second message containing only one word.
I also added test cases (some as regression insurance) and tweaked the function documentation as long as I was touching it.
h/t to @half-duplex for jumping straight into the code and finding the root cause while I was still working on a test case to reproduce the bug. 😅
Is this important enough to prompt a maintenance release? We haven't been planning to cut any more package versions off the 7.1.x series, in favor of focusing everyone's time and attention on finishing 8.0.
@sopel-irc/rockstars please weigh in if you have Thoughts.
=> tools: fix `get_sendable_message()` with both multibyte chars & whitespace

sopel/modules/url.py
The `query()` method has been deprecated, and was generating warnings in our CI logs. Fingers crossed that the `dnspython` maintainers will keep the old method around until their next major version, which Sopel (even on the stable branch) excludes in its requirements. (This is my excuse for not bothering to backport the change to 7.1.x.)
=> url: replace deprecated `dnspython` method

sopel/db.py, test/test_db.py
SQLAlchemy 1.4 (used by Sopel) defines a cross-compatible new style to query the database using its ORM, its engine, and its connection:
* Engine cannot execute SQL directly
* Connection can be used as context manager
* Session can be used as context manager
* Instead of doing *.query, use *.execute(stmt)
* SQL statements are easier to create with select, update, and delete function from `sqlalchemy.sql`
* And many other things
One of the key change here is the usage of session object as context manager instead of using try/except block: less code, same feature!
We can't set `future=True` on the Engine yet, because we need the non-compatible and now deprecated behavior of direct SQL execution from the Engine object: `SopelDB.execute` has been deprecated and should be removed in Sopel 8.1, …
=> db: adapt SopelDB to SQLAlchemy 2.x new style

requirements.txt
Tin, fix #1903.
I've check a set of URLs (user, subreddit, comments, image, and video) with praw versions 6.5 and 7.6 and everything worked so far. I've read their changelog and didn't see anything that would generate an error on our side.
=> pip: allow praw from v4 to v7

docs/source/plugin/anatomy.rst, sopel/bot.py, sopel/loader.py, sopel/plugin.py, sopel/plugins/rules.py, test/plugins/test_plugins_rules.py, test/test_bot.py, test/test_loader.py, test/test_module.py, test/test_plugin.py
Fix #830 by adding an optional message and three new decorators for specific rate limit messages (user, channel, and server).
=> bot, loader, plugin, rules: add NOTICE message to rate limits

dev-requirements.txt, setup.cfg, sopel/bot.py, sopel/irc/__init__.py, sopel/irc/modes.py, sopel/modules/url.py, sopel/plugin.py, sopel/plugins/rules.py, sopel/tools/target.py, sopel/trigger.py
=> implement flake8-type-checking

sopel/plugins/handlers.py
The `_module` of an entry point plugin is unlikely to have its own `__version__`. What's important is the version of the package from which that entry point was loaded.
I haven't written a test for this (yet?). Am not even sure if it should call the superclass version (`PyModulePlugin.get_version()`) somewhere as a fallback. Doing that doesn't seem very useful, but I'm open to others' thoughts.
=> plugins.handlers: override get_version() for EntryPointPlugin

docs/source/configuration.rst, sopel/config/core_section.py
Tin. Fixes a couple of omissions that led me astray while trying to reproduce an issue someone asked for help with on IRC.
Removed redundant text in the 7.1 `versionadded`, since the same information already appears just a few lines earlier.
- Docs only.
- Docs-only.
=> docs: improve coverage of `flood_max_wait` setting

sopel/modules/wikipedia.py
This PR removes user highlights `bot.reply()` from the `wikipedia` plugin, in favor of the non-highlighting `bot.say()`
Note: this PR is motivated by a personal opinion about netiquette; a user sharing a Wikipedia URL may not even know the Sopel instance exists, and the bot highlighting them is the kind of thing I consider a bit of an aggravation. Feel free to close this PR on that basis :sweat_smile: 
```
16:33 <SnoopJ> https://en.wikipedia.org/wiki/Diffraction_spike#/media/File:Comparison_strut_diffraction_spikes.svg
16:33 <terribot> SnoopJ: Error fetching section "/media/File:Comparison_strut_diffraction_spikes.svg" for page "Diffraction spike".
```
```
16:34 <SnoopJ> https://en.wikipedia.org/wiki/Diffraction_spike#/media/File:Comparison_strut_diffraction_spikes.svg
16:34 <terribot> …
```
=> wikipedia: use say() instead of reply() when reporting a URL error

sopel/coretasks.py
Tin, should fix #2289 for good but I didn't test that section in particular.
This was way too easy. The tests didn't even fail, everything worked on the first try. I don't really complain, I'm just... yeah, OK, all good then.
I've tested it with the Libera servers (they use solanum-1.0-dev), and with a friend's server using UnrealIRCd-5.2.4. Both are fairly modern IRC servers, so it is possible that this breaks with older server that don't follow the MOTD specification.
=> coretasks: join channels on MOTD

sopel/db.py
Tin. Issue introduced by the new flake8-type-checking feature [in recent release](https://github.com/snok/flake8-type-checking/commit/7be3641be6cf651822ce67f07f83d8416ae13f2c).
=> db: fix typing.cast according to flake8-type-checking

docs/source/configuration.rst, sopel/config/core_section.py, sopel/irc/__init__.py, test/test_irc.py
Tin, fix #1618.
The feature was surprisingly easy to implement, this is a draft because I want to make sure I've the right names before writing more documentation.
=> irc: configure anti-looping system

sopel/irc/__init__.py
Tin. Reading #2320 made me wonder why we used a list with manual pruning (`l = l[-10:]` after appending), and I couldn't think of a good reason. Updated tests made me pretty confident I could just swap to a deque with `maxlen` and get pruning for free.
- Caveat: Some type-checking stuff gets flagged by flake8, but those should be sorted out already on the actual `master` branch (they reference code that wasn't changed in this patch).
- (thanks to Exirel's updated test suite)
This is a draft because it's built on top of #2320. I will rebase and mark ready for review when that's squashed down.
=> irc: use deque for "stack" of recent messages

sopel/modules/currency.py
=> currency: fiat_provider config option takes precedence

sopel/loader.py, sopel/plugin.py, sopel/plugins/rules.py, test/plugins/test_plugins_rules.py
Tin. Part of #2120:
* some internal flags about example
* remove support for regex in command name
I didn't touch the currency plugin, will do in another PR.
=> loader, plugin: remove deprecated features

pyproject.toml
Tin. I tried and tried, but couldn't find any reason not to allow the newer version of xmltodict now that we no longer support Python 2.
On IRC, @Strykar said this _does_ break something, but I have no idea what (no details). I invite them to post said details here.
=> reqs: allow xmltodict 0.13

.github/workflows/ci.yml, dev-requirements.txt, pyproject.toml, setup.cfg, sopel/plugins/__init__.py
Tin. Fix #2274.
I haven't check yet if all tests pass on older version of Python with the newest pytest, so the PR is going to do that for me here (hence, the draft).
* Added "python 3.10" to the CI config
* Updated pytest to 7.1+
* Fixed an issue with Python 3.10 and the `imp` module (leftover from previous cleanup)
* Suppress a Pytest warning about plugin file rewrite (pytest does too much black magic)
=> ci, plugins: Python 3.10 and other improvements

sopel/coretasks.py
Tin. Simple subcommand rename w/variables changed to match.
These are not, and AFAICT never have been, actual host*masks*. Having the subcommand name and code variables refer to them as (host)masks has been a point of confusion for, literally, years.
This is just the first step toward making the ignore/block system work more intuitively, but you know what they say about journeys of a thousand miles…
- Successfully verified listing "host" blocks, adding one (and made sure it actually ignored my test user), and then removing it.
For full context, thought processes, tentative future plans, and so on: See #1355.
That covers a lot of ground, and most of it is rightly left for the next release (again) so we can try to ship 8.0 this year. But this is a simple patch that makes room for some of …
=> coretasks: `.blocks hostmask` -> `.blocks host`

sopel/coretasks.py
Replaced the Liquid link tag with an actual URL, since the primary purpose of these docstrings is for help output on IRC.
Added a couple examples, to show the syntax and also make it crystal clear that the inputs are interpreted as regex.
New output of `.help blocks` on my test bot, using the new sopel-help package:
Yes, I'm jumping the gun a bit on #2344 by using "host" instead of "hostmask" here, but this stuff is so simple that it's just not worth messing with stacked PRs, rebasing, etc. 😁
=> coretasks: fix/improve `.blocks` help output

sopel/irc/__init__.py, sopel/irc/isupport.py, test/test_irc.py
Take advantage of the `LINELEN` token in 005 to send longer messages than the RFC limit of 512 bytes, when possible.
Can't say I've ever seen a network actually advertise this token, but it's relatively easy to add and test so why not support it.
This was previously flagged as obsolete, but InspIRCd still uses it (refs: ircdocs/irc-defs#82, https://github.com/inspircd/inspircd/blob/e147b461173c58eb443eee0ac56f7d3c3c4b2c3a/src/server.cpp#L218).
Docs link in the code points to a nonexistent section at time of writing. See ircdocs/modern-irc#189 for the patch that will add it.
=> irc: `LINELEN` ISUPPORT token support/use

sopel/modules/seen.py
Currently, if the DB writes that the `seen` plugin tries to do fail for any reason, the error will propagate up into `bot.error()` and cause very antisocial error report messages from the bot every time the channel receives messages, if the `reply_errors` (sic) feature is turned on. In particular, I've seen this with a disk that becomes full with the `sqlite3` backend, but this patch should cover a broad class of such failures.
- Just the same test failures I see when I run `make qa` against `master` (0479737d):
`12 failed, 1268 passed, 8 xfailed, 1 warning, 73 errors in 44.38s`
=> seen: catch database write errors

sopel/modules/unicode_info.py
This PR adds support for the [`unicodedata2`](https://pypi.org/project/unicodedata2/) library to the `unicode_info` plugin, allowing the plugin to report information about codepoints from more modern versions of Unicode than the one shipped with the stdlib of the Python executing the bot.
=> unicode_info: Use unicodedata2, if available

sopel/modules/remind.py
Past-due reminders could be consumed during startup (and emit an error to the log about the event loop not being started yet).
The documentation for `@plugin.interval()` has had a warning in it about not assuming that the IRC connection will be available for I don't even know how long, at this point. It's about time core followed its advice.
=> remind: skip `remind_monitoring()` if IRC connection not ready

sopel/bot.py
This PR modifies the error report issued as an IRC message to include the ~`repr()`~ `type()` of exceptions when relevant to prevent a somewhat obscure category of errors. Closes #2353
=> bot: report exception type for relevant errors

docs/source/package/trigger.rst, sopel/trigger.py, test/test_trigger.py
Short sleep does not make me a great comprehensive reader of specs, but commands that are 1) sent from the server to a client and 2) include a <target> (channel/nick), are actually quite rare. The IRC protocol is mostly numeric replies, and very few event types actually refer to a user (nick) or channel.
The idea here, though, is that unless I forgot about an event type that actually is tied to a channel or query (PM) buffer, it is ONLY the new list of `COMMANDS_WITH_CONTEXT` that should have the `sender` set to any value other than `None`.
Undecided yet if this is enough to call #2331 closed. I remember a discussion about transitioning to a new property called `trigger.context` or similar, for clarity, but can't find it on the relevant issue. Maybe it was an IRC conversation.
'Breaking …
=> trigger: Make `sender` property more consistent

sopel/trigger.py, test/test_trigger.py
An IRC command/event such as 'AWAY' with no message, or 'PING', will have an empty `args` list.
Documentation for the (Pre)Trigger `text` attribute says that it will contain the last item in `args` if the line does not contain ':', but it previously—erroneously—contained the command name in such cases.
Starting this as a draft because it's built on top of #2359. Whether I separate the histories or not, I'll have to faff with _something_ after merging one before the other can be merged. Would rather have the simplest rebase imaginable (which this strategy will get me) than a rebase that requires the interactive mode.
Same as the parent PR, 'Breaking Change' label because fixing this after so long could cause a [spacebar heating](https://xkcd.com/1172/) incident.
=> trigger: make `text` empty if `args` is empty, per docs

sopel/irc/abstract_backends.py, test/irc/test_irc_abstract_backends.py
When UTF8ONLY is active, raise a decoding error if the message fails to decode instead of attempting other encodings.
As far as I can tell, Sopel never sends non-utf8 data unless someone's poking at the backend directly, so no other changes should be necessary to consider UTF8ONLY supported. (Actually, even this doesn't seem mandatory, just sensible)
=> backends: try only utf8 when UTF8ONLY

pyproject.toml
In setuptools 64.0, editable installs were changed. As of 65.x, I was unable to install sopel as an editable distribution without getting ImportErrors even when trying to do something as simple as run `pytest --version` (which shouldn't load any Sopel code).
I *believe* this is enough to work around the issue for now, given that pyproject.toml packages are supposed to use build isolation and the used setuptools version is separate from whatever's installed in the user's environment. At least my brief testing bore this out, with ~=63.0 requested by the TOML file and 65.something installed in pip.
No milestone; this is entirely for us developers, not tied to any release. (It's a build-time dependency, not required at runtime.)
=> build: pin setuptools while we figure out PEP-0660 editable install

sopel/coretasks.py, sopel/irc/abstract_backends.py, test/irc/test_irc_abstract_backends.py, test/test_coretasks.py
Upon receiving a line that isn't valid unicode, decode_line raises an exception which isn't caught and kills the event loop.
I broke this in #2365 by confusing what class I was in and which contained .isupport, and trusting the (also by me, also incorrect) unit tests... Sorry >.>
=> backends: fix event loop close on invalid utf8 rx

sopel/modules/unicode_info.py
* ignore import error because `unicodedata2` doesn't have a stub
* ignore no-redef error because `unicodedata2` is optional and it has the same interface as `unicodedata`
Also modified some comments because nitpicking is my pride.
=> unicode_info: ignore type check on unicodedata2

sopel/formatting.py, test/test_formatting.py
A literal `0` (nominally the color white, in mIRC convention) evaluates as `False`, which was being skipped by the `not` and making the function return its input text unchanged.
Regression check added to existing `test_color()` case.
No further 7.x releases are planned, but this fix probably _should_ be included if another patch version happens.
This took about 10x as long as it should have because I ran into `setuptools>=64.0` breaking how Sopel does editable installs and had to figure out that problem before I could actually test the patch. That problem needs its own issue/PR, but I still need to do a little more research before I can open a useful one of either.
Kudos to @xnaas for hacking some extra color schemes into a forked sopel-rainbow plugin, which revealed this bug.
=> formatting: fix `color('some text', 0)`

sopel/coretasks.py, sopel/irc/abstract_backends.py, test/irc/test_irc_abstract_backends.py, test/test_coretasks.py
The IRC backend doesn't need an attribute for UTF8ONLY that must be updated separately by coretasks when receiving 005. Because the backend has a `self.bot` passed in at construction time, it can check the active ISUPPORT flags directly.
=> backends: simplify UTF8ONLY handling

sopel/bot.py, sopel/coretasks.py, sopel/irc/__init__.py, test/test_coretasks.py
The `connection_registered` attribute itself is now a property, which first checks to see if the bot's `backend` exists (is not `None`) and then whether the `backend.is_connected()`, before finally seeing if the internal `_connection_registered` flag has been set.
Also added a few places where the internal flag should be reset back to its initial value of `False`, such as if the bot is about to quit or the backend's `on_close()` handler was called.
All of this is to try and make `bot.connection_registered` reliable for plugins like `remind`, which have scheduled tasks that might need to send data to IRC and need a reliable way to check whether the connection is ready to accept such data before operating.
- Note that this required adding a bit more setup to two `test_coretasks` units.
=> bot, irc, coretasks: more robust `bot.connection_registered` value

sopel/config/types.py, sopel/formatting.py, sopel/tools/__init__.py, sopel/tools/memories.py
For #2381 I made sure we wouldn't introduce any Error-level alerts, because those would have given the `master` branch a ❌ check status. Anything below that level (that wasn't a false-positive or a test case) was mostly left alone.
This PR's branch name, `useless-code`, is inspired by the alert label that caught my eye first. At time of opening that label also applies to most of the alerts that will be fixed by this patch.
- I managed to break my flake8 somehow, but these tweaks are so minor I did not waste time trying to fix it just for this PR
=> CodeQL minor nitpick pass

.github/workflows/ci.yml, pyproject.toml
Other projects seem to have success adding this now, unless they rely on some unusual setup (e.g. using `brew`).
Assuming the patch builds successfully, I will update the package's trove classifiers before merging.
- Does not change code.
- This is why I'm opening the PR, to test what this touches (CI pipeline in GHA)
- PR passed checks, so I consider this task item done
=> ci: begin testing on Python 3.11

sopel/modules/remind.py
Methods on `bot.backend` are really supposed to be used internally only, not by plugin code.
Improving the reliability of `bot.connection_registered` (the reason it wasn't already used here) is being taken care of in a separate patch, #2375.
- Can't be tested For Real™ until the fixes land for `bot.connection_registered`.
=> remind: use `bot.connection_registered` instead of internal method

sopel/modules/xkcd.py
Bing has become supremely unreliable. In a shocking turn of events, it seems that DuckDuckGo no longer vomits on the long string of `-site:` operators used in this plugin.
**Current `master`:**
```
16:03:35 <~dgw> ,xkcd group chat
16:03:36 <SopelTest> dgw: Could not find any comics for that query.
```
**With this patch:**
```
16:31:03 <~dgw> ,xkcd group chat
16:31:04 <SopelTest> [xkcd] Group Chat Rules | Alt-text: There's no group chat member more enigmatic than the cool
person who you all assume has the chat on mute, but who then instantly chimes in with no delay
the moment something relevant to them is mentioned. | https://xkcd.com/2235
```
Someone else can investigate backporting this to 7.1.x if they like, but it's easy enough for someone to just use the newer `xkcd.py` in an old bot …
=> xkcd: switch to DDG for keyword lookup

sopel/modules/xkcd.py
Asked the creator of searchxkcd.com on Twitter about an API. Was told there is no true public API (yet), but I could pull the backend URL out of network tools. So have I done.
Makes the most sense to keep the original `web_search()` method around as a backup option. For example, two days after the latest comic's release on Friday (today is Sunday), searching searchxkcd.com for its title returns no results. For this special case we have the 'latest' operator, but there are no guarantees for how frequently searchxkcd's index is updated with fresh comics.
Complements #2376, but shouldn't replace it. The two patches work together to fix _and_ improve search results in `xkcd`.
Aside: Sure would be nice if xkcd itself provided a JSON file listing all of the comics' basic data in one place. The …
=> xkcd: try searchxkcd.com backend, with web-search as fallback

sopel/coretasks.py, sopel/tools/target.py
I saw a very angry person talking about Sopel somewhere (intentionally vague). Their complaint _du jour_ was that Sopel doesn't expose `User`s' realnames.
While I chose not to engage them in conversation (some users, you're better off without, as goes the conventional business wisdom), the gap in our API is a valid point and it's not difficult to fix.
- My flake8 is still busted 🙁 and the test suite doesn't cover WHO/WHOX handling yet anyway ☹️
- Automated testing no, but I manually verified (via `sopel-ipython` console) that realnames were correctly populated from both WHO (on Rizon) and WHOX (on Libera) replies
I needed to get back to something else and didn't have time to work on tests right now, but still wanted to get the code itself out there for y'all wonderful people to look at. …
=> Track `User`'s realname

sopel/tools/time.py
Was working on something in sopel-github and got annoyed that I had to check `git blame` to verify that the functions I wanted to use would be available in that plugin's minimum required Sopel version.
`willie.tools.time` came into existence in the 5.3 release, so I used that as the module's `versionadded`, and treated the namespace change from `willie` to `sopel` as a `versionchanged` event.
If people are nice to me (read: this gets reviewed in something less than a month 😝), I might go through the rest of `sopel.tools` and add any missing version annotations in its other submodules, too. This is the sort of thing I'm always on the lookout for when working on other stuff, because if the documentation annoys _me_ (who's been around the project for almost a decade), it will _almost …
=> tools.time: versionadded annotations for great justice

sopel/cli/config.py, sopel/cli/plugins.py, sopel/cli/run.py, sopel/cli/utils.py, sopel/config/__init__.py, sopel/config/core_section.py, sopel/config/types.py, sopel/tools/__init__.py
Started looking at `sopel.tools` as a follow-up to #2379 and noticed some more cleanup that could be done. Specifically:
* `OutputRedirect` class is used by nothing, appears to be a relic of the 3.x-era logging system, and should be deprecated.
* `check_pid()` belongs under the `cli` namespace, because that's the only code that needs it. And plugins shouldn't be touching PIDs anyway.
* `stderr()` also ideally should never be used by plugins. If they really really want to print directly to a terminal instead of using a logger, they have access to `import sys; print('some bs', file=sys.stderr)` on their own.
* `get_input()` is already deprecated, but I had to replace uses of it to eliminate circular imports (because I'm perhaps foolishly keeping the moved functions available in `tools` …
=> tools: deprecations & reorganization (feat. `sopel.cli`)

pyproject.toml
This PR adds the `maintainers` field to the project metadata, and adds historical contributors with more than 100 commits (as tracked by Sopel's repository) to the `authors` field. The latter is completely arbitrary, so people who know the long tail of the project's history may have suggestions for changes to that. A simple alternative would be to move anybody who's in the `CREDITS` file into this field.
Closes #2339
=> pyproject.toml: list maintainers, historical authors

sopel/irc/__init__.py, sopel/irc/abstract_backends.py, sopel/irc/backends.py, sopel/irc/isupport.py, sopel/irc/modes.py, sopel/irc/utils.py
The top-level docs page for `sopel.irc` did, in fact, have an inline note about the `irc` module being for internal use. That wouldn't catch the eye of someone landing on a submodule via search (internal or web), though. Seemed prudent to beef up the presentation to `.. warning::` and also add a notice to each submodule.
Annotating `sopel.irc.isupport` was extra fun, because part of it *is* included in the bot's public API.
- Haven't run tests because this doesn't touch code, but `make quality` passes.
- No code changes to test, but Sphinx didn't throw any (new) warnings and the HTML output seems to work as I intended.
=> irc: annotate submodules with internal-use warnings

sopel/modules/wikipedia.py
This PR adds support for Wikipedia links to media embedded in articles (i.e. fragments of the form `#/media/File:…`), which closes #2316
**Edit:** While writing up the follow-up issue, I realized that `File:` is specific to English Wikipedia, so in 63187e9 the prefix check was relaxed to support other references to files on other language communities on Wikipedia. It seems to Just Work™ and the description retrieval is fairly cautious anyway.
Note that this changeset **does not** emit an image description for links directly to a `File:…` article, but it's probably possible to rework it to do that too, if desired
=> wikipedia: support media fragments

sopel/irc/__init__.py, sopel/tests/factories.py, sopel/tests/pytest_plugin.py, sopel/trigger.py, test/test_trigger.py
Fix #1886.
In this PR, I modified `PreTrigger` to parse the `sender` to check if the prefix was a `STATUSMSG` prefix, i.e. a message intended to a specific privilege level in the channel (such as ops, voice, etc.). Once this is done, the `PreTrigger` remove that prefix from the `sender` to create an instance of `Identifier`. On the bot's side, every time a `PreTrigger` is instantiated, `bot.isupport.get('STATUSMSG')` is provided.
I added some tests to show how that works and ensure it works as intended without breaking anything, so we should be all good.
Two notes to consider for the future:
* we may want to change the list of channel prefix to something more restrictive, or not
* we may want to set a default value for the `STATUSMSG` value, or have something a bit smarter about that
Both …
=> trigger, irc: use STATUSMSG to handle status specific messages in channels

sopel/config/types.py, test/test_config.py
Fix #2263. That was way easier than I expected.
=> config: strip quotes from FilenameAttribute

sopel/irc/__init__.py, sopel/irc/backends.py
Part of a strategy for addressing #2373, we want to have a backend that works like a normal backend but isn't connected yet, for use instead of a `NoneType` object (which obviously won't have any of the methods a backend would).
The idea is to make it so calls to things like `backend.is_connected()` still work even pre-connection, so it's easier for core & plugin code to be responsible and check the connection status before trying to send things over the IRC connection.
- Will revisit this when the PR is actually final (starting as draft)
- Ditto above
=> irc, backends: dummy non-connected backend for convenience

sopel/plugin.py, test/test_module.py
This is the simple way. It doesn't preserve any backward compatibility for uses imported via `sopel.module`, and I don't think that's needed. It'd be a spaghetti mess for not much gain.
Closes #2399.
- With an actual test, in fact.
=> plugin: `require_privilege()` implies `require_chanmsg()`

sopel/bot.py, sopel/coretasks.py, sopel/irc/__init__.py, test/test_coretasks.py
This will let us add API features that take advantage of the `.wait()` method available for Event objects.
Shouldn't affect plugin code (internal or third-party) much, if at all, since this is an internal value. `connection_registered` (no underscore) is still the name in all released versions of Sopel, anyway. In 8.0 it has become a property that checks multiple pieces of state so the answer returned can be more consistent.
Follow-up to #2375, where @Exirel proposed this idea but did not block the merge. I thought about it, opened #2391, and left it for 9.0. Then I thought some more this weekend and realized, it doesn't _matter_ what type `bot._connection_registered` is any more because it's private now. We can do whatever we want to it.
So I decided to make it a `threading.Event` object …
=> irc: use `threading.Event` for internal `_connection_registered` flag

dev-requirements.txt
Looks like autoprogram 0.1.8 is all behind-the-scenes changes to keep up with newer Python versions, but I think it's important for us to stay on the newest release unless something breaks.
I will look at any pages that include autoprogram output in deploy preview (under Checks, below).
=> docs: update sphinxcontrib-autoprogram

sopel/logger.py
The revamped `connection_registered` bot property checks for a backend, a socket connection, AND connection registration. This is what we need to prevent doing a `say()` before the IRC connection is ready.
This might be a fix for #2255, but I haven't tested for that specific case yet. Regardless, this old-style check is due for replacement.
=> logger: use newer, more robust IRC connection check

sopel/modules/wikipedia.py
This PR fixes #2412 by discarding the query string from the name of the article to be searched.
=> wikipedia: support query strings in Wikipedia URLs

sopel/irc/__init__.py, sopel/irc/abstract_backends.py, test/irc/test_irc_abstract_backends.py
We previously had a silly pattern of calling safe() for most (but not all!) arguments passed to send_command. This is _usually_ not an issue since the contents are either not user-generated or must be sent through IRC (so cannot contain `\r\n`), but sometimes that's not the case, especially for privmsg/notice. Some plugins may also call send_command directly. Let's just pre-empt the whole class of potential problems by safe()ing _all_ args in `prepare_command()`.
Supersedes #2356. Thanks to @semarie for finding this issue.
=> abstract_backends: safe() all prepare_command args

pyproject.toml
Tin. Makes more sense to cleanly drop this in 8.0, rather than wait for 8.1.
I was already thinking along these lines, but IRC discussion this morning pushed me the rest of the way.
=> reqs: do not require sopel-py

sopel/cli/run.py, sopel/cli/utils.py, test/cli/test_cli_run.py, test/cli/test_cli_utils.py
Github won't let me reopen #2093.
+`Bugfix` because it now prints the .cfg path instead of ".sopel/foo"
This fixes two annoyances:
- Sopel automatically adds `.cfg` when searching the config dir, but it doesn't when searching the current working directory
- If the config file is not found, it currently automatically starts the configuration wizard.
Combining these two, a user (me) will (does, regularly) `cd` to their non-default Sopel config dir, run `sopel -c mybot` expecting it to load mybot.cfg and run, but instead have Sopel create ~/.sopel/ and ~/.sopel/mybot.cfg and start the config wizard.
Searching `$PWD/{config}.{ext}` is straightforward, but not automatically running the wizard is probably subject to opinions. I changed it to the below output, but I would also be content with …
=> cli: look harder for $PWD/cfg, don't automatically start wizard

sopel/modules/reload.py
Sopel's not designed to run directly from a Git working directory any more, so let's not advertise this command that relies upon it.
- It was really easy to test, because this only removes stuff.
=> reload: remove `.update` command

sopel/modules/reload.py
Tin. Lighter weight (no-code) alternative to #2043.
- Easy, because no code is touched. I verified the appearance of `.help reload` output.
=> reload: better document limitations of `.reload` command

sopel/cli/utils.py, sopel/modules/reddit.py
Bot owners can now turn off `u/someone` and `r/subredditname` expansion without having to use the dumpster fire called per-channel settings. Closes #2194.
Bundles a whitespace change I thought had been added to #2299 during merge, but I messed it up. I'd rather stick it in an unrelated PR than push directly to `master`. 😅
=> reddit: add `slash_info` toggle

docs/source/configuration.rst, sopel/bot.py, sopel/config/core_section.py
Setting `logging_channel_level = DEBUG` sends so much to IRC that the bot got stuck waiting for flood protection to release.
The only sensible solution is to disallow setting channel logs to the `DEBUG` level, and along the way I've also made it so that channel logging always defaults to `WARNING` if not configured, instead of inheriting the console's `logging_level` setting.
Indirectly related to #2255, both because I discovered that bug while working on this one last year _and_ because I devised this solution while testing to see if that issue could be closed after #2410.
=> logging: disallow `DEBUG` channel logs & stop inheriting console log level

sopel/modules/safety.py
* failure to delete old malwaredomains file is upgraded to a warning: fixing the problem requires manual intervention
* domain list update is now all debug, all the time, except if there is an error (which generates a warning so the bot owner can see if it's repeatedly failed)
* cache cleanup being skipped is also debug now; it didn't make sense for "cleanup already running" to be louder than "starting cleanup"
I'm looking specifically at `info()` logging calls in light of #2419 and very well might run through all the places where the most common messages I see in logs of the bots I run/admin just to double-check that we're using the INFO level sensibly.
=> safety: logging level tweaks

sopel/modules/url.py
This changeset adds a bit of caution to the DNS resolution that might happen in the `[url]` plugin, to fix #2348
- `1370 passed, 8 xfailed, 1 warning in 52.60s`
=> url: Wrap DNS resolution in try/except

sopel/irc/isupport.py, test/irc/test_irc_isupport.py
This changeset handles hexadecimal escape sequences in `ISUPPORT` parameter values, implementing #2195
=> irc: unescape hexadecimal sequences in ISUPPORT parameter values

sopel/modules/pronouns.py
Since @lucasew was kind (and industrious) enough to make a pronoun.is clone written in Svelte, which we can fork (https://github.com/sopel-irc/pronoun-service) and host a copy of on our existing Netlify plan, now seems like the perfect time to replace the old, much cuter, domain name with one that actually works. 😢
=> pronouns: pronoun.is has been dead for months; switch to our own backend

sopel/modules/url.py
This changeset resolves #2230 by dropping the incorrect information from the relevant docstrings, and also does some light refactoring of `title_auto(), process_urls()` for the sake of future maintenance. Also included is a fix for a bug discovered while writing this PR, where a URL matching a registered callback causes following URLs in the message to be ignored.
- `1426 passed, 8 xfailed, 1 warning in 52.07s`
=> url: fix premature loop termination, docstring cleanup & slight refactoring

sopel/modules/pronouns.py
Adds the option to use "your own domain" for the pronoun-info links output by the `pronouns` plugin.
Since it's so easy for _us_ to host our own `pronoun.is` clone, that means it's also easy for our users to do so. I think bot owners having the ability to choose how this plugin's links look is very much in keeping with the plugin's spirit, and it's simple to do.
This is a follow-up to #2437—and by rights should have been done _in_ #2437, but I didn't think of it yet.
- `1430 passed, 8 xfailed, 1 warning in 38.28s`
=> pronouns: make base URL of links configurable

sopel/modules/currency.py
Title. Sends to PM, because the list could be quite long.
Currently allows for up to 5 messages' worth of ticker symbols.
=> currency: add `.currencies` command to list supported symbols

sopel/bot.py
The formatting, in particular, is what was problematic here. Sphinx doesn't provide a way to negate the monospace formatting of a `:meth:` reference when using a custom title, so the only way to avoid having random monospace words in the middle of this paragraph is... rewriting to eliminate the xrefs.
Which is to say, if there's a better answer to [this question](https://stackoverflow.com/q/45741326/5991) in the future, we can put this back the way it was.
- No code changes; didn't run `make test` locally but `make quality` was indeed fine.
=> bot: eliminate problematic xrefs from `SopelWrapper` docs

sopel/bot.py, sopel/trigger.py, test/test_bot.py
Fix #2440 by adding a default destination on the `SopelWrapper` (idea from @SnoopJ) that properly handles status-specific prefix. Most of my work was to add tests and docstrings.
=> bot, trigger: use status prefix in SopelWrapper

pyproject.toml
CI is broken with urllib3 2.x, but the specific package that fails our tests (vcrpy) is not moving very swiftly to release a fix.
While they debate which versions of urllib3 to support, we just want to have working CI so we can start merging our slowly growing PR backlog.
Because urllib3 is a transitive dependency of requests, it belongs in the regular requirement list even though this pin is to fix tests.
This has been blocking us for about two weeks, and that's more than long enough to warrant a temporary dependency pin (even though I prefer to avoid them, in general). I'm subscribed to the upstream issue already [pointed out by @SnoopJ](https://github.com/sopel-irc/sopel/pull/2434#issuecomment-1541338658), for notifications relevant to undoing this.
=> build: pin urllib3 to <2.0 for now

sopel/irc/__init__.py, sopel/irc/abstract_backends.py, sopel/irc/backends.py
Closes #2111 and open the way for better error handling and connection retry.
=> irc: Improve output for common connection errors

sopel/irc/backends.py
Tin. Based on #2430, closes #2350.
To elaborate a bit: I realized that having a connection error and other uncaught exception in the run-forever loop (await read task, await write task) would lock the bot, and so it's not just friendly error messages, it is also a better exception handling.
=> irc: properly manage exception of the run-forever loop

sopel/modules/find.py
Unescaped `|` was messing up capturing the flags at the end of the line.
Introduced in #1993, first released in v7.1.0. Should be backported _if_ we make a 7.1.10 release (but I'm still not planning one).
=> find: fix flags in pipe-separated substitutions

docs/source/configuration.rst, sopel/config/core_section.py, sopel/coretasks.py, sopel/tools/target.py, test/test_coretasks.py, test/tools/test_tools_target.py
Sending mode `+B` by default is pretty silly. As of #2088 we should have stopped doing so. Now we will.
More importantly, WHO replies contain a bot flag on servers that support the bot-mode spec; it's indicated by the same character as the modechar advertised in ISupport's `BOT` token. We should track that—and you guessed it: this patch adds an `is_bot` attribute to `User` objects.
I'm hoping to write some more tests when I have time, because this part of coretasks seems pretty under-tested. Therefore, I'm starting the patch as a draft, to collect feedback until I get to that step.
=> core: better bot-mode handling

sopel/bot.py, sopel/plugin.py, sopel/plugins/rules.py, test/plugins/test_plugins_rules.py, test/test_bot.py
Fix #2325.
This changeset includes:
- unless somebody has suggestions for more fields, I'm considering this complete
---
=> Add more placeholders to rate-limit messages, move template interpolation from `Rule` to `Sopel`

sopel/modules/remind.py, sopel/tools/time.py, test/tools/test_tools_time.py
- **Breaking:** `validate_timezone()` raises `ValueError` even if passed `None` now, instead of returning `None`
- "Duration" named tuple returned from `seconds_to_split()` function
- Added tests to cover original & fixed behaviors
Tin. Oh, and also I added type annotations and fixed the resulting type errors.
I ensure that the tests all pass on the current version of `sopel.tools.time`, **then** I added type annotations, so there is a guarantee that it works pretty much as it did before... except for a bug I fixed where you could call a function without a `db` and it would raise an `AttributeError` because `NoneType` doesn't have the right method.
=> tools.time: tweaks & tests

sopel/modules/translate.py
Don't make me PM the bot to not even be reminded how .tr wants language hints.
You may now discuss whether we should reorder the examples, have one or two hints, why we don't have a `@plugin.help("Something less docstring-ish here")`, etc. in comments.
=> translate: Make help more helpful about language :hints

test/coretasks/test_coretasks_cap.py, test/coretasks/test_coretasks_sasl.py
The major edge cases handled in Sopel's SASL PLAIN code are:
- Unexpected continuation message from the server (`AUTHENTICATE PLAIN` ack'd by something other than `AUTHENTICATE +`)
- Very long password that b64encodes to exactly 400 bytes
- Very long password that b64encodes to over 400 bytes
IRCv3 recently merging [a patch to add an example](https://github.com/ircv3/ircv3-specifications/pull/521) of split token negotiation inspired me to cover that in our behavior tests.
Along the way I fixed a couple typos, and realized it would also be pretty easy to validate Sopel aborting SASL PLAIN on a non-empty message from the server.
- This change is literally tests, so it tested itself 😁
Big thanks to @Exirel for writing tests of the main SASL PLAIN codepath, which I copied and adapted to cover …
=> test: cover obvious SASL PLAIN edge cases

docs/source/plugin/time.rst, sopel/bot.py, sopel/coretasks.py, sopel/irc/__init__.py, sopel/modules/remind.py, sopel/modules/uptime.py, sopel/plugins/rules.py, sopel/tools/time.py, sopel/trigger.py, test/plugins/test_plugins_rules.py, test/test_bot.py
As @SnoopJ mentioned on IRC right after opening #2457, `datetime.utcnow()` is deprecated in Python 3.12 (and also `datetime.utcfromtimestamp()`). The recommended replacements for those items have been usable for most of Python 3's history—though we don't get to use`datetime.UTC` instead of `datetime.timezone.utc` until Python 3.11 is our minimum version.
As often happens when I poke at stuff, there are some minor documentation corrections lumped in here that I didn't think warranted (a) separate PR(s).
I wanted to go further with this and get rid of `pytz`, but [`zoneinfo`](https://docs.python.org/3.9/library/zoneinfo.html) isn't available until Python 3.9. (There is a [`backports.zoneinfo`](https://pypi.org/project/backports.zoneinfo/) package, but it hasn't been updated in a while and …
=> Replace uses of deprecated `datetime.utcnow()`

sopel/bot.py, sopel/irc/backends.py, sopel/modules/url.py, sopel/plugins/rules.py
This resolves all known errors in `mypy sopel` output, as of commit time. There are few enough other outstanding PRs, I don't think introducing new errors after this is merged will be much of an issue.
(It would help if I started checking `make mypy` before merging things, to avoid introducing new errors after fixing this set of them… I'll try to remember that step.)
=> mypy: fix currently known type-checking errors

sopel/modules/remind.py, test/modules/test_modules_remind.py
"Unexpected AttributeError: 'str' object has no attribute 'utc'" begone.
Fixes a bug I introduced in #2468 by not being careful enough with my imports. Code review or not, I should've caught it. (And I was reminded to finish/open this PR by `mypy --check-untyped-defs` flagging these errors, so that's all the more reason to work toward #2461 in the longer term.)
`mypy --check-untyped-defs` still reports errors in `sopel/modules/remind.py` after this patch, but they'll be fixed separately. @SnoopJ and I have been chipping away at that list over the weekend.
=> remind: fix import streamlining gone haywire

sopel/modules/safety.py, sopel/modules/url.py
This PR fixes an edge-case in `url` and `safety` when the result of `urlparse` has a `hostname` of `None`
```
19:20 <+dgw> https://?bonk
19:20 <+Sopel> Unexpected AttributeError ('NoneType' object has no attribute 'lower') from dgw at 2023-06-13 23:20:54.685361+00:00. Message was: https://?bonk
19:20 <+Sopel> Unexpected AttributeError ('NoneType' object has no attribute 'lower') from dgw at 2023-06-13 23:20:54.705164+00:00. Message was: https://?bonk
```
- This also doesn't seem to introduce any new failure to `mypy` over Sopel's codebase
=> safety, url: skip handling invalid links with empty hostnames

sopel/bot.py
If a Trigger causes an error in a plugin, we already know when the error happened because the logger call is timestamped. The error as reported to IRC also is timestamped, and `datetime.now()` is not useful data.
(It is, however, confusing data. Considered replacing it with `trigger.time` but decided against that, since `server-time` means those could be in the past/future, making the timestamp embedded in the log message even *more* confusing instead of less.)
=> bot: don't add duplicate timestamp into error log line

sopel/bot.py, sopel/config/types.py, sopel/coretasks.py, sopel/db.py, sopel/irc/__init__.py, sopel/irc/backends.py, sopel/irc/capabilities.py, sopel/irc/isupport.py, sopel/irc/modes.py, sopel/loader.py, sopel/modules/currency.py, sopel/modules/meetbot.py, sopel/modules/safety.py, sopel/modules/tld.py, sopel/modules/url.py, sopel/plugin.py, sopel/plugins/capabilities.py, sopel/plugins/handlers.py, sopel/plugins/rules.py, sopel/tests/factories.py, sopel/tools/target.py, sopel/tools/time.py, sopel/trigger.py
It turns out that "where possible" is equivalent to "almost everywhere". There are a _very_ few places where we still have to leave `typing` aliases in for compatibility [with Python versions before 3.9](https://peps.python.org/pep-0585/).
- This also includes running `mypy` 1.4 under Python 3.8, to make sure none of the changes breaks that version. (I did not bother to test Python 3.7 since it's EOL any day now. Tentatively it's EOL _today_, but I haven't seen any formal announcement or update to [the Python Versions page](https://devguide.python.org/versions/) yet.)
Follow-up to #2471; prerequisite for finishing #2477 (so I can extract a very nice, clean file for packaging externally).
Haven't touched `remind` as it's due to be removed shortly (#2478, replaced by external package).
=> mypy: use generic types instead of `typing` aliases where possible

docs/source/plugin/advanced.rst
This changeset adds an example to the "tips and tricks" for plugins of importing another plugin and re-using a command from therein, as well as a warning about the potential for the duplication problem described in #2488.
- [N/A] No issues are reported by `make qa` (runs `make quality` and `make test`)
=> docs: add example of plugin re-use

sopel/modules/tld.py
Fix regressions in the `tld` plugin from #2471. Mea culpa…
- Not really relevant since these didn't cause test failures in the first place 😛
- Before: `.tldcache update` spat an error into the bot log
- After: `.tldcache update` yields DEBUG level log messages indicating success
Kinda broke the parser in 3ffe55c097a53287a9d0d7aa159e2f33ae789a67, then hid that error by breaking the data fetch too in c24dfa209c3d2965939f227992c16168bc9fb69c when I tried to get too smart with one-line statements.
=> tld: fix regressions from type-hint cleanup

sopel/__init__.py
This PR fixes #2493 by adding a module-level docstring to `sopel/__init__.py`. I just copied the first two sentences from https://sopel.chat
- [N/A] No issues are reported by `make qa` (runs `make quality` and `make test`)
- [N/A] I have tested the functionality of the things this change touches
=> docs: add docstring to library root module

.github/workflows/ci.yml, README.rst, pyproject.toml, setup.cfg, sopel/__init__.py, sopel/bot.py, sopel/cli/run.py, sopel/irc/isupport.py, sopel/modules/announce.py, sopel/modules/tld.py, sopel/plugins/handlers.py, sopel/plugins/rules.py, test/plugins/test_plugins_handlers.py, test/test_plugins.py
This fulfills the last "Finally letting the dead snakes lie." part of [the 8.0.0 milestone](https://github.com/sopel-irc/sopel/milestone/15)'s description. Python 3.7 was officially EOL'd as of a month ago, on June 27.
- (As of when I prepped the patch.)
- When I wrote it, I did, with `make test` etc. (Now it needs a rebase for retesting.)
@SnoopJ and @Exirel arrived at similar conclusions for dealing with aliases in `plugins/rules.py`; this has a conflict with 098d8c309058dc794dd04d0d464598482ca94505, but the approaches are quite similar. That and b0693b7b0da1047aa0f509a30f9d15ef6b71065d are both from #2471, which touched a bunch of stuff (so I knew the risk of conflicts with this relatively long-lived housekeeping branch was inevitable).
The only other little conflict is more directly …
=> build, meta: drop Python 3.7 support, checks, and CI job

sopel/tools/calculation.py
`ast.Num` and friends have been deprecated since Python 3.8, but only started to generate warnings in Python 3.12 prereleases.
Feels like stdlib made a bad trade here, simplifying Python internals in exchange for making users write uglier, more complicated type checks such as this. But it's been so long, it's not as if they'll un-deprecate the older, more-convenient-for-the-user classes.
I was under the impression that `ast.Constant` would work as far back as Python 3.6, but apparently not. This change has to wait until we're ready to drop Python 3.7.
=> tools.calculation: replace deprecated `ast.Num` with `ast.Constant`

.github/pull_request_template.md, .github/workflows/ci.yml, Makefile, contrib/tox.ini
I think Sopel 8.0 is ready to enforce type check (close #2461).
I know I did that, so I'm owning my mistake, and rename "make quality" by "make lint". A linter is something that checks your code for errors, and both flake8 and mypy are linters.
There are now 2 new make commands:
* make lint-style: perform any code style check (today: flake8 only), it could be used for a pylint check for example, or isort, or rst check, or anything that could help us with code style in the future
* make lint-type: perform any type check (today: mypy only)
The command `quality` is replaced by the command `lint`, which runs both `lint-style` and `lint-type`.
Type check is now mandatory in CI, and the PR template has been updated accordingly.
I used the kebab-case style for the lint sub-commands, while other …
=> ci, make: "lint" (flake8 & mypy) replace "quality"

test/irc/test_irc_capabilities.py
Some IRCds include trailing space in capability lists, and this is not a spec violation. Default `.split()` behavior in Python should handle it fine, but it's also good to be explicit that we expect the default behavior, through tests.
- `Success: no issues found in 82 source files`
- `1322 passed, 8 xfailed, 1 warning in 70.41s (0:01:10)`
Inspired by ircv3/ircv3-specifications#530, which is not yet merged. However, since this is de facto behavior by UnrealIRCd and InspIRCd that isn't likely to change very soon even if the spec amendment is rejected, I think we should just add the tests.
Review requested from @Exirel specifically because the new capability system is his baby, and he's the most likely one to point out any incorrect assumptions I might have had about how to adapt existing …
=> test: add capabilities test cases for trailing space handling

sopel/coretasks.py, test/test_coretasks.py
Tin. Also added `None` to tested cases, so if it goes back to throwing an error after future changes we'll find out about it.
- The corresponding (new) test case `test/test_coretasks.py::test_handle_isupport_bot_mode[None]` initially failed with an exception traceback, as described in #2509.
With the patch applied, it passes.
Fun facts about this bug:
- It was introduced in #2448 (my fault).
- I considered giving `core.modes` a `default=''`, but it could still become `None` if someone puts `modes = ` into their config file. The logic changes here would still be required to handle that case, so I decided that `None` was still a more semantic "not set" value than empty-string and left it without a default value.
=> coretasks, test: handle `core.modes` setting being `None`

sopel/modules/xkcd.py
I started this branch intending to fixup several other alerts, but realized that most of them were of the same type we already decided to dismiss (no one really cares about the return value of a plugin callable).
However, `xkcd` has a real function that was flagged by this rule, so I chose to still fix it even though it means opening a dinky +1 pull request. But I won't bother milestoning this until it's merged, so it doesn't affect our release timelines in any way.
=> xkcd: address py/mixed-returns CodeQL alert

sopel/modules/search.py, test/vcr/modules/search/test_example_suggest_0.yaml, test/vcr/modules/search/test_example_suggest_1.yaml
`xmltodict` presents a response with only one `<CompleteSuggestion>` element as just a plain OrderedDict, without any list wrapping it. This PR fixes the behavior, adds an `@example` test covering a query that currently returns only one result, and updates the VCR cassettes for all `@example` tests.
As a bonus, which example should appear in `.help suggest` is now explicitly specified with `user_help=True`.
- Same as my last PR, an unrelated error appears in my local `make lint` run that doesn't appear in our CI.
=> search: fix cases where `.suggest` gets only one item back

README.rst
The old link went to the latest *release*, not master.
- Non-code change.
- Non-code change.
=> README: fix link to *latest source* archive

sopel/tools/memories.py
We aren't using LGTM any more, and thus don't need to trick it (46f184e6a030e955364c38546e8ce9c5cecd261f, part of #1754) into suppressing a warning about attributes that were added to `SopelMemory` vs. the base `dict` object it's extending.
I don't think this'll do anything in CI, but it fixes a mypy error that seems to only appear on my system. Since there's no technical reason for these assignments to exist, rather than wast time figuring out how to fix the type-check error, let's just remove them.
Like LGTM, the CodeQL static analysis we use now is also difficult/impossible to use effectively on a local machine, so if this brings up any new alerts I/we will have to decide what to do after the fact.
- Fixing an issue reported by `make lint` locally was in fact the entire reason I made …
=> tools.memories: remove obsolete LGTM tricks

contrib/tox.ini
This changeset drops Python 3.7 from the `tox` config, since this version is now EOL and no longer targeted by Sopel.
=> contrib: drop Python 3.7 from tox config

sopel/bot.py
This changeset adds a deprecation notice to `SopelWrapper` as the first part of #2460.
=> bot: add deprecation notice to SopelWrapper

sopel/lifecycle.py
This changeset modifies the version check for deprecation warnings so that only the [release segment](https://peps.python.org/pep-0440/#public-version-identifiers) of a version tag is used to check if a warning should be issued. For instance, currently a `@deprecation(warning_in="8.0")` _will not warn_ in `8.0.0.dev0` because the pre-release is considered to come before the 'final' release.
@dgw mentions that this might make for noisy logs in some cases, but I'm of the opinion that if I am running `8.0.0.dev0`, I _want_ to see deprecation warnings that will be current when `8.0.0` is finalized, _before_ that version is tagged. This is a concern for both core usage of in-the-future deprecated features, and for plugin authors who are checking their plugins against a coming release (although …
=> lifecycle: issue deprecation notices in pre-releases

dev-requirements.txt, docs/source/conf.py, docs/source/index.rst, docs/source/package/plugins/rules.rst, docs/source/plugin/advanced.rst, sopel/db.py, sopel/plugin.py, sopel/plugins/rules.py, sopel/tools/identifiers.py, sopel/tools/memories.py, sopel/tools/target.py, sopel/trigger.py
First, I upgraded Sphinx to the latest version, which requires to upgrade Furo as well. That went well so that's good! Then I added links to the general index and the Python module index, because they are nice.
Then I tried to fix Sphinx autodoc's warnings regarding type annotations. I more or less figure out a way to fix one or two... but then I got stuck very hard: Sphinx, currently, does not handle type annotation properly. For some reason it works for `TypedRule` now but not with some `datetime.datetime` annotation? There are clearly bugs (that are not new to version 7.0 of Sphinx by the way), and I tried few options (such as using `autodoc_type_aliases`, or for a moment I switch to another autodoc extension, with the same issues). Sopel is not an isolated case, [as this issue shows …
=> docs, dev-requirements: upgrade sphinx and try to fix some type issues with documentation

.github/workflows/codeql.yml
No more false security warnings in test files.
- I haven't touched any code.
- Leaving this unchecked until I see what GHA does, since I can't test the CodeQL workflow locally.
=> CodeQL: only scan `sopel` directory

.github/workflows/codeql.yml
Saves us from burning GHA minutes (4-5 min/run) on CodeQL analysis when no files in the `sopel/` directory were changed.
Should have done this in #2528 but alas, I forgot.
- Whether the CodeQL workflow runs when I open the PR _will be_ the test, lol
- CodeQL workflow doesn't appear on the Checks tab for this PR; seems to have worked 🥳
No, unnecessary Actions runs don't cost the project anything, but since it's so easy to be nice and not waste even free resources on analyzing non-code changes, I think we might as well.
Thought about it, but can't skip the CI pipeline for unrelated changes because those checks are marked as required. They also finish in just a minute or two, vs. the 4-5 minutes (or longer) that CodeQL takes to run.
=> CodeQL: restrict paths on which action should run

pyproject.toml
@Exirel discovered that we have some problems with type analysis on `master` if one has a `packaging` version that is 'too old'.
```
$ mypy --check-untyped-defs sopel
sopel/lifecycle.py:147: error: Unsupported operand types for >= ("tuple[int, ...]" and "None")  [operator]
sopel/lifecycle.py:147: note: Right operand is of type "tuple[int, ...] | None"
```
The above was observed with `packaging==21.3`.
I tried to look in their changelog to see if there was a specific version that fixed the issue we saw, but came up empty-handed. Pinning the lower bound to the latest version is the next best thing to do, and this package has excellent compatibility, so it shouldn't be a problem.
=> Pin `packaging` version

docs/source/plugin.rst, docs/source/plugin/tutorials.rst, docs/source/plugin/tutorials/configuration-and-setup.rst, docs/source/plugin/tutorials/first-plugin.rst, docs/source/plugin/tutorials/playing-with-commands.rst
This starts a new set of tutorials for Plugin Author:
* "Your first plugin" introduce the very concept of a Plugin
* "Playing with your command" talks about commands and triggers
* "Configuration and plugin setup" adds the plugin config section
Combined, they provide a first introduction to Sopel Plugin development. They don't talk about everything, trying to introduce very few notions at the same time.
Further tutorials would be welcome in future release of Sopel.
=> docs: basic tutorials

dev-requirements.txt, pyproject.toml, test/vcr/modules/search/test_example_duck_0.yaml, test/vcr/modules/search/test_example_duck_1.yaml, test/vcr/modules/search/test_example_suggest_0.yaml, test/vcr/modules/search/test_example_suggest_1.yaml, test/vcr/modules/search/test_example_suggest_2.yaml, test/vcr/modules/url/test_example_title_command_0.yaml
This is *probably* the ideal solution to my issues with certain VCR cassettes failing locally, since we were on vcrpy 2.x for quite a long time. The error I saw on my local environment went away after upgrading vcrpy (to 5.x) & urllib3 (to 2.x).
Skipping two whole major versions of vcrpy probably isn't ideal, but I like this solution because:
* No more pinning urllib3 at runtime to make a dev requirement happy
* No more snarky incompatibility warning from pip that types-requests wants urllib3 2.x but we have 1.x (seen in CI logs)
* No more weird BrotliDecoderDecompressStream exceptions in my local environment (which didn't happen in CI)
Note that this commit only updates half a dozen YAML cassettes for two plugins whose tests *failed* after upgrading vcrpy. Working cassettes have been …
=> build, test: upgrade to vcrpy>=5 & refresh broken cassettes

.github/workflows/ci.yml, Makefile, contrib/tox.ini, dev-requirements.txt, docs/source/plugin/test.rst, pyproject.toml, sopel/tests/mocks.py
This changeset adds Python 3.12 support to Sopel, which mostly means some chore updating of version lists. The most notable change is the adjustment of the pinned version of `setuptools` to avoid a [known incompatibility with 3.12](https://github.com/pypa/setuptools/issues/3631).
~At one point it looked like `aiohttp` would be a blocker for this support (as they still have no issued a new release with a compat bugfix :grimacing:), but the problem disappeared between the last check of a Python 3.12 RC against Sopel and the official release. :shrug:~  Edit: nope, `aiohttp` is indeed [a problem](https://github.com/sopel-irc/sopel/actions/runs/6415020971/job/17416271455?pr=2516#step:4:613) (failure in CI associated with the [known upstream …
=> Add Python 3.12 support

sopel/config/core_section.py
Dates like `2023-10-26 - 23:45CDT` look a bit weird, and should be presented as `2023-10-26 - 23:45 CDT`. (The default timezone is still UTC, don't worry.)
- Technically I do get 2 local failures in `make test`, from the `vcrpy` problem that #2519 is meant to fix. CI seems to bypass that, so I should be fine. _\*knocks on wood\*_
While making this, I noticed that Sphinx does not output any of the attribute values. Because of that, we have the same default value defined in three different places. The header line for each attribute _ideally_ would look like a module-level constant, e.g. `name_of_config_attribute = ListAttribute('name_of_config_attribute', default=['list', 'of', 'defaults'])` (and `ListAttribute` there would link to the type, of course). It'd save us having to duplicate …
=> config: space before zone in `default_time_format`'s default

sopel/builtins/calc.py
Error cases weren't covered by the `@plugin.example` tests. Fixed that.
Also declared a few more examples that should appear in the help output, to showcase more of the plugin's capabilities.
Follow-up to https://github.com/sopel-irc/sopel/pull/2503#issuecomment-1676205118.
=> calc: improve help output, test coverage (now 100%)

docs/source/package/tools/calculation.rst, sopel/tools/__init__.py, sopel/tools/calculation.py, test/tools/test_tools_calculation.py
This starts with some tweaks to the docstring data in `tools` (`.. versionadded::` kinda stuff) and `tools.calculation` that I found sitting in a forgotten branch; apparently those smaller tweaks never reached the point of a full PR.
That stalled work's finally done: `sopel/tools/calculation.py` is now fully type-annotated and has 100% test coverage. Along the way I discovered a few API glitches (e.g. incorrectly documented parameter types, missing parameters) and fixed 'em.
I admit some of the test assertions are pretty ugly, but with only one custom exception type it's necessary to make sure that _the right kind_ of `ExpressionEvaluator.Error` is being raised. A future refactoring opportunity, that is (which #2508 already tracks).
The framework for fully exercising `tools.calculation` …
=> tools, tools.calculation: docs/type-hint improvements, API fixes, better test coverage

sopel/plugins/__init__.py, test/test_plugins.py
This changeset adds a check that a plugin file actually exists on disk before it is added to the list of known plugins.
Closes #2269.
- Everything passes except `test_example_roll_4` on 3.8, for which I have filed #2544
=> plugins: avoid crash on broken symlink

Makefile, pyproject.toml
This changeset specifies the [`testpaths`](https://docs.pytest.org/en/stable/reference/reference.html#confval-testpaths) parameter, so that `pytest` will look in more explicit locations during collection if the user did not specify a location (if the user does this, the `testpaths` setting is ignored). In other words, running a bare `pytest` will look specifically at the files the project cares about and nothing else.
This fixes a somewhat obscure race against the filesystem that @dgw unearthed when running the automated checks in parallel. In particular, what we observed is that when `mypy` and `pytest` overlap just right, `pytest` may end up looking at files in `.mypy_cache/` during collection, _after_ they have been deleted, presumably when the cache is being flushed. See error details …
=> test: explicitly specify `testpaths`

sopel/tools/memories.py, test/tools/test_tools_memories.py
Tin. Will resolve #2524.
- Copiously.
Started as a partial, untested fix from my tablet to reserve the PR number. New day, new task list:
Made a copy `m` and added another item to it, verifying that the new item did not appear in the original `d`.
However, the new object `m` is a `dict`, not a `SopelIdentifierMemory`.
Returns the default passed to `.get()`, not `key`'s value.
Returns `None` but **should** raise `KeyError`.
With `'key' in d`, returns `'default'` & adds `'KeY'` to `d` as a regular string, _not_ `Identifier`.
If `d` has `Identifier('thing1')` as a key, and `a_plain_dict` has `'ThinG1'` (a regular string), they will not be merged correctly and `d` will now also have a regular string key called `'ThinG1'`.
Same problem as `d.update(a_plain_dict)`.
Same problem as …
=> memories: test/fix interactions between `SopelIdentifierMemory` ↔ `dict`

sopel/plugin.py
I realized that leaving parameter types in the docstrings of these decorators is a maintenance nightmare waiting to happen. Our docs show the type-hints in the function signatures very nicely now. Putting types in the parameter list too is just redundant.
- I mean there'd better not be any, since I didn't touch code.
- By this I mean I test-built the docs locally. Sphinx still warns about some type annotations/x-refs that it has trouble resolving, but those aren't new (discussed [in #2496](https://github.com/sopel-irc/sopel/pull/2496#issuecomment-1741076230) and variously on IRC).
=> plugin: clean up redundant in-docstring parameter type annotations

docs/source/plugin/privileges.rst, sopel/plugin.py, sopel/privileges.py, sopel/tools/target.py
Rather than [have someone open an issue](https://github.com/sopel-irc/sopel/issues/2538#issuecomment-1788027761), I decided to Just Do It. I realized that the time to change how these constants are defined/accessed is _now_, as they've been moved to a new location but the new location hasn't appeared in a release yet. After we release 8.0, it would be that much more painful to change this a second time.
**I'm open to bikeshedding on the class name here.** If nothing else, maybe it should be plural to match `sopel.formatting.colors`. I'm keeping in mind the fact that we keep thinking about better access controls on bot functions, and other stuff that might also logically have constants living in `sopel.privileges`. `AccessLevel` is perhaps not the most future-proof choice for avoiding …
=> privileges, plugin, tools.target, docs: channel privileges as IntFlag

docs/source/conf.py, docs/source/configuration.rst, docs/source/plugin/anatomy.rst, sopel/bot.py, sopel/config/core_section.py, sopel/coretasks.py, sopel/plugin.py
Maybe still not perfect, but there's at least a way to find out what might make a callable "blockable" (and necessitate using `unblockable` to change that), and how to bypass something that you don't want to be blocked getting blocked.
We do still need proper documentation on how to use built-in commands from `coretasks`, but I don't particularly want to link the migrated wiki page at https://sopel.chat/usage/ignoring-people/ here.
That old stuff will continue getting folded into the Sphinx docs over time. Arguably, describing the `.blocks` command in `configuration.rst` is already enough to mark the old website page for removal as part of sopel-irc/sopel.chat#45.
- Didn't run these, as I'm not touching code.
- Many iterations of reviewing the rendered docs…
=> coretasks, docs: fix auto-saving `.blocks add host`; improve "Ignoring Users" docs & x-refs

sopel/bot.py, sopel/builtins/find.py, sopel/builtins/translate.py, sopel/builtins/url.py, sopel/irc/__init__.py, test/test_coretasks.py, test/test_irc.py
Here is a shortcut way of getting a new `SopelIdentifierMemory` with the `identifier_factory` kwarg filled in for you so it automatically uses the bot's awareness of casemapping from the IRC server's ISUPPORT tokens.
Manual casemapping selection is still possible by using the `SopelIdentifierMemory` constructor directly, of course, as before.
Using this new method in the bot to initialize its `users` and `channels` automatically adds this to test coverage:
_(NB: That is an older coverage run, from before I expanded the docstring.)_
=> irc, bot, builtins: add & use `AbstractBot.make_identifier_memory()` helper

sopel/plugin.py
This will flag any use of unrecognized values for the callable priority. It makes a good intermediate step between the current free-form `str` accepted and probably turning it into an `Enum` later.
- Indeed, if I change one of the `priority` decorators in core to an unlisted value, `mypy` raises an error 👍
=> plugin: type-hint `priority` argument as `Literal[]`

docs/source/conf.py, docs/source/configuration.rst, docs/source/index.rst, docs/source/package/config.rst, docs/source/package/config/core_section.rst, docs/source/package/irc.rst, docs/source/package/plugins.rst, docs/source/package/tools.rst, docs/source/tests.rst, sopel/plugins/rules.py, sopel/tools/__init__.py, sopel/tools/memories.py
I set out to clean up some of the documentation appearance & make things more usable, taking into consideration the fact that we use the Furo theme now and detailed in-page TOCs are kinda redundant in a lot of places thanks to the dual sidebars.
In addition to the original impetus for this patch—`maxdepth` or `titlesonly` options on TOCs where needed—this patch also cleans up some warnings generated by `SopelIdentifierMemory` inheriting docstrings from `dict`, tells autodoc not to evaluate function argument defaults before display (eliminates `<class 'sopel.foo.nonsense.ClassName'>` from being shown, which is very ugly), and also improves the docstring of `tools.get_sendable_message()` because I don't want to open a tiny PR for that.
I'm also aware of what #2533 plans to change, and …
=> docs: set `maxdepth` or `titlesonly` on overly-long TOCs

sopel/coretasks.py, test/coretasks/test_coretasks_sasl.py
Fix #2560, now separate and with test (verified to fail without patch)
=> coretasks: fix SASL EXTERNAL without password set

sopel/builtins/wikipedia.py
Closes #2573.
This changeset corrects errant usage of `urllib.parse.urlparse()` in the `wikipedia` plugin, fixing a regression introduced by #2414. This fix prevents namespaces from being erroneously discarded.
In the process of this fix, I discovered that the `Special:*` namespace is a special case as far as the MediaWiki API is concerned, queries to the API for pages in this namespace don't do what you might expect, so these pages cannot be located and turned into snippets for IRC. So, instead, the URL rule ignores these pages, and issues a specific explanation if a user tries to query them using a command.
=> wikipedia: fix urlparse usage & handle Special: namespace

sopel/plugin.py, test/test_plugin.py
If the bot needs a channel privilege for a given callable, it probably wants to do something related to channel operations, and triggering such a callable in response to a private message makes no sense.
Sorry about trying to add something into 8.0.0 this late… I've been writing the 8.0 migration guide tonight, and when I ran across #2405 I realized that #2399 should have contemplated doing this too. If we're gonna "breaking change" privilege-decorator stuff, we should do it _all_ in one major version.
If others agree that this is a good idea we can just merge the patch that's already ready to go and get on with finishing the release. (That's why I didn't open an issue first, to shorten the discuss -> implement -> review cycle.)
=> plugin: `require_bot_privilege()` implies `require_chanmsg()`

sopel/plugin.py, sopel/plugins/capabilities.py, test/test_plugin.py
When Sopel is started with loglevel DEBUG, it currently outputs a stack of lines like this:
```
sopel.plugins.capabilities DEBUG   : Capability Request registered: <sopel.plugin.capability object at 0x7f77903c7cd0>
```
The str(cap_req) gives no useful information. This PR adds `capability.__str__()` so it does:
```
sopel.plugins.capabilities DEBUG   : Capability Request registered: <capability 'message-tags'>
sopel.plugins.capabilities DEBUG   : Capability Request registered: <capability 'account-notify' (_handle_account_and_extjoin_capabilities())>
```
Open to format opinions.
Also, given the format, should this `__str__()` and that for Rule and Command be `__repr__()`?
=> plugin: add capability.__str__ for better logs

sopel/bot.py
That decorator is the only thing wot *might* actually get people to notice that they're still using a deprecated feature…
~~Carelessly left out of #2121, somehow.~~ Actually was included in #2121 but reverted in #2156 due to log spam. But it's not so important that it needs to go in 8.0.0, either.
=> bot: properly deprecate `search_url_callbacks()` method

sopel/builtins/tell.py
This changeset is an alternative to #2582 that transforms the `tellee` as early as possible.
The use of `lstrip("@")` in this patch means that an arbitrary number of prefixing `@`s will be removed, so that `@@Someone` is transformed into `Someone` where it would previously have been transformed to `@Someone`, but since this is an edge case to begin with, I don't think it's any problem.
Longer term, we'd like to have better awareness of if `tellee` is a valid nick or not. I've filed #2583 for this purpose.
=> tell: avoid errors produced by empty tellee

sopel/builtins/adminchannel.py
- `.tmask get` shows the current topic mask
- `.tmask` without arguments assumes the `get` subcommand
- `.tmask set` now sets the topic mask, and provides a usage hint if called without further arguments
- `.tmask clear` is added to explicitly clear the topic mask
In combination, the above should be sufficient to resolve #2596.
If no one minds adding this to 8.0.0 while the release notes are still under peer review, I'm happy to get it shipped sooner.
_(Because it's modifying command behavior, if we don't ship this patch in 8.0.0, I believe the semver-appropriate thing to do would be to ship the first commit in 8.0.1 and hold the second for 8.1.0.)_
=> adminchannel: rework topic-mask commands

NEWS
Since I only wanted to work on this if I could do a whole page of 25 PRs in one sitting, it sometimes took over a week between sessions. So here we are in March despite me starting on this in earnest two months ago.
I don't know how far along @SnoopJ has gotten with putting feedback on sopel-irc/sopel.chat#46 but this and that should probably be reviewed somewhat together. The changelog (this) summarizes the highlights, and the upgrade guide (that) gives all the details with suggested replacements for deprecated/removed features.
This **will** be a lesson for future changelogs, and we're going to have an `8.1-NEWS`, `9.0-NEWS`, etc. branch for the next releases. I've learned that the way we did it for 7.0.0 was Good, Actually!
And yes, I am very very tempted to add this PR itself to the …
=> 8.0.0 changelog

.github/workflows/ci.yml, .github/workflows/codeql.yml, .github/workflows/pypi.yml
Both `actions/checkout` and `actions/setup-python` were using deprecated Node runtimes and generating warnings in our CI logs. Oh, and they'd also eventually stop working entirely when the deprecated runtime is removed. That's probably the best reason to update them.
I also discovered that there is no `v1` tag for `pypa/gh-action-pypi-publish`, so our existing `pypi.yml` workflow from #2328 wouldn't ever work. Because tags can be easily changed if a malicious someone gains access to the action's repository, the release action is pinned to a specific, verified, commit's SHA.
- This will be handled for the `ci.yml` workflow by PR checks, and if the checkout & setup-python actions work there we can assume the same new versions will also work in the `pypi.yml` workflow.
- I can't really test …
=> GHA: Update/fix actions

dev-requirements.txt, pyproject.toml, sopel/tools/__init__.py, sopel/tools/memories.py
`types-pkg-resources` was yanked, which I discovered when submitting #2613. `pkg_resources` itself is typed in setuptools>=71.1, negating the need to install type stubs.
When testing that fix, I updated `mypy` and friends (`pip install -U -r dev-requirements.txt`) and found a few more new type-check errors caught by the newer tools:
- `SopelIdentifierMemory.update()`'s signature isn't compatible with its supertype (fixed by adding `typing_extensions.override` decorator; can't go stdlib-only until py3.12…)
- `tools.OutputRedirect` calls methods on `sys.__stdout__` and `sys.__stderr__`, which are allowed to be `None` and therefore have to be guarded with `if`s (I'm glad this class is deprecated)
All of this needs backporting to the `8.0.x` maintenance branch, which is why this has the 8.0.1 …
=> Miscellaneous type-checking updates

.github/workflows/ci.yml, contrib/tox.ini, pyproject.toml, sopel/builtins/dice.py, sopel/builtins/url.py
- ci: Added Python 3.13 to CI workflow
- contrib: Added Python 3.13 envs to tox config
- dice: removed unnecessary `count` parameter to `re.sub()` and pass `flags` as a kwarg
(py3.13 deprecates these as positional args)
- url: fix type-check error with `dnspython` 2.7
Use `Rdata.to_text()` to get each result as a string, which is one of the types that `ipaddress.ip_address()` accepts.
- meta: add Python 3.13 classifier for PyPI releases of 8.1+
With the above changes, the only warning emitted during `pytest` runs under Python 3.13 is from SQLAlchemy, which isn't new; it's because we haven't fully migrated to their 2.0 style yet, and not related to which Python version is used.
The type-check error from `dnspython` 2.7 isn't strictly Python 3.13-related, but this patch wouldn't pass …
=> ci, contrib, dice, meta: enable testing on Python 3.13 + fix warnings

sopel/config/types.py
This should make debugging a bad configuration easier, especially if the value is read from an environment variable.
It should also help with figuring out weird errors related to invisible characters in the configuration file, but that's not the primary motivation here.
=> config.types.ChoiceAttribute: log the invalid value if validation fails

pyproject.toml, sopel/builtins/url.py, test/builtins/test_builtins_url.py
Atop #2282
Fixes #2284
Draft implementation should resolve #2348.
=> url: improve private IP protection

sopel/builtins/find.py, test/builtins/test_builtins_find.py
Allowing `\|` or `\/` is all well and good, but if one can't escape the escape character, things get very confusing! So let's make it possible to escape `\` itself as `\\`.
With the test scaffolding now written (OK, much of it stolen from the preexisting `test/builtins/test_builtins_isup.py`), it'll be easier to add more cases (edge or otherwise) as we think of them.
Early 8.0.x bugfix candidate, unless someone else feels strongly about including it in 8.0.0. Feels late in the game to add One More Thing into that milestone…
=> find: support escaping backslash, fix double-bolding, and add basic tests

dev-requirements.txt
Tin. CI fails at the moment, and it would be nice if it kept working.
I have started a `mypy-1.12` branch to work on the broken things. but it'll require some coordination with #2616 and #2629.
=> Pin `mypy` to 1.11.2

Makefile, sopel/bot.py, sopel/builtins/calc.py, sopel/builtins/dice.py, sopel/builtins/safety.py, sopel/builtins/units.py, sopel/builtins/url.py, sopel/coretasks.py, sopel/db.py, sopel/irc/__init__.py, sopel/irc/backends.py, sopel/irc/modes.py, sopel/lifecycle.py, sopel/plugins/handlers.py, sopel/plugins/rules.py, sopel/tools/calculation.py, sopel/tools/identifiers.py, sopel/tools/memories.py
Tin, with the necessary type definition fix. Related to #2603 for Sopel 8.0.1.
Note: I used `Any` in several places, in particular in `sopel.tools.identifiers`. I'm not really happy about it. However, the best fix is to properly type annotate instances, i.e. doing something like `users: dict[str, User] = SopelIdentifierMemory()` as it should properly type check the `users` sopel memory object.
=> mypy: add --disallow-incomplete-defs option

sopel/tests/pytest_plugin.py
_This patch feels almost too simple to work, but it does._
For quite a while, we've had three tests from the `rand` plugin that take several seconds each. I had a Sopelunk with the Git version of [`pytest-profiling`](https://github.com/man-group/pytest-plugins/tree/master/pytest-profiling) (because they haven't released in about 5 years and the last package is broken on modern Pythons) and discovered that about 98% of the time spent on the five tests selected by `pytest -k rand.py` was in `time.sleep()`.
Drilling down, I saw that was being called from `bot.say()`, which led pretty quickly to the real culprit: Flood protection.
There's no server to flood during tests, so we can just turn that protection off. With this change, those five tests from `rand` went from ~12 seconds on my test …
=> pytest_plugin: disable flood protection for example tests

sopel/plugins/handlers.py, test/plugins/test_plugins_handlers.py
This fixes submodule search locations for `PyFilePlugin`s, checks whether the module spec is valid _before_ adding it to `sys.modules` (instead of checking after), and adds a regression test for the submodule search location fix.
Fixing `submodule_search_locations` resolves #2619.
=> plugins.handlers: fix some PyFilePlugin logic errors

docs/source/plugin/advanced.rst, sopel/plugin.py
How to do this was discussed fairly well in #1222 a while ago, and I just cribbed an example from there.
I also found an apparently obsolete note about using `sched` with `@plugin.rate` and friends while poking around the topic of scheduled callables, because I tested what it said and found that the caveat no longer applies (see #825).
Along the way I also briefly considered giving the `bot` a `schedule` instance that it provides to plugins, but I'm not ready to commit to that kind of API addition yet. Putting this into the tips & tricks section is better than pointing to a random issue comment on the occasions when "how do I schedule a function at a specific time?" comes up, and it doesn't preclude API additions at a later time if we come up with a sane decorator interface for it.
=> docs: add advanced tip about scheduling function calls

sopel/bot.py, sopel/plugins/rules.py, test/plugins/test_plugins_rules.py, test/test_bot.py
Fix #2627 by checking if the rate limit is actually set (equal or less than 0s).
I decided to make the `at_time` parameter mandatory, as it's all internal stuffs and it makes it clearer what time we are comparing it to. That's how I figured out that it was about the repeating call to the same rule for a single trigger: it would check against the same trigger object, but compare it to the latest call to `now()`. That's why the bug was visible on `url` rules, and it affected `find` rules as well.
=> bot, rules: fix rate limiting rules without a rate limit

sopel/cli/plugins.py
There are definitely more improvements I'd like to make in the `sopel-plugins` CLI (e.g. #2459), but this one is simple enough to ship with a patch release.
Several times, I've wished that it was possible to see which version of a plugin Sopel sees without starting the bot to use the `.version pluginname` command on IRC.
=> cli.plugins: include version number in `sopel-plugins show`

sopel/plugins/handlers.py, test/plugins/test_plugins_handlers.py
Fixes #2593.
This changeset swallows all exceptions when trying to determine the version of an `EntryPointPlugin`, as there are more failure cases than what catching `ValueError` specifically covers, and allowing those exceptions to propagate breaks plugin reloading.
- `1388 passed, 8 xfailed, 1 warning in 45.44s`
=> Fix version check for entrypoint plugins with unequal project/package names

sopel/irc/__init__.py
This takes care of #2602 as far as what directly prompted me to slot it into the 8.0.1 milestone, with new `versionadded` annotations in the docstrings of stuff that's new-ish (added in 7.x or later). I figure after this PR, that issue can become a general checklist of which submodules have been looked at again since 8.0.0 and live un-milestoned for a while.
Maybe we should also have a tracking issue for the second half of this PR, which starts the process of something we talked about in other patches: Replacing use of `typing.Optional` with `| None`. Right now I think "just migrate the files you touch" is better than a "touch ALL the things!" PR, but we still should keep track of what's been done.
- Ran `make lint` only locally, as no runtime code is touched
=> irc: `versionadded` notes + `Optional` annotation migration

pyproject.toml
<Sopel> [update] A new Sopel version, 8.0.1, is available; I am running 8.0.0. Please update me.
=> Update master's version metadata

dev-requirements.txt, sopel/tools/time.py, sopel/trigger.py
I had the itch to work on a feature for 8.1, but noticed that unrelated tests were failing when I started validating my changes…
`urllib3` 2.3.0, released 22 December 2024, broke compatibility with `vcrpy` 5.x by using a `response.version_string` attribute that's missing from the mocked-up response objects. ([The diff](https://github.com/urllib3/urllib3/commit/f9d37add7983d441b151146db447318dff4186c9) looks pretty innocuous, but every change has the potential to [break _someone's_ workflow](https://xkcd.com/1172/), right?.)
Upstream has fixed this for vcrpy 7.x, but we're on an old fork of vcrpy 5.x due to incompatibilities with mixed `urllib` versions across older versions of Python (see #2456).
I'll add a note to #2456 with an update on the current state of this. We can remove the pin …
=> build: pin urllib3<2.3 to accommodate our old fork of vcrpy

sopel/builtins/url.py, test/builtins/test_builtins_url.py
This is a possible resolution for #2649.
Maybe there's a better way to do this—maybe it would be better to just use `AccessLevel._member_names_` directly—but suggesting an alternative approach when appropriate is what code review's for, right?
The commits are separated out so it'll be easy to bring whatever is useful (especially the new test case) over to a new approach if someone has a better idea.
- mypy and pytest pass; only flake8 complains a little (fixed by #2647).
Defining these shortcut constants from `sopel.plugin` (below) in `sopel.privileges` instead could be useful:
https://github.com/sopel-irc/sopel/blob/99c4a0036d208ac9343c145f1f003122e8fec410/sopel/plugin.py#L26-L34
I do wonder if we should in fact make `sopel.privileges.__all__` export the list of privilege names, and keep …
=> privileges, url: fix privilege check in `.urlban` command family

sopel/builtins/safety.py, test/builtins/test_builtins_safety.py
Fixes #2644, or at least makes it not an uncaught exception.
=> safety: fix safeify_url() exception on python 3.11

sopel/bot.py, test/test_bot.py
This makes rate limit feedback from the bot more readable. Fixes #2651.
=> bot: round rate limit `time_left` value up, eliminate microseconds

.github/workflows/ci.yml, NEWS, dev-requirements.txt, sopel/bot.py, sopel/builtins/safety.py, sopel/builtins/url.py, sopel/tools/time.py, sopel/trigger.py, test/builtins/test_builtins_safety.py, test/builtins/test_builtins_url.py, test/test_bot.py
Trying out a new workflow: I've merged the changelog and backport branches for 8.0.2 into this PR, which will both run CI on the final result and allow other maintainers to give the overall patch a once-over before it gets merged for final release.
If we like doing things this way, we can use it for 8.1.0—and create (an) appropriate label(s) in the tracker for this type of PR.
=> Release prep: 8.0.2

.github/workflows/ci.yml, dev-requirements.txt
We aren't using the `v` prefix for maintenance branches. What we have are names like `7.1.x`, `8.0.x`, etc. and CI hasn't been running for 8.0 series maintenance patches like it should.
I already proposed this in the 8.0.2 release-prep PR (#2654), but it needs to be in the master branch too so future maintenance branches will get the new patterns automatically.
=> ci: make `v` prefix optional in maintenance branch names

sopel/bot.py, sopel/builtins/url.py, sopel/coretasks.py
Both `coretasks` and `url` used `bot.search_url_callbacks`, that was deprecated some time ago and wants to emit warning in Sopel 8.1. Because it was used, we didn't bump Sopel's version to 8.1.0.dev0 yet, and that was annoying.
Therefore, I replaced that by a direct access to the private attribute `_url_callbacks`, and then bumped to Sopel 8.1.0.dev0. And by the way, we should be able to remove `bot.call` in Sopel 9.
Thank you for your service, `register_url_callback`, but I can't wait to remove you and your sister methods!
=> sopel: don't use bot.search_url_callbacks internally

sopel/plugins/handlers.py
There is a type safety issue in `sopel/plugins/handlers.py` where `entry_point.dist` could be None. In theory, this never happens because we checked if it has the `name` attribute, but that doesn't convince mypy that we are doing things right.
The solution is rather straightforward: properly annotate the entry point and check that its `dist` attribute isn't `None`, and voilà! The condition check is simpler and mypy is happy too, everyone win!
=> plugins: fix type safety issue on EntryPoint's dist attribute

sopel/bot.py, sopel/plugins/handlers.py
Related to #2425 (first two tasks).
Both methods to add/remove plugins rely on values direct from `loader.clean_module`, which is inconvenient at time. In order to rework smoothly this interface, these methods are now deprecated and they will be removed in Sopel 9.0.
We still need methods to record the plugin handler to the plugin name in `bot.plugins`, but they don't do more than that. Everything else is now directly handled and controlled by the plugin handler.
For good measure, I've fully type check `sopel.plugins.handlers`. This will create merge conflict with #2634 and I'm sorry about that, yet it was too good an opportunity to miss it.
=> bot, plugins: deprecate bot.{add|remove}_plugin

dev-requirements.txt
flake8-import-order 0.19.0, released earlier this week, drops support for Python 3.7 & 3.8.
It also adds some new ordering & whitespace checks we need to fix in our code before upgrading, too.
_This PR is to fix a CI failure, and is therefore intentionally submitted without running the checks locally first._
=> dev: cap `flake8-import-order` to avoid bugs & Python 3.8 deprecation

sopel/builtins/lmgtfy.py
As reported on IRC, `lmgtfy.com` no longer works. It redirects to `lmgtfy.app`, whose TLS certificate expired in 2023.
Using the archived copy at `lmgtfy2.com` works.
- ~~I've done this patch in the web editor, so I haven't run the checks myself. It's trivial though, should be OK. I'll just let GHA run the checks after the PR is opened.~~
- Successfully passed `make qa` locally on 2025-06-11
- ~~Similar to the above, I will ask the original reporter to test this solution as I'm on my tablet/GH web.~~
- The original reporter did not get back to me. Manually tested myself and found working as of 2025-06-11
=> lmgtfy: switch domain to a working archive

Makefile
I had too many garbage files accumulating in `build/` and `**/__pycache__` from various virtual environments, packaging tests, etc. Figured these cleanups could be useful to anyone else hacking on the code, not just me.
(Submitting them in a PR also gives an opportunity for our other Make enthusiast(s) to weigh in.)
=> Makefile: add cleanup recipes

sopel/bot.py, sopel/plugin.py, sopel/plugins/rules.py, test/plugins/test_plugins_rules.py, test/test_bot.py
Implementation of my own idea from #2435, an optional `include_admins` kwarg to `@plugin.rate` and related decorators.
With #2647 settled, I can now open this and (hopefully) not run into any unrelated CI fails.
- It passed locally when I was working on the patch. Haven't rerun things on top of the current `master` branch, but the lazy way is letting CI do it for me.
=> bot, plugin, plugin.rules: optionally include admins in rate limits too

sopel/bot.py, sopel/config/core_section.py, sopel/coretasks.py, test/bot/test_bot_blocking.py
What it says on the tin. Sub-task of #1355, closes #2686.
**[Tests added July 5]** _Previous status:_ Beginning in draft status; while the current test suite passes, I haven't yet gone through the test cases to add any specific checks that might be warranted for this new feature. So far, I've only (…almost) proved that it doesn't break any existing behavior.
=> bot, coretasks, config: add `hostmask` block type

Makefile, pyproject.toml
Tin. I can think of no reason not to apply these command-line flags even if the user runs `mypy` directly/manually. We should have done this sooner in `setup.cfg`, before #2682, but alas.
- Better not break `make test` since I didn't touch any Python… But yes, I checked `make lint`.
- As above.
Will cause further merge conflict with #2362—but between the existing conflicts, open review comments to be addressed, and how long it's been… That one's gonna need a rebase to test it out properly, anyway, if work on it continues.
=> Move mypy options from Makefile to pyproject.toml

sopel/coretasks.py, test/test_coretasks.py
Tin. Fixes #2675.
Also explicitly tests the `0` placeholder for missing account name in WHOX (regular WHO doesn't send that). We do not request the other fields that could have placeholders (`ip` and `oplevel`) in WHOX.
Yes, possibly the test assertions are a bit overkill. `assert`ing is cheap, and I would like to be extra sure.
=> coretasks: handle '*' placeholder for omitted channel in WHO/WHOX RPLs

sopel/builtins/version.py
Tin and personal wish fulfillment. With this changeset, the `version` command will report commit information if Sopel is running from a [`git-worktree`](https://git-scm.com/docs/git-worktree).
The current revision of the `version` plugin only supports reading commit information when the host Sopel is running inside of a 'real' git repository. I find it convenient to run Sopel from a worktree for a "near to development" copy, and it's nice to still have the commit information in this use-case.
- I did see some errors when running `mypy` because `types-urllib3` was not installed. I'm not sure if that's missing from `dev-requirements.txt` or if my local environment was in a weird state.
- Also saw some test failures in `test_example_suggest_*` caused by content decoding errors. I only …
=> version: retrieve commit hash for git worktrees

sopel/cli/config.py
Opens the specified config file in the user's `$EDITOR`, obeying any environment variables like `$SOPEL_CONFIG_DIR`, as a convenience.
- Note: I'm not up for creating a whole `test_cli_config.py` suite from scratch for this. I verified that both error cases (empty/unset `$EDITOR` envvar, and nonexistent config file) are caught, and of course that the normal case opens an editor as intended.
=> cli: add `sopel-config edit` subcommand

sopel/builtins/admin.py, sopel/coretasks.py, test/builtins/test_builtins_admin.py, test/test_coretasks.py
Sopel now requests the `invite-notify` CAP. I couldn't think of anything useful for it to do with the notifications, except to log them like other channel events are, at the INFO level. A test case added for `coretasks` checks the expected log message.
The `admin` plugin's `invite_join` handler now ignores `INVITE`s not targeted at the bot. A new `builtins/test_builtins_admin.py` test suite validates its invite-handling behavior. Of the four test cases, `test_invite_accept_not_us` was the only one not already passing prior to patching the plugin.
Progresses #971.
Discovering some other old branches that I'd never created PRs for got me thinking, and I looked in the Branches list for other things that I might've forgotten about. This was one of them. Then I realized that `admin` would be …
=> Support `invite-notify` CAP
