willie/modules/youtube.py

Compare: 
python 2: 
[YT Search] Title: Test Brytyjskich Ciast | Uploader: paei100 | **Duration: 9mins 6secs** | Uploaded: 05/01/2015, 17:49 | Views: 109,733 | Link: http://youtu.be/p9a0LgQv_Gw
python 3:
[YT Search] Title: Test Brytyjskich Ciast | Uploader: paei100 | **Duration: 0.15166666666666667hours 6secs** | Uploaded: 05/01/2015, 17:49 | Views: 109,733 | Link: http://youtu.be/p9a0LgQv_Gw
This is caused by python 3 assuming float division even when both operands are integer. Changing the division to be explicitly integer fixes the issue.

[youtube] Fixed video duration format when running on python3

---

willie/modules/youtube.py

This is identical to PR #703, but the fix is in the master branch as opposed to 4.6.

[youtube] Fixed video duration format when running on python3 in 5.0

---

willie/modules/youtube.py

in python 3, the / operator can take two integers and produce a float.
This leads to things like "Duration: 0.025833333333333333hours 33secs"
// is always integer division, in both python2 and python3

use integer division for python 3 compatibility

---

willie/modules/admin.py

I added a feature to auto-accept invites and a config option to control it!

Added auto-accept invite feature and config option.

---

willie/modules/clock.py

When you would set your time format, it would give an example response like
```
<maxpowa> .settf %F %r (%Z)
<Inumuta> maxpowa: Got it. Your time will now appear as 2015-01-25 12:04:35 AM (). (If the timezone is wrong, you might try the settz command)
```
instead of using your previously set time zone like
```
<maxpowa> .settf %F %r (%Z)
<Inumuta> maxpowa: Got it. Your time will now appear as 2015-01-25 04:05:38 PM (PST). (If the timezone is wrong, you might try the settz command)
```

[clock] Fix unclear message when using .settf

---

willie/modules/safety.py

The isop attribute has been removed from Trigger and thus issuing
```.safety on/off``` would cause an AttributeError.

safety: Fix channel operator check

---

willie/modules/clock.py

Also fixed the consistency between some commands, like .setchanneltz instead of just .channeltz. Fixed incorrect examples, as commands were not defined for given examples. Made commands follow somewhat of a general format instead of somewhat random names.

[clock] Add getter commands for tz and format

---

willie/modules/chanlogs.py

This adds an option to use the clock module's timezone for storing logs.
I'm not sure if this is done properly as I'm not very well versed in Python, but I figured I'd give it a shot since everybody in my channel is in America/Los_Angeles and was complaining about logs being split in the middle of when we tend to be active. It appears to work properly, when pytz is installed, and falls back to the old behaviour when it isn't.

Add the option to use the bot's preferred timezone for logs.

---

willie/trigger.py

CTCP messages that are just single word messages weren't properly being converted into intents, because the current system was expecting a following section. Some CTCP messages (TIME, USERINFO) wouldn't usually be sent with trailing information, causing the old regex to miss converting them into intents.

[trigger] Fix CTCP -> IRCv3 Intent conversion

---

willie/modules/chanlogs.py

Fix for a possible bug involving logging of unicode characters to ascii text files.

Write unicode to ascii log file

---

willie/modules/weather.py

This alters the response of the .weather command so that it includes the time of the weather report.  A typical response intro will change from "Yahoo! Weather - Austin, TX:" to "Austin, TX at 11:50 pm CST:", which seems nicer and more useful to me.
This also reverses all the arrows displayed for wind direction.  Currently, for example, 337.5 - 22.5 degrees is represented by an up arrow, suggesting motion towards the north, but those numbers mean that the wind is coming *from* the north.

Weather tweaks: include time in response, reverse wind direction arrows

---

willie/modules/seen.py

This is an update to the ".seen" feature.
The old behavior is /me actions (CTCP ACTIONs) would be saved in the .seen feature and re-shown as the user saying something:
9:42:26 AM  * jnmtx hehe 
9:42:28 AM  @jnmtx  .seen jnmtx 
9:42:29 AM  jwbot  jnmtx: I last saw jnmtx at 2015-05-19 - 14:42:25 in here, saying hehe 
The new behavior makes .seen replies for CTCP ACTIONs say "doing nick message", but leaves .seen replies for PRIVMSG to channel the same ("saying message"):
9:49:45 AM  * jm hehe 
9:49:48 AM  @jnmtx  .seen jm 
9:49:48 AM  jwbot  jnmtx: I last saw jm at 2015-05-19 - 14:49:44 in here, doing jm hehe 
9:50:06 AM  jm  what's up? 
9:50:11 AM@jnmtx  .seen jm 
9:50:11 AM  jwbot  jnmtx: I last saw jm at 2015-05-19 - 14:50:05 in here, saying what's up? 
That's it.
Thank you for …

make .seen replies for CTCP ACTIONs say "doing nick message"

---

willie/modules/clock.py

When a user sets a new time format for him/her/theirself, the bot validates it and tests it before saving. Do the same for new channel time formats.

[clock] Test setctf same as settf

---

sopel/modules/adminchannel.py

[adminchannel] Fix .kick & .kickban
1. .kick reason was being truncated
2. .kickban didn't work because local var channel was used before assignment

[adminchannel] Fix .kick & .kickban

---

sopel/modules/find.py

Fixes: UnboundLocalError: local variable 'new_phrase' referenced before assignment (file "<sopel_path>/sopel/modules/find.py", line 123, in findandreplace)

Fix UnboundLocalError

---

sopel/loader.py

When populating the functions' doc value, we were incorrectly checking if it started with just `prefix` instead of `help_prefix`. `prefix` is usually regex, so it's better to use `help_prefix`

Ensure help output matches the example correctly

---

sopel/modules/search.py

Issue #885 (https://github.com/sopel-irc/sopel/issues/885) was caused by the fact that the duckgogo query wasn't urlencoded previously which caused the API to return its HTML documentation page instead of a JSON document when the query contained characters that should be urlencoded.
I did a quick fix to the issue by urlencoding the query string with urllib.parse module's quote_plus() in /modules/search.py duck_api function. Now it doesn't crash on queries such as "#" or "100% sugar-free".

A quick fix to issue #885

---

sopel/loader.py

Every function is currently forced unblockable, as the unblockable decorator doesn't allow a boolean value, and the default, when there is no decorator, is True. This PR fixes that behavior by making the default, when there is no decorator, False.

Fix blocking functionality

---

sopel/config/types.py

Should fix coretasks' `.blocks add` command.

Allow ListAttribute to be a list or a set

---

sopel/modules/help.py

Minor tweak, but it makes a ton of difference when you have a lot of modules loaded.

[help.py] Sort output alphabetically by module

---

docs/source/index.rst

To account for the changes in https://github.com/sopel-irc/sopel/commit/1217c40a7549660b26deb9a6858a90f7f11172b6
I added a bit of extra documentation for the reply function too.

[Documentation] Change instances of recipient to destination

---

sopel/modules/safety.py

Configuring the module would previously bomb out with a TypeError because `default` was actually passed as `serialize`.

Fix safety module configuration

---

README.rst

Information regarding having to add config setting for modules removed, due to being the default now: ~/.sopel/modules

Removed unneeded information :bangbang:

---

sopel/modules/isup.py

`'http://'` is 7 characters long, so `site[:6]` can't ever match it. ditto for `'https://'` and `site[:7]`

[isup] fix bad indexes preventing bot from recognizing http protocols

---

sopel/modules/movie.py

it seems the imdb api has been taken down entirely- there is no mention of it on their site and any connections to the site time out. [omdb](http://www.omdbapi.com/) provides the exact same functionality, and i have tested these changes and confirmed them working on my own installation.

update movie.py to use omdbapi as imdbapi is non-functional

---

contrib/rpm/willie.spec.in
requirements.txt
sopel/modules/weather.py

Also cleaned up dict value retrieval a little, the .get() calls were a bit unnecessary.

Resolve #926

---

sopel/config/types.py

Ensures that FilenameAttribute's parse and serialize always have the parameters they need.

Resolve #929

---

README.rst

I have uploaded a `sopel` package into [community], and want to update the installation instructions in README with this PR.
Link to PKGBUILD: https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/sopel
Thanks!

README: Update sopel package location in Arch

---

sopel/modules/ip.py

We should only get `socket.gaierror` if the user passes an invalid IP or hostname, but it could be in the event that we don't have DNS configured on the machine or a multitude of other things, so we can be somewhat vague in the error message.

[ip] Mask socket.gaierror

---

sopel/modules/countdown.py

User input `.countdown 2015 12 25`
Sopel old output `21 days, 7.8805555555555555 hours and 0.0 minutes until 2015 12 25`
Sopel new output `21 days, 7 hours and 34 minutes until 2015 12 25`

[countdown] fix remaining time calculation

---

sopel/modules/wikipedia.py

Should resolve the inconsistencies between the implementation of unquote in python 2 and python 3.

[wikipedia] Properly handle unicode in python 2.7

---

CONTRIBUTING.md
pytest_run.py
sopel/modules/calc.py
sopel/modules/clock.py
sopel/modules/countdown.py
sopel/modules/unicode_info.py
sopel/modules/version.py

Update project website URL in comments for some modules. These were probably missed during the initial change because they were mistyped. 
URL in comments were `http://sopel.dfbta.net` instead of `http://sopel.dftba.net`
Updated to the new URL `http://sopel.chat`

Update project URL in module comments to http://sopel.chat

---

sopel/modules/dice.py

Instead of matching for the literal `d` or `v`, match `[dD]` and `[vV]` appropriately.
Match an optional `-` character before each possible number, and handle negative inputs in the `_roll_dice` method. There was already a check for negative `dice_type`, but because the `-` wasn't being captured, this code wasn't being used. I added a check for `dice_num < 0` (which returns `None`) and `drop < 0` (which ignores the `drop_lowest` value entirely).
Partially addresses #874

[dice] Case insensitivity and better error handling for negative numbers.

---

sopel/bot.py
sopel/coretasks.py
sopel/irc.py
sopel/tools/target.py
sopel/trigger.py

This uses some of the code that @maxpowa wrote for #941, but gives a somewhat more intuitive API. It also paves the way for potentially adding direct support for away-notify and metadata-notify.
Since this being broken could have big security repurcussions (especially since I'd like to be able to make admins/owner pull from account tracking in the future), I'd like a few people to pick this over and see what I've broken before merging it.

Add tracking of users and their accounts

---

sopel/modules/url.py

setup uses it as a list, and in previous versions of sopel it was a list, but in the UrlSection it's defined as a ValidatedAttribute. This was causing each character in the excludes list to be parsed as a regex exclude. Switching to ListAttribute fixes the issue.
Fixes #959

[url] Fix URL excludes loading

---

sopel/modules/currency.py

Took me a bit longer than I said it would, but I remembered to commit this today.

[currency] Make arguments case-insensitive (close #979)

---

sopel/bot.py

Coretasks is only one module, so if you loaded it and only one other, you'd get the "Couldn't load any modules" warning, even though there was a module loaded.

[bot] Fix misleading message

---

sopel/irc.py

_ssl_recv returned empty strings instead of the empty bytes object if
the socket was closed or upon ENOENT.
This lead to exceptions when running sopel with python3 because
asynchat.handle_read expects byte objects.
This commit fixes #937.
Note - b'' is available from python 2.7 onwards. I tested this change with python 3.5.0 and 2.7.10.

Make _ssl_recv always return bytes

---

contrib/README
contrib/sopel.cfg
contrib/sopel.conf
contrib/willie.conf

Fixes #963 
I'm not ready to touch anything in `contrib/rpm` yet, but I don't think that's part of the current issue.

[contrib] rename & edit willie out of contrib

---

sopel/modules/url.py

Trigger rules are case-insensitive regexes, so the auto title responder
will be triggered even for capitalized URLs such as "Http://google.com"
(which can happen, for example, when a mobile device attempts to
auto-capitalize the beginning of a sentence).  Match URLs case
insensitively for title lookup purposes and add error handling in case
no URLs could be extracted from the match.

url: handle capitalized URLs

---

sopel/modules/reddit.py

Previously, the reddit module fetched posts by the full URL of the post.
This led to RedirectExceptions in some cases, for example when someone
links a naked reddit.com URL instead of www.reddit.com.  Instead, match
only the post ID and pass it to get_submission.

reddit: fetch posts by submission_id

---

sopel/modules/xkcd.py

xkcd.py was missing the import for the requests module when it was ported over to requests.
This commit adds that missing import.

Added missing import to xkcd.py

---

sopel/modules/url.py

Depending on the URL, response.iter_content() in Python 2/3 will return either:
- `type 'unicode'`/`class 'str'` (for "plain" HTML)
- `type 'str'`/`class 'bytes'` (for binary streams, like file URLs)
To distinguish between the two situations we're checking if we got string or
bytes, and proceed accordingly.
This also fixes #1021

Make sure we're working with UTF8 string

---

sopel/module.py

It seems there is no `@command` decorator. 
At any rate, examples for `@commands` should use the same (and correct) grammatical number.
I have only looked at docstring for `@commands`, not at other code nor docstrings.

[doc] unify grammatical number of `@commands` example

---

sopel/modules/admin.py

The parse() method only expects one argument, whereas the .set command gives it two. This is my fix for that.

fix .set command for non filename attributes

---

sopel/modules/weather.py

this closes #1050 and closes #1029
Yahoo no longer provides RSS feeds for weather.
bot now uses their most current API instead.

fix weather.py to work with new Yahoo API changes

---

sopel/irc.py
sopel/trigger.py
test/test_trigger.py

The check to pop account from the pretrigger if `account-tag` is not in the enabled capabilities really threw me off.

Implement proper extended-join support

---

sopel/config/core_section.py
sopel/irc.py

Also added core config settings for toggling whether to message the logging channel (if it is set) or to use the original behavior of messaging the sender.
I'm not sure why Sopel automatically messages the sender (as it's a channel most of the time), since it can get pretty disruptive pretty quickly.

Made it so Sopel doesn't automatically message who triggered an error.

---

sopel/modules/announce.py

Closes #1043
Let me know if there would be a more preferred way to do this. I think `reply` is the most appropriate method, but I am not strongly convinced.

[announce] Confirm when all announces have been sent

---

sopel/bot.py
sopel/loader.py
sopel/module.py

Modify the @rate() decorator to support a second and third argument for channel and global rate limits.

Add global and channel rate limits

---

sopel/modules/weather.py

e.g. when the user enters a continent for the location.
Since this seems to be triggered by specifying too general a location, I wrote the error message to cover that case.

[weather] catch empty forecast results

---

sopel/irc.py

This is so that Willie attempts to reconnect when your network goes down, instead of exiting.

Treat error in connect as a disconnect

---

sopel/coretasks.py
sopel/tools/target.py

Note that untracked users and their privileges are currently horribly handled. See #365 and its derivatives.
Technically fixes #1005, but we really should handle untracked users a lot better. See handle_names in coretasks.py
Before: (5 seconds online time)
```
gracefu:sopel gracefu$ python sopel.py -c test.cfg
Could not open CA certificates file. SSL will not work properly.
Welcome to Sopel. Loading modules...
Error loading ipython: No module named IPython (modules/ipython.py:23)
Registered 42 modules,
1 modules failed to load
Connecting to irc.ppy.sh:6667...
Connected.
Traceback (most recent call last):
File "/Users/gracefu/sopel/sopel/bot.py", line 441, in call
exit_code = func(sopel, trigger)
File "/Users/gracefu/sopel/sopel/coretasks.py", line 375, in track_quit …
```

Prevent KeyError when untracked user leaves

---

sopel/modules/seen.py

Saves a DB query, and makes people feel silly at the same time. Two birds, one stone, etc.
Partly motivated by optimization, partly by knowing that e.g. Rizon BotServ bots do this.

[seen] Be a smart-ass if people ask the bot about itself

---

sopel/db.py

As described in #1101, this DB API call will currently remove even a nickname that is the only member of its group, contrary to what the documentation string says. This fixes the problem.

[db] Fix group nick count check in unalias_nick()

---

sopel/coretasks.py

Support different implementation of topic update, RPL_TOPIC appears to only be sent to the user who actually updated the topic.
Resolves #1107

coretasks: tweak topic tracking

---

sopel/modules/meetbot.py
sopel/modules/url.py

The `core.verify_ssl` was not passed to `url.find_title()`, resulting in SSL errors on sites with invalid certs when `verify_ssl = False`
Slight refactor of @psachin's original code for backwards compatibility. Resolves #1113

meetbot/url: fix SSLError

---

sopel/config/core_section.py
sopel/coretasks.py

I added a couple of rows of simple code which add the support for authenticating your Sopel on Quakenet.
Modified files are `core_tasks.py`, and `core_section.py`. The modifications to the code should be simple enough to understand just by looking at them.
Works on my machine™ (`Sopel v. 6.3.1`, installed via pip).

Add support for authentication on Quakenet

---

sopel/modules/bugzilla.py

Although the primary error no longer exist, but the bot shows nothing if
the bugzilla is private. In the logs, I see the error,
WARNING:sopel.modules.bugzilla:Bugzilla error: NotPermitted
This commit should notify about private BZ
Closes-Bug: #1112
Signed-off-by: Sachin Patil <psachin@redhat.com>

Notify if Bugzilla is private

---

sopel/modules/calc.py
sopel/modules/find_updates.py
sopel/modules/url.py
sopel/modules/xkcd.py
sopel/web.py

After realizing I'd left a dead import in calc.py after removing the `.wa` command, I decided to go through and clean up any other imports that didn't appear to be in use any more.
Let me know if I've accidentally bollocksed up a module. I double-checked the imports PyCharm said were unused before actually removing them, but I might have made a mistake.

Lint imports

---

sopel/modules/url.py

Previously, each 512-byte chunk is prone to decoding mishap when a UTF-8 sequence is incomplete. Now we decode all of content at once, ignoring errors.
The old problem appears reliably for pages with many high codepoints:
```
<user> http://www3.nhk.or.jp/news/easy/k10010665021000/k10010665021000.html
<bot-old> [ NEWS WEB EASY|æ±åã¢ã¸ã¢ã§ã¸ã«ç±ã«ãªãäººãå¢ãã ] - www3.nhk.or.jp
```

url: make find_title more robust

---

sopel/trigger.py

The intent_regex in sopel/trigger.py does not separate "intent" from "args" correctly. The way it was there needed to be a blank after "intent" which caused test_ctcp_intent_pretrigger to fail:
```
test/test_trigger.py:118: in test_ctcp_intent_pretrigger
assert pretrigger.tags == {'intent': 'VERSION'}
E   assert {} == {'intent': 'VERSION'}
E     Right contains more items:
E     {u'intent': u'VERSION'}
E     Use -v to get the full diff
```
Fixed it by adding a question mark to the regexp after the blank in order to make the blank optional.

sopel/trigger.py: fix intent_regex

---

sopel/modules/etymology.py

Replace bespoke implementation of unescape() with stdlib tools; fix #1153.
Uses try/except to maintain compatibility with both Py2 and Py3.

[etymology] unescape all known HTML entities

---

sopel/modules/search.py
sopel/web.py

This is a two part fix.
1. Fix in web.py for headers being set as blank if they were set in web.get()
2. Use a common user-agent string for duck_search function only.  
Replacing the Sopel version user-string for all web.get calls via web.py would have been a bit too extreme, in my opinion.

Fix .g giving broken links

---

sopel/modules/url.py

url.find_title() throws ConnectionError when hostname/IPaddress is not
readable thereby fails to read title
Sample error
```
15:11:05 psachin:     https://10.65.177.15
15:11:09 BB-8:        requests.exceptions.ConnectionError: HTTPSConnectionPool(host='10.65.177.15', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7feb41b6a2e8>: Failed to establish a new connection: [Errno 113] No route to host',)) (file "/home/tss/virtualenvs/sopel/lib64/python3.5/site-packages/requests/adapters.py", line 487, in send)
```

Fixes ConnectionError

---

sopel/modules/pronouns.py

Fixes setpronouns error on lack of trigger.group(2), fixes autocomplete of nicks with a space so that it's stripped out automatically, fixes that it will say the wrong username if you request someone else's pronouns.

Fixes for pronouns.py

---

sopel/modules/weather.py

Takes care of #1019 for the weather module. One of my users bumped into this tonight, so I decided to just fix it.

[weather] Use help_prefix in hint text when no location given

---

sopel/modules/safety.py

Should ignore exception when checked URL is wrong eg `https://cnn.com]`
Got this error on Python 3.5.2, master release.
not sure this is good solution though...
```
ValueError: Invalid IPv6 URL
File "sopel/bot.py", line 497, in call
exit_code = func(sopel, trigger)
File "modules/safety.py", line 119, in url_handler
netloc = urlparse(trigger.group(1)).netloc
File "urllib/parse.py", line 295, in urlparse
splitresult = urlsplit(url, scheme, allow_fragments)
File "urllib/parse.py", line 368, in urlsplit
raise ValueError("Invalid IPv6 URL")
```

safety module - catch exception on urllib/parse

---

sopel/modules/help.py

Remove duplicates in help output. They are showing itself after plugin reload/unload... I don't really remember but worth taking care as well ;-)

help module - remove duplicates

---

sopel/bot.py

I don't know if this has been mentioned before, but as it stands it looks like the bot's shutdown methods are overwritten (rather than appended to) each time a module is registered. This patch fixes that!

Fixed correct loading of shutdown methods

---

sopel/modules/help.py

Replace deprecated gist API in help

---

dev-requirements.txt
requirements.txt

IPython 6.0+ requires Python 3.3+, so only install that version if we're using Python 3.3+.
This fixes #1194.

Fix IPython requirement

---

sopel/modules/search.py

Requires importing unquote and some regex changes.
The change I propose in #1210 doesn't fix the UK-en version, but does for us-en :thinking: 
Tested with 3.5, untested with 2.7

fix .g giving broken result

---

sopel/modules/wikipedia.py

Sopel will now say a human-friendly error message when a Wikipedia link pointing to a non-existent article is posted, instead of a cryptic KeyError.
Fixes #1256

[wikipedia] Return friendly error on missing pages

---

sopel/modules/currency.py

This PR fixes #1253.
Should it be possible to set a custom precision? It'd be an easy addition.

currency: limit precision to two decimal places

---

README.rst

PyPI download count information is no longer available, so that badge is patently useless now (it literally shows "no longer available" as the download count).
I understand the sense of whimsy that comes from saying "works: usually" or "ages: 12+" in badges, but at the same time the badge real estate at the top of a README is for practical information that potential contributors/users need to know. I'm also not sure there's any value in bragging about how many stars/forks the project has in the README. That information isn't really relevant on PyPI, where the README gets the most exposure, and is readily available from GitHub's UI for users visiting the project there.

Clean up badges in README

---

pytest_run.py
setup.py
sopel.py
sopel/__init__.py
sopel/config/types.py
sopel/coretasks.py
sopel/formatting.py
sopel/modules/countdown.py
sopel/modules/dice.py
sopel/modules/ipython.py
sopel/modules/lmgtfy.py
sopel/modules/meetbot.py
sopel/modules/movie.py
sopel/modules/spellcheck.py
sopel/modules/translate.py
sopel/modules/unicode_info.py
sopel/modules/units.py
sopel/modules/wikipedia.py
test/test_db.py
test/test_irc.py

`CONTRIBUTING` says Python files should always have a specific set of imports from `__future__` as the first line after the docstring. Some were missing or incomplete; others were surrounded by the wrong amount of whitespace. (These were corrected manually, so omissions are accidental.)

Make __future__ imports consistent

---

sopel/logger.py

Original code logged the unformatted message string. Something like this:
[module] Found error while doing %s
Instead of:
[module] Found error while doing foo
Replacing msg with message fixes this behaviour

logger: format arguments for logging channel messages

---

requirements.txt

Testing with the latest `requests` (2.18.4 as of writing) showed no issues with all the Sopel modules and functions that I was able to try out.
Newer versions of PRAW (which the `reddit.py` module needs) prefer to be installed with more recent versions of `requests`, and I see no reason not to keep up with `requests` releases unless something breaks.

Allow any 2.x version of requests

---

requirements.txt

The new `reddit.py` module (updated in December) will not work with PRAW older than 4.0.0. Sopel must therefore require a compatible version.

Require PRAW >= 4.0.0

---

sopel/config/types.py

Might add an optional parameter to the constructor to disable the filtering in the next minor release, similar to the existing `strip` parameter. Don't really want to unless something breaks though (and if anything does, I'd argue that it should be fixed to not rely on empty ListAttribute parsing to `[""]` instead of `[]`).
Merging this should fix #1032 and also close #1173. It will also make #1052 safer, in theory (not tested yet).

[config.types] Filter ListAttribute empty values

---

sopel/modules/calc.py

tumbolia-two is shared with a number of jenni instances and forks, so it is often over quota for hours at a time. That's inconvenient for users of Sopel, and inconvenient for the development process (because there are tests that rely on the service).
If we run into the same quota issues with our own instance, we can make the URL configurable and provide documentation on setting up your own.

[calc] Switch to Sopel's own tumbolia instance

---

sopel/modules/tell.py

If `open()` fails in Python 2, it throws an `IOError`. This was changed to `OSError` in Python 3.3 (but Sopel requires 3.3+, so this change is strictly to safeguard py2 installs).

tell: Catch py2 IOError in setup()

---

sopel/module.py
sopel/modules/ip.py
sopel/modules/url.py
sopel/test_tools.py

Added monkeypatcher to add properties to setup() functions in modules, so they won't automatically be run by pytest (who thinks they're part of the testing).

Pytest setup shenanigans

---

sopel/modules/units.py

There is a bug in the units module (temp sub-module): the user is allowed to convert temperatures below the absolute 0 Kelvin, which is not physically possible. This small code modification allows to return the correct answer to the conversion only if the result if 0 Kelvin or above and will return an error to the user if the resulting temperature for the conversion is below 0 K.

add physical limit to temperature conversion (units module)

---

sopel/module.py

Takes advantage of pytest's test runner always importing `pytest` to detect whether we're running tests.
Alternative to #1295. Fixes #1294.

module: only inject test functions if testing

---

MANIFEST.in

I'd like to exclude `sopel.test_tools` as well, to have as clean a build as possible at release, but since that module is imported in several places that change will take longer to make and validate.
These files aren't even installed, so why are they included in the sdist?

Prune tests from release distribution

---

MANIFEST.in

I've learned more about Python packaging conventions today, and have been convinced that the potential benefits of including tests in the source distribution outweigh the small additional file size.
Reverts sopel-irc/sopel#1297

Revert "Prune tests from release distribution"

---

requirements.txt

Either pip isn't smart enough to figure out which Python versions a package version is compatible with and pick one it can use, or IPython is packaged in such a way that it breaks pip's smarts.
Whichever it is, Sopel will have to be the smart one and hold both their hands to avoid breaking things.
Resolves #1308
----
Pinging @alanhuang122 for review — did I do it right? :stuck_out_tongue:

Fix IPython requirement for real

---

sopel/config/types.py
test/test_config.py

I spent some time this morning figuring out more of how the tests actually work, and expanding the test suite to cover all attribute types in `sopel.config.types`. It was a fun exercise, with the added benefit of catching any future breakage due to changes in how the config stuff works.
`test_config` is the only test module that uses `unittest`, apparently. Maybe I'll work on that later.

Additional config tests

---

sopel/coretasks.py

Fixes account tracking on some IRCds that support the caps but not the modifiers. I'd like input on this before merging it in as I'm not fully sure why @embolalia had went for sticky caps initially.
Servers that are known not to support sticky caps:
irc.esper.net
irc.hackint.org

coretasks: remove sticky modifier from account capability requests

---

sopel/db.py

I was reading [Sopel's documentation](https://sopel.chat/docs/db.html) when I noticed that an obvious setter function was missing. I checked the source code and noticed that the function exists but it does not have a docstring. I added it (line 210).
I also put one-liner comments on one line on the same module.

Add missing docstring to 'set_channel_value' function

---

sopel/bot.py
sopel/loader.py
sopel/modules/version.py

This PR fixes #1240.
Changes to intents:
- they are now added to _callables for all messages (.*)
- they are now converted to regular expressions, like rules
- they now have more reliable (?) handling in dispatch()

core, loader, version: Fix intent handling and CTCP replies

---

sopel/formatting.py
test/test_formatting.py

I never noticed before that italics weren't a thing already in `sopel.formatting`, but indeed, the only existing options were colors, bold, and underline. I'm glad I decided to go through and make sure the existing test modules cover as much as possible, because that's how I noticed this.

formatting: add italics

---

sopel/web.py

It doesn't matter if tests cover the deprecated methods, because, well, they're deprecated. They'll be removed in Sopel 7, and will never have tests added to them.
Doing this is purely cosmetic of course, and I would probably never use `# pragma: no cover` on real code, but for deprecated stuff that is planned to be removed it's OK.

web: mark deprecated methods for coverage exclude

---

sopel/config/core_section.py
sopel/loader.py

I have a bot named Pangubot, and sometimes people refer to it as just pangu. With this code, it recognizes its name either way.

Add nick alias config option for $nick and $nickname in @rule regex

---

sopel/modules/search.py

Python 2 has really infuriatingly inconsistent handling of Unicode text sometimes… Until #1346 happens, this is how to fix #1345. Also see #949, from which I stole this handy trick.

search: apply Unicode fix for unquote() from wikipedia

---

sopel/modules/wiktionary.py

I only noticed this because someone looked up a word that happened to contain an entity escape sequence… Maybe Sopel needs an `html2text()` function in its library? (Or maybe that would be too much like reinventing the wheel.)

wiktionary: Decode HTML entities

---

sopel/modules/bugzilla.py

If `regex` is never added to the bot's URL callback memory, of course trying to remove it with `del` will throw a KeyError. Just catch the exception, everything's fine.
Fixes #1320 (@Helldembez feel free to confirm)

bugzilla: handle empty domains setting on shutdown

---

sopel/modules/search.py

Bing returning inconsistent results has been the number-one cause of CI failures for the last several months. Basically the only cause, in fact.
Kicking the CI occasionally to re-run a failed job was tolerable, but it's reached a point where seemingly no number of job restarts will get a successful test run out of Bing, so away the tests will go.
Coveralls will probably yell at me because this reduces coverage, but I don't care. I'm tired of seeing red X's on pull requests because of this. (**Edit:** "Coverage increased (+0.2%) to 42.833%"? What?)

search: remove tests that hit Bing

---

sopel/modules/translate.py

When Google decides that a CAPTCHA needs to be solved before using their translation service, the module will break and throw a JSONDecodeError.

[translate] Fail graciously when the API does not respond

---

sopel/loader.py
sopel/module.py

Callable cleanup in loader now always uses help_prefix's default value to replace. The documentation for module.example() reflects this, and I also moved the constructor documentation up to where it would be included in the auto-generated API docs (so the parameters are now visible in the public documentation without reading the code).
This should resolve #1283. I might add sanity checking for `help_prefix` (e.g. checking its length and printing a warning on startup if it's longer than one character), based on feedback from @kwaaak.

loader, module: Fix help_prefix cleanup & example docs

---

sopel/modules/url.py

Continuation of #1317; this time, I've separated out the request from my own `master` branch to my own `tinyurl-rebase` branch so any changes I make to my own master don't pollute my pull requests. (I'm learning a lot from this.)
I've incorporated all suggestions from #1317 into this pull request.
New function `get_tinyurl` in URL module
`title` and `title_auto` can now shorten long URLs using TinyURL. The length of a long URL is definable by the user in the config and is optional; the user can disable this functionality by setting
`shorten_url_length` in the config's `[url]` section to `0` or leaving it out entirely.

url: added optional shortening of long URLs

---

sopel/modules/lmgtfy.py

Google's URL is also always given with `www.` prefix, so include that. It's not like the bot is ever in danger of overflowing the IRC line by sending a link to Google's homepage…

lmgtfy: update URLs to HTTPS

---

sopel/modules/lmgtfy.py

Use `web.quote()` to encode the query so it's safe to use as a GET param.
Will merge-conflict with #1363 because they both touch the same line.

lmgtfy: urlencode query

---

sopel/modules/xkcd.py

Visiting xkcd over HTTP will redirect to HTTPS, but it's better to send users there directly.

xkcd: always use HTTPS for URLs in output

---

sopel/modules/currency.py

The last PR to update this (#1208) actually just stopped using the global variable instead of updating it, so there was an unused value in here.
I came only to move things to HTTPS after checking that the API is available there, but I found a mini-refactor opportunity!

currency: Put API URL where it belongs & use HTTPS

---

sopel/modules/pronouns.py

I don't know how long `pronoun.is` has supported HTTPS, but it's never too soon to default secure.

pronouns: use HTTPS in output links

---

sopel/modules/wikipedia.py

Wikimedia's MediaWiki instances 307-redirect unencrypted API requests to HTTPS anyway, so we aren't saving SSL overhead or anything.

wikipedia: fetch from API over HTTPS

---

sopel/modules/reddit.py

The only place the module outputs links, that I saw.
It's also worth noting, since I'm already touching this code, that as written it will incur two redirects, one from `reddit.com` to `www.reddit.com` and another from `/u/username` to `/user/username`. This might be changed too, since it's only an extra 7 characters in the message to avoid being redirected twice. (That said, it's the user's browser being redirected, not Sopel, so it's not a performance concern.)

reddit: Link to user page with HTTPS

---

sopel/modules/safety.py

HTTPS support for the mirror we've been using is officially listed on their site at time of writing: https://www.malwaredomains.com/?page_id=29

safety: retrieve MalwareDomains list over HTTPS

---

sopel/formatting.py
test/test_formatting.py

It's not very well supported, and it can be unpredictable, but people might find a use for it anyway.
Will require rebasing or manual merge if #1368 is merged (or cause #1368 to require same if merged first).

formatting: add reverse-color support

---

sopel/modules/url.py

Bit weird in its handling of failure when multiple URLs were passed in, admittedly, but figuring out which URL failed would require a refactor.
Fixes #1340.
@antdude what do you think of this solution?

url: Say something on .title command failure

---

sopel/modules/dice.py

Another side note is that i used `SyntaxError` rather than the all-encompassing `Exception`, as some exceptions should be handled different. As far as I know, though, `eval_equation()` only throws `SyntaxError`.
Fixes #1189

dice: invalid dice rolls now gives a more friendly error

---

sopel/__init__.py

I added `SIGINT` to the signal handler in `__init__.py`, which is the signal generated by Ctrl-C.
This fixes #1370 .

fix: ctrl-c now runs shutdown routines

---

sopel/irc.py

After grinding the code for a while, I noticed that the shutdown routines (function `handle_close()`) doesn't run if `socket.error` is thrown.
There is a simple way of reproducing the issue: target Sopel towards an IP address that doesn't host an IRC server. 127.0.0.1 should do fine, as long as you aren't running an IRC server on your system.
Fixes #1378

irc: sopel now runs shutdown routines on connection error

---

sopel/modules/wiktionary.py

Directly addresses sopel-irc/sopel#1177 by adding "Prefix" and "Suffix"
types to parsing loop.

wiktionary: fix inability to look up affixes

---

sopel/modules/tld.py

No arguments makes bot say exception. Argument check prevents this.

tld: add argument check

---

sopel/modules/xkcd.py

For whatever reason Duckduckgo (which is used when it says google_search in this module) does not return results anymore. A quick switch to Bing restores the search function.

xkcd: Change search engine from Duckduckgo to Bing

---

.gitignore

Since the `.coveragerc` configuration file defines `coverage_html_report` as the HTML report folder, we can add it to the `.gitignore` file.
I guess few people use the `coverage html` command line, but since I do it *a lot*, and since it's configured in `.coveragerc`, it's fair enough to add it to the project's `.gitignore` file.

test: add coverage_html_report dir to gitignore

---

sopel/modules/reddit.py

Fix for #1411 
- **Current Fix:** Wildcard subdomain for reddit.com
- **Changes:** sopel/modules/reddit.py --> regexp for url with wildcard subdomain
**Background:**
I think it would be better to have wildcards rather than calling out specific subdomains in the regex. (unless we scope the subdomains to support)
Based on the examples in the issue. I initially preferred to allow 2 char or 3 char length subdomain wildcards as `https?://(?:[a-z0-9]{2}\.|[a-z0-9]{3}\.)?reddit\.com`
Digging further, based on a initial vague subdomain scanning (summary below)
```
park1.reddit.com
glee.reddit.com
devel.reddit.com
edin.reddit.com
divms.reddit.com
eriogerg.reddit.com
gogo0.reddit.com
hofmystery.reddit.com
hq.reddit.com
maoliworld.reddit.com
aniwthoi.reddit.com
portableappz.reddit.com …
```

reddit: match more subdomains

---

sopel/coretasks.py
sopel/tools/target.py

I think I found all the places where `bot.channels` wasn't being updated with privilege info. This should finally resolve #1136, but I would really like another pair of eyes (or three) on this.
Still to do:
- We'll rely on my test instance and early adopters who run Sopel from source on the `master` branch to catch any glaring issues before release.

Fix bot.channels.privileges

---

sopel/modules/search.py

The simple way to deal with #1415.
A rewrite isn't in the cards this late in the release cycle for 6.6.0, so the next best option is to detect when a query is affected by the bug and advise the user to modify it.

search: add contextual warning for 'site:' in DDG query

---

sopel/tools/target.py

In `rename_user()`, in class `Channel`, the nick property of users was not updated on NICK events, but the keys for the dictionary were. This pull request addresses this.
Fixes #1358

target: nick property are now updated properly on NICK events

---

sopel/config/core_section.py

Resolves #1426, and some potential oddities in time handling on fresh Sopel installs.

config: Add default value of 'UTC' to core.default_timezone

---

sopel/modules/reload.py

Force-reload all sub-modules of packages recursively.
I dare say this actually fixes (most of) #1056 after two years. My testing on Python 3.6 has been promising so far, and I've heard good things from @ralienpp in that thread about its effects under Python 2.7.
My fingers remain crossed. But someone else should definitely look at this before it gets merged to make sure I didn't do something dumb. I played with the logic a _lot_ yesterday, and after all those little tweaks I'm kind of fuzzy on what I actually _did_. :rofl:
(Also, note to self: Find that StackOverflow post again and amend the commit to reference it in a code comment somewhere before merging.)

reload: Recurse into packaged modules

---

requirements.txt

pyenchant is broken on newer distributions, and has been unmaintained for quite a while. Since only the spellcheck module needs it, and a rewrite of that module to switch libraries is coming Soon™, we might as
well make Sopel installable in the mean time on systems that can't pull down a working pyenchant build.
See #1452. Alternative to #1453.
Note that this change is intended to make `master` installable, and there is no release planned between now and Sopel 7 (which will include the rewritten spellcheck module and drop pyenchant completely).

Don't require pyenchant on Python 3.7 or above

---

test/test_loader.py

The `sopel.loader` module is responsible for loading Sopel Module (as in, "plugins" for Sopel), so it's quite critical.
So I added unit-tests, and change as few code as possible.
There is one function that I didn't test, because I want to rework it later: `enumerate_modules`. This function does too many things, and relies on too many global or hard-coded variables. This must be changed.
So, for now, here is a good increase in coverage for the project.
---
**Initial description**:
> Hi! It's a WIP and I don't expect it to be merged "as-is". I wanted to dive into Sopel's code, just to give it a try, and found that I could help on the test side of thing.
>
> I think I can do plenty more on the `sopel.loader` module, but I wanted to share this as soon as possible, to see if it would help …

loader: test coverage

---

sopel/bot.py
sopel/irc.py
sopel/tools/__init__.py
test/test_tools.py

When a module wants to send a multi-line message, the `Bot.say` method can be used with a `max_messages` parameter to do so. The low-level `write` method on the other hand, will truncate and discard the excess no matter what.
In both case, we must not truncate unicode character composed of 2 bytes in half: we must remove the whole unicode character, then check the size again, until the encoded message's length is lower or equal to the maximum length.
It won't solve the case where the bot can send a valid message, but the server won't be able to propagate it properly to other clients because it has to add extra information (such as the bot's hostmask and all) and such a way that it generates a message too long.
But it's a good start to fix #467

core: properly truncate long messages with 2-byte characters

---

sopel.py
sopel/config/__init__.py
sopel/run_script.py
test/test_run_script.py

My end goal is to address issues like #1243 or #1175 and for that the code must allow it, either by being more modular, or more reusable, or more testable - not mentioning documentation, which is not an easy task at all.
In this PR:
* I extracted bit of code from `sopel.run_script` into separated and testable functions,
* I removed the usage of a global variable in these functions, as it is an hard-coded value, so it could be replaced at a higher level of the application,
* I replaced as much as I could any `sys.exit` and `os._exit` call, while keeping the exit value for the command line,
so it still lacks proper unit-testing and documentation, but in my opinion it is a good starting point.
That being said, I think this is a good topic for Sopel 7.0.0 or another future version.

run_script: clean up & reorganize code

---

sopel/__init__.py
sopel/irc.py
sopel/modules/admin.py
sopel/run_script.py

This PR is an up-to-date version of the seemingly abandoned #1103 by @pachuco.
Personally, I need to dig more into why the `pid_file` parameter exists in `run()`, and why it was removed in this PR. But any further changes I might make to this pull request as a result will be in new commits, so as not to overwrite @pachuco's author credits in the commit log.
Assigning to 7.0.0 for now, to match the tentative (but never official) placement of the original PR. (Target milestone subject to change, of course.)

Implement restart functionality

---

sopel/modules/wiktionary.py

Looking at the wiktionary results so far, it appears that all (or nearly all) of the words are lowercase when querying. I believe it is safe to cast our query to lower().
Should fix #1214

wiktionary: fix query logic

---

requirements.txt

I can't WAIT to drop the ipython module from core.
Less than a year after dropping py2 support, upstream has also dumped support for Python below 3.5. They're moving too fast for our slow-ass release cycle (and it's not even an important dependency).
Shout-out to `eagle` on IRC for kick-starting this one. Yes, it appears Sopel works just fine with IPython 7.x.

Update supported IPython versions again

---

requirements.txt

dnspython dropped support for Python 3.3 in version 1.16.0, so we have to special-case that. Otherwise, py2.7 and 3.4+ are supported until version 2.0 comes out.
This is the part where I maybe come to regret adding this dependency, isn't it? Might be worth trying to make dnspython optional later.
Closes #1461.

Get specific about dnspython requirement

---

sopel/config/__init__.py

Infer config directory from given config filename. I found this branch kicking around while looking for something else… how I forgot about it for six months, I have no idea.
Resolves #1243 (@alanhuang122 please confirm :sweat_smile:)

config: don't assume ~/.sopel as dotdir

---

sopel/modules/dice.py

See issue #1420 and PR #1421 that I used as my starting point.
Following my comment on #1420 I decided to go with a PR that:
* strip the space from the input,
* properly format delimiter in the ouput,
* add some test example while I was at it,
* and use the space `\s` as a last-resort delimiter, because why not,
which improve coverage and make for a better output.
**EDIT**: we discussed another option, which I implemented afterward, to use comma as an output delimiter in all cases and to add quotation marks when needed.
Example with comma `,`:
[nick] .choose a, b, c
[Sopel] Your options: a, b, c. My choice: b
Example with comma `,` (without spaces):
[nick] .choose a,b,c
[Sopel] Your options: a, b, c. My choice: b
Example with pipe `|`:
[nick] .choose a | b | c
[Sopel] Your options: a, b, …

dice: clean up the dice "choose" command output (fix #1420)

---

.travis.yml
dev-requirements.txt
sopel/modules/etymology.py

Travis wasn't testing on 3.3, so this slipped in with the rewrite for Sopel 6.6.0 (#1432). Hopefully Travis will just work without any additional tweaking, and we'll have tests for Python 3.3 until we eventually do drop support for it (since it's already EOL).

etymology: fix py3.3 compatibility

---

sopel/module.py

At present, the privilege level constants (VOICE, OP, HALFOP, ...) aren't included in the [documentation](https://sopel.chat/docs/plugin.html?highlight=unblockable#module-sopel.module) because they lack docstrings. Docs `make html` appears correct with this patch, though ordered alphabetically with the other constant (NOLIMIT).

Add docstrings for privilege levels

---

sopel/modules/etymology.py

**Note**: quick fix for 6.6.x
The `ety` command now properly encodes the search term used in the URL
to request www.etymonline.com.
This way, the command `.ety coup d'etat` returns something like:
> "1640s, from French coup d'étate, literally 'stroke of the state'
> (see coup). […]" - https://www.etymonline.com/word/coup%20d%27etat
Instead of this:
> Can't find the etymology for "coup d'etat".
> Try https://www.etymonline.com/search?q=coup d'etat
Which was very unfortunate, because a) it didn't find the answer
and b) it gave an invalid URL to search for an answer.
It also encodes the search URL when it does not found a result:
<me> .ety not found
<Sopel> Can't find the etymology for "not found".
Try https://www.etymonline.com/search?q=not%20found
So that the user can copy and paste the …

etymology: quote URL parameters

---

sopel/modules/search.py

**Note**: quick fix for 6.6.x
Following #1480 my eyes turned to the search module, and they found the same kind of problems.
So I applied the same solution, and it works fine:
<@Exirel> .suggest 2+2
<Sopel> 4
<@Exirel> .suggest coup d'ét
<Sopel> coup d'état
_(also yes, I'm so French that I can't resi**s**t to use "coup d'état" in my example)_

search: quote URL parameters

---

sopel/modules/instagram.py

**Note**: based on 6.6.x
It all started with a small hitch I wanted to scratch off my head, then I saw minor problems here and there, so I fixed them all:
* unicode prefix for string while `unicode_literals` is in the import from `__future__`
* bad import order
* usage of specific import (`from sopel.module import rule` instead of `from sopel import module`)
**Edit:** no more replacement of `module.rule` for now.

instagram: remove `u` prefix (and other cleanups)

---

setup.py
sopel/cli/__init__.py
sopel/cli/utils.py
sopel/config/__init__.py
sopel/run_script.py
test/cli/test_cli_utils.py
test/test_run_script.py

Related to #1471:
* create a `sopel.cli.utils` modules,
* functions from `sopel.cli.utils` are available from `sopel.cli` as shortcuts,
* find, enumerate, and load configurations functions are now in `sopel.cli.utils`,
* `sopel.run_script` now uses `sopel.cli.utils` for these functions,
* existing tests are moved around into `test/cli/test_cli_utils.py` for consistency,
and there is no new feature, only internal changes: everything is backward compatible.
From this PR, it is possible to change how settings are loaded (which files, from where, etc.), and there is one single place to load a Sopel's configuration.

sopel.cli.utils

---

sopel/coretasks.py
sopel/module.py
sopel/modules/announce.py
sopel/modules/ipython.py
sopel/modules/reload.py

There is a decorator in `sopel.module.require_admin` that check for `trigger.admin`, but it wasn't used everywhere!
So I fixed this, and added a `reply=False` optional argument, that, when `True`, uses `bot.reply` instead of `bot.say`.
It's a very small improvement.

modules: use @require_admin instead of if trigger.admin

---

sopel/modules/unicode_info.py

**Note**: based on 6.6.x (and yes, this looks like #1483 a lot - but it's a different plugin!)
The `hex` function returns a `str` object, and you can not use a bytestring object when you need a unicode one. Which is a problem, because py2's str is py3's bytestring, and the py3's str is
py2's unicode.
The previous implementation used to convert everything into `str` and to call it a day. It "works", but requires some hack, for instance:
ord(u'' + arg)
point.rjust(4, str('0')
Which can be quite confusing. To make things easier to read, the new implementation defines `unicode` for py3 as an alias for `str`, and uses it in the code once. From that line:
unicode(hex(ord(char)))[2:]
Everything is working with unicode strings (which is more consistent) instead of working with bytestrings in py2, …

unicode: remove `u` prefix (and other cleanups)

---

sopel/modules/version.py

Last unsolicited PR until I dig into `.reload` more, _I PROMISE_ :grin:
Sometimes I forget which version of python I am using :sweat_smile:.  Really though, this stemmed from testing issues/code across multiple versions of Python. I could _quickly_ check the Sopel version from the bot, but not the python version it was running on. This commit simply appends the Python version to the `.version` response.
I don't think it shouldn't really be a security issue to show the Python version of the bot... _right??_

version: include python version

---

sopel/coretasks.py
sopel/test_tools.py
test/test_regression.py

Both `handle_names()` and `_record_who()` should update both `bot.privileges` and `bot.channels`. The fact that they don't is a leftover bug from who knows when.
We're also no longer happy with throwing an `assert` in released code, so the consistency check in `track_modes()` is now a logger warning.

coretasks: Consistently update privilege tracking

---

sopel/module.py
sopel/modules/adminchannel.py
sopel/modules/clock.py
sopel/modules/reddit.py
sopel/modules/safety.py
test/test_module.py

`bot.privileges[channel][user]` -> `bot.channels[channel].privileges[user]`. Smoke tested.

Replace deprecated bot.privileges accesses

---

sopel/test_tools.py

Before:
```
:NickName!UserName@example.com  PRIVMSG NickName :msg param to @example
```
After:
```
:NickName!UserName@example.com PRIVMSG NickName :msg param to @example
```
Yes, it's that subtle. :smirk_cat:
----
For quite some time, the example-test hostmask has been causing an invalid raw line per IRC specs (the prefix and command MUST be separated by a single space, no more—this code was generating two).
This manifested as `KeyError: Identifier('PRIVMSG')` when a tested callable tried to find `trigger.sender` in `bot.channels` (or, though I didn't check it, presumably also `bot.privileges`). While the error was expected, the value should not have been `PRIVMSG` but a channel/nick.
Alone, this fix doesn't do anything for the tests I'm trying to write… but it's still a silly bug worth …

test_tools: fix invalid raw line in example tests

---

sopel/bot.py
sopel/modules/reload.py

Similar to #1381, `.reload` didn't call any shutdown methods. This pull request addresses this by simply calling the shutdown method(s) before unloading the resources.
Fixes #1395

reload: fix shutdown routines not called on .reload

---

setup.py
sopel.py
sopel/__init__.py
sopel/cli/run.py
sopel/cli/utils.py
test/cli/test_cli_run.py

**Related** to #1471
This move the `sopel/run_script.py` file to `sopel/cli/run.py`, and updates the `sopel` command line tool's interface:
* `sopel start` replaces the default behavior (run the bot)
* `sopel stop` replaces the ``--quit/--kill`` options
* `sopel restart` replaces the ``--restart`` option
* `sopel configure` replaces the `-w/--configure-all/--configure-modules` options
The `-v` option for "version" is deprecated, `-V/--version` should be used instead.
By default, `sopel` works as before (100% backward compatible), but adds some warning here and there when needed (when using --restart/--quit/--kill for example).
This is all thanks to #1472 being merged.

cli: move sopel.run_script to sopel.cli.run

---

sopel/bot.py
sopel/modules/bugzilla.py
sopel/modules/instagram.py
sopel/modules/reddit.py
sopel/modules/url.py
sopel/modules/wikipedia.py
sopel/test_tools.py

This new interface adds:
* `bot.register_url_callback(regex, callback)`, to register a `callback` to call when a URL matches `regex`
* `bot.unregister_url_callback(regex)` to remove this regex from triggering callbacks
* `bot.search_url_callbacks(url)` to get a list of (callback, match) for each pattern matched by the URL
This provides a unified interface to work with URL Callbacks, but does not change how the built-in url plugin works (yet).
So this:
if not bot.memory.contains('url_callbacks'):
bot.memory['url_callbacks'] = tools.SopelMemory()
bot.memory['url_callbacks'][instagram_pattern] = instaparse
Become this:
bot.register_url_callback(instagram_pattern, instaparse)
It does not change the fact that the `url` built-in plugin is required at the moment in order to work with URL …

core: URL Callbacks new interface

---

README.rst
setup.py
sopel/cli/run.py

This will simply display a warning about py2.x EOL
It won't exit, but gives people most of a year to straighten out their python versions.
Not saying Sopel should/will drop py2.7 support Jan 1st 2020, but we shouldn't tie our hands with this either.

Py2 warning

---

sopel/modules/url.py

A change that should have been made in #1413, but was overlooked. This proves why having more than one developer review changes is useful.
@Exirel indirectly found this omission during an overhaul of Sopel's URL-handling for version 7.
See https://github.com/sopel-irc/sopel/pull/1510#discussion_r268139814

url: Actually clean URLs when auto-fetching titles

---

sopel/modules/url.py

Python 2 doesn't like `thing is unicode`; it wants `thing == unicode`. Of course, it just works with regular str in both py2 and py3… Oh well.
This is another find from @Exirel's overhaul of URL handling for 7.x.
As long as I was touching the line anyway, I added parentheses to make the operator precedence explicit. Likely unnecessary, but probably easier to read by some small measure. (@Exirel, if you don't think the added parens are useful, I can drop it from this PR so you don't have to mirror it in #1510. :smile_cat:)

url: Fix py2 compatibility in trim_url()

---

sopel/cli/utils.py

**Related** to #1471
**Replace** #1445, based on #1472 
This PR adds one commit to #1472 to load the configuration file from the environment variable `SOPEL_CONFIG`.
Sopel will now try to load the configuration from:
* `-c <filename>` or `--config <filename>` if used,
* then look at `SOPEL_CONFIG` env var, and use it if not empty,
* and default to use `default`,
but it does not try to load one and fallback on other: it'll stop at the first option available, and raise an error if the configuration is invalid and/or not found.

cli: allow config loading from env (SOPEL_CONFIG)

---

contrib/sopel.service
contrib/sopel@.service

The service files also specify their unit to start After=network.target
but that target only defines the start of networking, and network
configuration may not be complete yet; instead it should use
network-online.target to ensure it starts after the network is
ready to use.
[EDIT: I removed the PIDFile= removal that was originally in this pull request]

systemd service files: use network-online.target

---

setup.py
sopel/cli/config.py

**Replace** #1465
The `sopel-config` is a CLI tool to:
* list existing configuration file from Sopel's homedir
* init a new configuration file in Sopel's homedir
* get a value from a section.option of Sopel's configuration
It could do much more, but I'll leave it here for now, since @dgw is quite busy.
Note: `sopel-config list` could replace `sopel --list`, and `sopel-config init` could replace `sopel --wizard` in the end. That requires more thought.

cli: add `sopel-config {list,init,get}`

---

sopel/modules/ip.py

`dns.google` is quite a catchy name, but our tests were failing because of this sudden (not that I know where they would announce it) change.
On the plus side, we now have robust tests that should correctly handle both the old and new hostnames, and probably most potential future changes as well. And they're *actually* using regex syntax, unlike before with the unescaped brackets and pipes.

ip: fix tests (again)

---

sopel/modules/admin.py

For good measure, I added a configuration save on the `part` command too.
Fixes #563

admin: save configuration on .join/.part command

---

sopel/modules/ipython.py
sopel/test_tools.py

Any individual test of a Sopel module (either as `python a_module.py` or `pytest a_module.py`; even with full path), leads to this exception:
```
___________________________________________ test_example_rand_1 ___________________________________________
Traceback (most recent call last):                                                                         
File "/home/sopel/pkgs/sopel/sopel/test_tools.py", line 113, in test                                     
bot = MockSopel("NickName", admin=admin, owner=owner)                                                  
File "/home/sopel/pkgs/sopel/sopel/test_tools.py", line 52, in __init__                                  
self.channels[channel] = sopel.tools.target.Channel(channel)                                           
AttributeError: …
```

fix: regression in testing individual modules

---

sopel/modules/admin.py

Before:
<Owner> .set
<Sopel> AttributeError: 'NoneType' object has no attribute 'split'
After:
<Owner> .set
<Sopel> Owner: Usage: .set section.option value

admin: Catch set commands without arguments

---

.travis.yml
contrib/rpm/sopel.spec.in
requirements.txt
sopel/modules/spellcheck.py

I had experimented with this module a bit, and had found that I was completely unsatisfied with its performance (namely, the corrections it suggested). As a result, I rewrote the module to use aspell instead of pyenchant. The resulting performance satisfied me.

spellcheck: complete rewrite

---

sopel/test_tools.py

New PR as I absolutely messed up the original one..
When running a testsuite where the bot.say, reply or action function has any other than the defined arguments set, for example max_arguments, it will fail. With this change it should accept any named arguments.
Would be nice if this could also be done for the 6.6.x branch.
```
TypeError: _store() got an unexpected keyword argument 'max_messages'    
```

fix _store() so it accepts any named arguments

---

sopel/bot.py

Adds shortcut for `bot.users.get(bot.nick).hostmask`.
Closes #1533.

core: add `bot.hostmask` getter

---

sopel/bot.py
sopel/coretasks.py
sopel/irc.py
sopel/loader.py
sopel/module.py
sopel/modules/find.py
test/test_module.py

Rebased & tweaked version of #1072, which stalled. Resolves #526. Original PR description by @maxpowa follows; see #1072 for the earlier evolution of this patch.
----
Allows modules to listen in on what's being sent by Sopel. Compatible with all the other decorators, as it goes through all the same logic. If `echo-message` is supported on the server and is toggled on by a module, only functions with the `@sopel.module.echo(True)` decorator will receive those echo messages. If `echo-message` isn't enabled, the same behavior still exists but the hostmask will not be as accurate.

irc/bot: implement echo-message

---

sopel/coretasks.py

`bot.write()` joins the elements of a sequence type (tuple, here) with a space already, so including a space in `'MODE '` caused Sopel to send <code>MODE &nbsp;SopelsNick +modes</code>. Technically, that's invalid.
Discovered while trying to test #1470 on a network with actual support for `echo-message`, when darwin.network disconnected the bot during registration with the message "ERROR :Received malformed line". Annoying because I was trying to test something else, but useful in the end.

coretasks: fix malformed MODE command in startup()

---

Makefile
checkstyle.sh
dev-requirements.txt
setup.cfg

**TL;DR**: I'm super lazy and it shows.
There are 2 things I can't remember:
* the full line to checkstyle + coverage + tests
* the exact parameters for flake8
And I really like `make`, it's a great tool for any projects, not just for C/C++ stuff. So here is a short one, with few commands that I find useful. This is the kind of commands I use in my own project, be they personal or professional.
For `flake8`, I wish I could just run it without having to resort to `checkstyle.sh`, and the `setup.cfg` file is perfect for that. I tested it worked, by adding/removing ignored errors/warnings. Isn't it great?
Bonus point: I hate having to cd into docs to build the doc, then to cd back in the project.  So I added that, too.

dev: add a Makefile to the project and use setup.cfg to configure flake8

---

sopel/bot.py
sopel/config/__init__.py

Ability to disable modules or even methods inside chosen modules for channel name using default configuration file.
In this example we are disabling modules / modules methods on `#example` channel.
`disable_modules` is used to completely disable provided modules on channel for example `choice, weather` won't respond at all.
`disable_commands` is used to disable methods from provided modules for example `event_watcher` from `url` module which means all other methods should work (unless disabled are needed).
Adding other channel excludes is as simple as adding another section named like channel.
```
...
[#example]
disable_modules = choice,weather
disable_commands = {"url": ["event_watcher"]}
```
----
Resolves #64, after many long years and multiple project renames. — @dgw

Support disabling modules/commands per channel

---

sopel/__init__.py
sopel/irc.py

core: fix broken interrupt handling (6.6.x)

---

sopel/modules/meetbot.py
sopel/modules/reddit.py

Cleaner, and makes source display work correctly in editors that don't like non-printing characters.

Replace manual color codes with sopel.formatting

---

sopel/modules/admin.py

Just like #1544, but in the `admin.py` module instead of coretasks.
This was the only relevant occurrence I could find with a search for strings with trailing spaces. Hopefully after this, we're golden.

admin: .mode compliance with IRC specs

---

sopel/bot.py

The penalty for a message that trips flood protection scales directly with the message length and has no upper bound. As seen in #1550 and #1551, a 64bk message (which can apparently be returned during normal bot function) would incur a penalty of ~37 minutes between message sends.
I think the best option is to just cap the maximum wait time between messages. I followed the example of ZNC, which has a default of `1.00` seconds between messages that trip its flood protection.
This option is configurable under `[core]` with the `flood_trickle_rate` setting.
Fixes #1550 and fixes #1551

core: limit maximum flood penalty

---

sopel/irc.py

Before the connection is accepted (and the socket exists), <kbd>CTRL</kbd>+<kbd>C</kbd> will
start closing nicely, until `irc.Bot.handle_close`. `handle_close()`
tries to close the socket, even if it may not exist, which leads to a
messy exit.
All that is needed is a quick check to ensure a socket exists before
trying to close it.

core: fix interrupt during connection phase (before connection accepted)

---

sopel/bot.py
sopel/module.py
sopel/test_tools.py

Despite notes like this: https://github.com/sopel-irc/sopel/blob/229f3bfacaf393f331bf79569783f23d88d05a03/sopel/bot.py#L270-L272
each outgoing method (`bot.msg`, `bot.say`, `bot.notice`, `bot.action`,
`bot.reply`) should be present in the mock as long as they are present
in the codebase such that they can be used in testing.
These "mocks" need to exist so that more tests can be written (e.g., #1540) that use _actual_ mockers (`e.g., pytest-mock`).

tests: make MockSopelWrapper subclass actual SopelWrapper class

---

dev-requirements.txt
setup.cfg
sopel/__init__.py
sopel/bot.py
sopel/cli/run.py
sopel/config/__init__.py
sopel/modules/calc.py
sopel/modules/dice.py
sopel/modules/emoticons.py
sopel/modules/find.py
sopel/modules/help.py
sopel/modules/isup.py
sopel/modules/search.py
sopel/modules/tell.py
sopel/modules/wikipedia.py
sopel/test_tools.py
test/test_loader.py

Somehow, being sick motivated me to work on a tedious patch that I would usually skip in favor of writing something more interesting. But this seems to have been productive!

Unignore more style checks

---

sopel/cli/run.py

@dgw did a good job describing the issue in #1478, so I refer the reviewer there for the details.
The fixes provided here use simple checks to ensure 1) that a socket is present before attempting to send a `QUIT` message, and 2) a `hasquit` flag was not set on a bot instance during a disconnected phase.
Generally, in both cases, the issue was the signal setting the `hasquit` flag too late, and allowing a new `while` loop to begin. The bot would still have the `hasquit` flag set, but this would not be caught until a new `Exception`/`signal`.

core: fix broken interrupt handling

---

sopel/modules/help.py

I've created a new config section `help` with the `output` setting. `output` can currently be set to:
* `"ptpb"`
* `"0x0"`
* `"hastebin"`
* `"termbin"`
This resolves #1416.
```
19:42 <uint> .set help.output termbin
19:42 <uint> .help
19:43 <uint-bot> Hang on, I'm creating a list.
19:43 <uint-bot> I've posted a list of my commands at https://termbin.com/3tyx2 - You can see more
info about any of these commands by doing .help <command> (e.g. .help time)
```
It seems that if I use `.help`, the bot will cache the url. If I then change the `output` option to something else, the bot won't let me use the new service since it still has the old link cached. This could lead to problems if the old link is erroneous and the user can't get a new one until they restart the bot.
@dgw Is it possible to …

help: choose pastebin service for .help output

---

sopel/loader.py
sopel/module.py
sopel/modules/admin.py
sopel/modules/help.py
test/test_loader.py

Should behave the same as before for modules that don't use the new parameter to `@sopel.module.example()` to declare multiple help examples.
Updated `admin.py` module as a proof of concept. Going through other modules and updating them with multiple examples is a separate project.
Output is still tweakable, but I'm happy enough without worrying about splitting lines just yet.
----
This is WIP code I based off of #1303. Between the length of time between when I last looked at this and the present, and the fact that I had to manually rebase it on `master`, I'm definitely leaving it labeled WIP until I get back to working on it (probably after 6.6.0 releases).
Because this changes the module API (a new argument to `@sopel.module.example()` is introduced), this will be a Sopel 7 project.

help: support multiple examples

---

sopel/tools/__init__.py

It started from noticing some extra blank lines and a few typos, and snowballed into this reasonably large changeset. Sometimes I just can't stop fixing documentation once I start…
This might or might not get added onto. I only touched `tools/__init__.py` so far, and haven't looked at any of the subpackages. (`web` is safe until #1318 gets sorted—that branch is still WIP, but largely done.)
Officially marking the `SopelMemory.contains()` method (and its fraternal twin in `SopelMemoryWithDefault`) as deprecated felt really good. Can't wait to get rid of them for good…

tools: Overhaul docstrings

---

sopel/config/types.py
test/test_config.py

This is a first step towards completing #1455, since, as @dgw mentioned, to do so would require accepting commas in a single entry of `ListAttribute`.
Items entered through the wizard do not need to be escaped manually. Items configured in the `.cfg` file manually require an escape sequence, like `\,` or `\\`. The prompt has also been changed such that the items are now surrounded by quotes so that one can differentiate items that may contain commas.
Relevant tests were added/updated (see commit messages).

config: support comma in config ListAttribute item

---

sopel/config/core_section.py
sopel/coretasks.py
sopel/module.py
sopel/modules/url.py
sopel/web.py
test/test_web.py

This fix #1489 - at last!
PR #1508 added a new interface for plugin maintainers, that would help us work with URL callbacks. In this PR, I:
* never trigger URL Callbacks from the `url` built-in plugin
* share the "find URL" feature into `sopel.web` (with unit tests for good measure)
* trigger URL callbacks from a `@url` defined in `coretasks`
This way, one may disable the `url` plugin, and the bot won't auto-title URLs. However, other plugins will still be able to define and use URL Callbacks.
Plugins that use `@rule` and define their own callback will still work, and that won't trigger callbacks.
By the way, this should fix https://github.com/sopel-irc/sopel-github/issues/13 too as soon as the github plugin uses `@url` instead of `@rule`.

core: handle URL callbacks in coretasks

---

sopel/bot.py
sopel/modules/url.py

The title says it all!
The flood of deprecation warnings from `.contains()` was quite unpleasant.

style: replace deprecated `SopelMemory.contains()` with `in`

---

sopel/tools/__init__.py

Previously the deprecation warning message was too long!
```
Function contains is deprecated.                                             
File "/usr/local/bin/debug-sopel.py", line 22, in <module>                 
sys.exit(run_script.main())                                              
File "/home/sopel/pkgs/sopel/sopel/cli/run.py", line 663, in main          
return command(opts)                                                     
File "/home/sopel/pkgs/sopel/sopel/cli/run.py", line 623, in command_legacy
ret = run(config_module, pid_file_path)                                  
File "/home/sopel/pkgs/sopel/sopel/cli/run.py", line 72, in run            
p = bot.Sopel(config, daemon=daemon)                                     
File "/home/sopel/pkgs/sopel/sopel/bot.py", line 143, in …
```

tools: decrease deprecation warning output

---

sopel/modules/help.py

I have been disabling the `help` module because it shows the name of my server in a full `.help` listing. This would be okay if the bot connected directly to a public server, but if it goes through a private bouncer, it may not be desirable to share this information.
Of course I can modify `help.py` to prevent this, but I thought "Why not make it configurable?". So, here it is :tada: 
A config section is defined for the `help` module (section called `help`, of course), which for now, only has one setting: `show_server_host`, a boolean that determines whether the server name will be printed or not; e.g., `Command listing for ro-bot-o@znc.roboto.org` (`true`) vs `Command listing for ro-bot-o` (`false`). A `configure` method was also added to provide config wizard support.
This required …

help: add config to hide server host from help listing

---

sopel/modules/help.py

While I was fixing the `iteritems()` py3 regression from #1459, I saw some other stuff that could use tweaking. Moved a bit of code around, and rewrote some comments—nbd really. Should be an easy :heavy_check_mark:

help: hotfix & small refactor

---

sopel/bot.py
sopel/tools/jobs.py
test/tools/test_tools_jobs.py

Two main ideas:
* instead of a `while True` loop to run the scheduler, a `threading.Event` object is used: the scheduler run until this event is set
* instead of a custom `PriorityQueue`, a built-in list object is used to store job: every now and then, the scheduler will look for jobs that are ready to run, run them, and never modify its list, keeping everything thread-safe and simpler
It is kept thread-safe by using properly a `lock`, and it has the advantage of not having to release it or rely to heavily on `time.sleep()` - or at least, only for a second each loop.

jobs: make JobScheduler easier to stop

---

sopel/coretasks.py
sopel/test_tools.py
test/test_coretasks.py

Opening this PR early as a draft, to gather feedback from @half-duplex (who reported a possible mode-tracking bug in the 6.6.x series to me) and others who might have more spare time and/or brainpower this weekend than I seem to (so far). 😅
If this turns out to be a productive rewrite, it's a solid reason to release a version 6.6.7 (which is not currently planned). Should it not help anything, I mean what I said in that comment about rewriting the mode tracking again after ISUPPORT parsing (#1536) gets finalized and merged for Sopel 7.

coretasks: Major rewrite of MODE handling

---

sopel/modules/currency.py

Hey there. Since I was moving from an old bot to sopel, I wanted to have it mimic what I and others were used to from my old bot. Because of this, I made it support multiple target currencies like:
`.cur 100 usd in dkk eur usd aud cad btc`
additionally, I moved to https://exchangeratesapi.io/ as the bank of Canada apparently doesn't offer rates for the Danish krona. Exchangeratesapi doesn't have a whole ton of currencies either, but the output is fixer.io compatible, so if it becomes a problem, a simple change would be to add a config section, allowing people to choose between API-key-less, exchangeratesapi.io or getting a free API key from fixer.io
A free API key should be more than enough as well, as the module caches rates for 24h in a global variable, and the free fixer.io plan offers …

currency: Moved to different API, support multiple target currencies, cache rates

---

sopel/cli/utils.py
test/cli/test_cli_utils.py

According to this:
https://github.com/sopel-irc/sopel/blob/0952f4443f831ef7eeba0c04ab34ff3f6dc76197/sopel/cli/utils.py#L153-L154
`find_config` is expected to always return an absolute file path.
However, here:
https://github.com/sopel-irc/sopel/blob/0952f4443f831ef7eeba0c04ab34ff3f6dc76197/sopel/cli/utils.py#L185-L186
it is possible for a simple filename (or relative path, which is not as bad, but still not the expected result) to be returned.
This is usually not an issue, but in the wizard, an attempt to `os.makedirs` is made, which breaks if there is no directory to even try to be made :smile: 
Fixed now, though.

cli: `cli.utils.find_config` returns absolute path, as expected

---

test/test_regression.py

Remove the sopel_bot fixture based on @Exirel's comments on #1575

test_regression: use fresh `MockSopelWrapper`s

---

sopel/modules/admin.py

The title says it all!
_Hello, #1556! Here, have some merge conficts_ :smile: 
Fixes #1586

admin: prevent setting of 'core.owner' setting

---

sopel/formatting.py
sopel/tools/__init__.py
sopel/tools/_events.py
sopel/tools/target.py

While I was using the live website over the weekend to reference Sopel's API docs, some annoyances jumped out at me in the page about other API features (formatting, various tools).
Today, I decided to fix them. Most of this is touching stuff that hasn't been overhauled (#1565) yet, but I'll probably have to deal with a merge conflict or two on stuff in `tools` that I did already fix in #1563. It's worth doing so our live site can have a bit better content—especially since I fixed an actual mistake!

Fix up some docstrings for 6.6.x

---

sopel/module.py

Since @Exirel added `reply` as an optional argument to `module.require_admin` (in #1456), it seemed prudent to implement the same argument on all of its relatives for consistency's sake.
Also added the parameters to docstrings for the functions I touched, since I was in there anyway.
Now this is a full-blown API addition instead of a one-off oddity! :grin:

module: optional `reply` arg for all `require_*` decorators

---

sopel/modules/wiktionary.py

The _refactor_ comes from changing the control flow, and the _bugfix_ is the ability of the module to parse more parts of speech. While this may not be a _bug_ per se, I'd think not being able to get definitions for a word/term that is actually in Wiktionary is not a preferred behavior (pardon the double negative :sweat_smile:).
Regardless, this PR is opened to address the points that came up in #1405:
- ~~give subdefinitions like those for [`-able`](https://en.wiktionary.org/wiki/-able) their own sub-number (e.g., 1a., 1b., ...)~~
- ~~update formatting algo to be smarter about sub-definitions and such~~
- ~~re-order parts of speech list so that definitions can be prioritized... it would be a shame if some obscure _circumposition_ (A circumposition is a discontinuous adposition... _um …

wiktionary: refactor/bugfix parsing all possible parts of speech

---

sopel/modules/remind.py
test/modules/test_modules_remind.py

Started by the conversation in #1543, this PR removes the usage of `time.sleep()` in a rogue thread. Now that #1557 has been merged and with the future plugin interface from #1479, job scheduling is a much better option for the remind plugin.
This PR was a good occasion to clean the code, to add some tests, and to fix some PEP 8 violations (I used `pylint` for that one). However, this will cause troubles for #1162 at first, but I'll figure this out later.

remind: use module.interval instead of custom monitoring

---

sopel/modules/adminchannel.py

Essentially reverts commit 902e715b308b7f3a663c961a64a3481af67f6ebf, but restores edited code that meets Sopel's current standards (using `bot.channels`; providing error messages for `@require_*` decorators).
Closes #1350

adminchannel: restore op/voice commands

---

.travis.yml
Makefile

Testing the full range of Python versions Sopel claims to support is probably wise. Generating releases from one of the newer runtimes is, likewise, also probably wise.
Running releases on 3.6 is a nice compromise between bleeding-edge and platform stability.
We don't test Python 3.8 yet, because its first stable release isn't scheduled until October of this year (2019). Travis supports testing on 3.8-dev or nightly versions, but that's not necessary for us.
_(This is the part where I hope that Travis picks up these settings when building the PR, so I can make extra sure they work as expected. Serve me right if it still uses the matrix from `master`…)_

build: modernize/expand job matrix

---

README.rst
requirements.txt
sopel/config/core_section.py
sopel/db.py

This should fix #736.
This PR migrates from direct SQLite SQL statements to using the SQLAlchemy ORM. This will allow users to choose whether they want to stick with SQLite (Default), or leverage another database engine.
I've added a few more variables to core to handle non-SQLite databases: db_type, db_user, db_pass, db_host, and db_name. If db_type is not specified, or is specified with sqlite, the other values do not need to be specified. If db_type is specified with MySQL, users will need to specify the other parameters.
We could probably move the Models into their own model.py to clean things up a bit, but I will leave that to your discretion @dgw

db: adding multi database support

---

sopel/bot.py
sopel/coretasks.py
sopel/irc.py
sopel/logger.py
sopel/module.py
sopel/modules/admin.py
sopel/modules/announce.py
sopel/modules/etymology.py
sopel/modules/find_updates.py
sopel/modules/help.py
sopel/modules/meetbot.py
sopel/modules/remind.py
sopel/modules/tell.py

This PR aims to deprecate the usage of bot.msg as per:
````
def msg(self, recipient, text, max_messages=1):
self.say(text, recipient, max_messages)
````
As of right now, anything that calls `bot.msg` gets passed to `bot.say`. This skips that step.

Deprecate usage of bot.msg to bot.say

---

sopel/modules/admin.py

If I hadn't rushed 6.6.8 out, this would have been fixed already, but I was too quick to approve and merge #1587 and didn't realize there was another setting that needed protection until it was too late.
I'm sure there will be more little things to fix, so I'm not gonna rush this one out. Very few networks actually support the IRCv3 capabilities Sopel needs to authenticate accounts, so it's not urgent.

admin: Also protect `owner_account` setting

---

conftest.py
sopel/module.py
sopel/modules/calc.py
sopel/modules/ip.py
sopel/modules/search.py
sopel/modules/translate.py
sopel/modules/url.py

Usage:
$ py.test --offline
This option skip all tests that can not be run offline, as they are marked as "online". Either from manual tag:
@pytest.mark.online
def test_call_google():
request.get('https://google.com')
Or from a command example:
@example('.title http://google.com', '[ Google ] - google.com', online=True)
def title_command(bot, trigger):
This is especially useful for people like me who are always traveling and can't have access to a reliable Internet connection.
Existing online examples have been marked as such.

test: add an --offline option to pytest

---

sopel/module.py

I think I didn't rebase properly and set `online=True` by default instead of `online=False` on the `example` decorator in #1555

module: example online argument defaults to False

---

sopel/module.py

This broke auto-documenting module commands on the website, at least. (Good thing I decided to spin up a 'preview' branch of that now, instead of waiting until after Sopel 7 released to test it out.)
Not really sure why it didn't seem to break running Sopel itself when pytest isn't installed, but since pytest is a dev-dependency it's safer to handle the case when it's not available anyway.
Specifically requesting review from Exirel, instead of just any old Rockstar, because it was his PR (#1555) that caused this to break in the first place. I want to know if he has a better idea, since I'm just patching this at midnight to get the aforementioned 'preview' site working properly.

module: fix examples when pytest isn't installed

---

requirements.txt
sopel/modules/reddit.py

- version locking praw
- updating code for new praw version
- narrowing exception

reddit: updating reddit module praw dependency

---

requirements.txt
sopel/modules/url.py

Prevents private IPs being used for URL lookups. This doesn't work for resolved IPs, but prevents folks from actively using http://192.168.1.1 to access potentially private sites.

url: fixing private URL lookups

---

sopel/modules/tld.py

Knowing full well that this will cause a merge conflict that I'll have to resolve later, I still want to fix this little bug in the 6.6.x series. There's talk of possibly rewriting the whole thing for 7.x anyway.

tld: prevent outputting undecoded HTML entities

---

sopel/coretasks.py

`User` objects created in `handle_names()` have `None` in user/host attributes because `NAMES` does not contain that information. When a `WHO` reply comes in for a user that was already added by `handle_names()`, `_record_who()` should fill in the missing properties if possible.

coretasks: complete sparse User objects in _record_who()

---

.travis.yml
conftest.py
dev-requirements.txt

Per [pytest latest version documentation](https://docs.pytest.org/en/latest/writing_plugins.html#registering-markers) we should register the custom marker we use - for now, "online".
And for good measure, let's always update dependencies when running Travis.

test: register pytest "online" marker

---

sopel/bot.py
sopel/config/core_section.py

Code originally by @larsks in #908 
I just made it compatible with the current state.

 config, bot: Configurable message rate

---

sopel/bot.py

Since `elapsed` was defined the same way in both places, there's no reason it can't be defined just once instead, in a higher scope that allows using it in loop detection also.
The only stumbling block is the fact that the sensible default value for `elapsed` (0) would trigger logic that shouldn't be triggered. And we can't use the other sensible default (`None`) because you can't apply operations like `<` to `NoneType`. So I picked an arbitrary default.
This is an important follow-up to #1518 and will bypass our general FIFO merge policy.

bot: fix sometimes-undefined variable in flood protection

---

sopel/config/core_section.py
sopel/logger.py

logging currently uses the default msg format and date format; add cfg file parameters to allow users to specify what format they would like for both msgs and timestamps.

logging: add format and datefmt to allow configuring the log output from cfg file

---

sopel/config/core_section.py
sopel/coretasks.py
sopel/irc.py

currently only a single authentication method may be specified, so it is
not possible to do both server-based and nick-based authentication.  This
splits that into 'server_auth_method' which can be either 'server' and 'sasl'
and 'nick_auth_method' which can be 'nickserv', 'userserv', 'authserv',
or 'Q'.  This allows, for example, authenticating with username/password
to a server as well as performing nickserv authentication after login.
The existing 'auth_method' param remains, and if specified will override
both 'server_auth_method' and 'nick_auth_method'.

auth: split 'auth_method' into 'server_auth_method' and 'nick_auth_method'

---

.travis.yml
MANIFEST.in
setup.cfg
setup.py
sopel/__init__.py

Did you know it's not safe to `import sopel` in `setup.py`? It's because when you do  `pip install sopel`, what it does is:
* fetch `sopel-{version}.tgz` from PyPI
* un-tar and uncompress it
* run `python setup.py install` (more or less)
It means that, anything that is imported in `setup.py` must be available *before* the project is installed, meaning none of Sopel's requirements are available at this very moment. Which is not ideal!
On the other side, how do you get Sopel's version once it's installed? Or even before? This is what we want (Python 3.5.2):
```console
$ python setup.py --version
6.6.5
$ python sopel.py --version
Sopel 6.6.5 (running on Python 3.5.2)
https://sopel.chat/
```
and with Python 2.7:
```console
$ python setup.py --version
Warning: Python 2.x is near end of life. …
```

install: use setup.cfg to configure Sopel's package metadata

---

sopel/cli/run.py
sopel/cli/utils.py
sopel/config/__init__.py
sopel/irc.py

This is a fairly simple tweak to the way log files are named.
The use case is for people that run more than one Sopel bot, distinguishing exceptions and stdio log files would be a bit easier this way.

logging: use config's basename in log filenames

---

sopel/modules/find.py
sopel/modules/safety.py
sopel/modules/tell.py
sopel/modules/url.py

Modules will safely initialize (ensure key does not exist in memory already) in `setup()` and clean up (remove module-specific keys from memory) in `shutdown()`, where necessary.

modules: always safely set up/clear memory

---

sopel/bot.py
sopel/modules/adminchannel.py
sopel/modules/reddit.py
sopel/modules/safety.py

this adds a `bot.kick(text, channel, nick)` ability to the bot, instead of using `bot.write(['KICK', channel, nick], text)`.
If the bot isn't OP, nothing happens (expected).

Provide a simpler way to kick users from channels.

---

sopel/bot.py

Discovered after removing stock modules. If not in memory, the search fails with a KeyError.

bot: prevent KeyError from search_url_callbacks

---

sopel/modules/meetbot.py

This should satisfy the easy scrutinizer, flake8, and human complaints, and removes a couple TODOs (display durations in minutes instead of seconds).

meetbot: Line length, linting, tweaks, fixes

---

sopel/modules/admin.py

This is a simple PR to clean up 2 lines in admin.py to use bot.action

admin: utilize bot.action

---

checkstyle.sh
dev-requirements.txt
setup.cfg
sopel/bot.py
sopel/cli/run.py
sopel/coretasks.py
sopel/irc.py
sopel/modules/dice.py
sopel/modules/reddit.py
sopel/modules/tld.py
sopel/modules/xkcd.py
test/modules/test_modules_remind.py
test/test_web.py

Unignores (or updates to add) and fixes the following:
E117 over-indented
E127 continuation line over-indented for visual indent
E128 continuation line under-indented for visual indent
F632 use ==/!= to compare str, bytes, and int literals
With the above fixed, flake8 3.7.7 finds no errors, so the 3.6 pin is replaced with 3.7
`checkstyle.sh`'s py3-unsafe `unicode()` detection seemed to have some inverted logic and was reporting files _containing_ `unicode = str` as potentially unsafe, instead of only files _not_ containing that.

Unignore even more style checks

---

sopel/plugins/__init__.py
sopel/plugins/handlers.py
test/test_plugins.py

By defining a `sopel.plugins` entry point in a `setup.cfg` (or `setup.py`) it is now possible to expose a Sopel plugin:
setup(
name='my_plugin',
version='1.0'
entry_points={
'sopel.plugins': [
'custom = my_plugin.path.to.plugin',
],
}
)
This definition will allow Sopel to load the `custom` plugin, from the Python sub-module `my_plugin.path.to.plugin` from the `my_plugin` package.
I'm not 100% happy with my abstractclass/subclasses, but I think that's for another day. Here, I wanted to showcase how quick and easy it is to implement new ways to discover Sopel plugins.
I'd like to mention that, in my opinion, entry points are probably a better option than `sopel_modules.*` subpackages.

plugins: load plugins from setuptools entry points

---

sopel/db.py
test/test_db.py

These are functions I've had for my bot for a long time,
* reset - sets a value to None
* adjust - allows math adjustments to existing values
Reset can likely use a better method like `DELETE FROM` instead of replacing values with None.
Adjust is something I've been using for a long time now to retrieve a current value and add a positive or negative number to it. Handy for modules that need to update stat counters.

db: add methods to delete a channel or nick's key from database

---

sopel/tools/time.py
test/test_tools.py

datetime.timedelta has a string representation, I don't like how it looks, though.
The most obvious uses for this would be the `seen` and `tell` module.

tools: Add formatter for timedeltas

---

sopel/bot.py

Sometimes, the code is just too complicated for what it does. I prefer to streamline conditions, to use intermediate variable when it makes sense, take advantage of built-in function like `any(iterable)`. When something can be calculated once and reuse each iteration, that's fine.
The second commit brings some protection against side-effect and race conditions: it was, in theory, possible for a triggered function to alter the `Trigger` or the `SopelWrapper` objects, which could cause an unexpected behavior in another triggered function. Now, we guaranty that, at least, the `bot` and `trigger` arguments of any triggered function will be unique and tied to the function's invocation only.
Of course, it is still possible to mess with the bot itself (which is usually the purpose anyway), or …

bot: dispatch simplification and minor optimization

---

docs/source/bot.rst
sopel/__init__.py
sopel/bot.py
sopel/config/__init__.py
sopel/formatting.py
sopel/irc.py
sopel/module.py
sopel/test_tools.py
sopel/trigger.py
sopel/web.py

The `__all__` statement in a Python module is used at import time when `from module import *` is used to expose only a defined list of object to be imported in the `locals()` environment of the importer.
Even though the [Python documentation](https://docs.python.org/3/tutorial/modules.html#importing-from-a-package) talks about "sub-modules" to import, it is widely used to define a set of names to import instead (being objects, functions, or sub-modules).

core: add `__all__` statements in sopel fix #765

---

sopel/bot.py

Hey! With reference to #1565, I've started tidying up some of the docstrings in `bot.py`. I'm happy to help do others as well, but this is just to check that this is the kind of thing you're looking for. Feedback is obviously requested and will be gladly received!

First pass of docstring additions.

---

sopel/modules/remind.py
test/modules/test_modules_remind.py

**This PR is based on #1581, and it replaces PR #1162.**
Also fix #1148.
It can replace PR #1581 if someone is brave enough to do the review of all the changes in one go.
I added an extensive test-suite to make sure the remind `.at` command works as intended.
I made `.at` opinionated about how date are expressed, with these choices:
* YYYY-mm-dd is valid, as dd-mm-YYYY
* dd-mm-YY is also valid
* screw mm-dd-YY (or mm-dd-YYYY) format
* dd-mm is valid too, as mm-YYYY and YYYY-mm
* but there is no such thing as mm-YY or YY-mm
* date separator can be either `-`, `.`, or `/`, and it must be the same between each parts
Even with all the unit-tests I added, I spent a good one hour with a live Sopel instance, and everything went according to the specs.

remind: add support for date in .at command

---

sopel/bot.py
sopel/cli/run.py
test/test_bot.py

At first, I had to rework the Job Scheduler in order to test how Sopel registers and unregisters plugins, which was annoying. But then, the solution wasn't perfect: I didn't like to have to manually stop the scheduler for testing purpose—which is time consuming and a bad thing when your test suite grow a bit (a lot at the moment). Aside from that, it also means that plugins where loaded, even if I didn't want them to be, or even needed to be. **This is the first thing I fixed**, by moving the call to `Sopel.setup()` outside of `Sopel.__init__()`.
Then, I realized: wait a minute... why do we setup plugins inside Sopel, but not logging? I couldn't find a good reason, so I moved that into Sopel's setup sequence.
Eventually, I thought: why do I even bother with the scheduler? Why do we need …

bot: new setup sequence

---

docs/source/cli.rst
setup.py
sopel/cli/plugins.py
sopel/cli/utils.py
sopel/plugins/handlers.py
test/cli/test_cli_utils.py
test/plugins/test_plugins_handlers.py

Should fix #244 and fix #1519 at the same time.
This PR adds a new command line to Sopel: `sopel-plugins`.
This command line supports 4 actions:
* `list`, to list available plugins (all by default, or just enabled/disabled plugins)
* `show`, to show detailed information about a plugin
* `configure`, to run a config wizard for a plugin
* `enable`, to enable a plugin
* `disable`, to disable a plugin
In order to implement it, I had to update the plugin handlers, adding methods to get meta description. I think we could built from that to include other meta-data (such as version, author, etc.).
This is the first version of the command. I think it's better to stop here for now, let users test it, play with it, etc. and see what's asked.
In the future, I think we will need to rework how a plugin …

cli: sopel-plugins (basic version)

---

sopel/modules/meetbot.py
sopel/tools/__init__.py

So, at first, I was going to deprecate the `Ddict` class, which can be replaced by `collections.defaultdict` since Python 2.5. I suspect it was very useful when the bot had to support Python version such as 2.2 or 2.4 (which used to be quite popular for a long time).
However, I could not get the proper deprecation warning: decorating the `__init__` method didn't give me what I wanted.
So I decided to allow this usage of the `@deprecated` decorator:
```
@deprecated  # as it is now
@deprecated()  # because why not
@deprecated(reason='obsolete')  # chose your message
@deprecated(version='7.0', removed_in='8.0')  # deprecated in 7, removed in 8
@deprecated(reason='obsolete', version='7.0') # deprecated in 7, no "removed in" yet
@deprecated(reason='obsolete', version='7.0', removed_in='8.0') …
```

tools: add optional arguments to deprecated, and deprecate Ddict

---

sopel/modules/reddit.py

A couple years ago, reddit added support for marking posts/links as "spoiler", obsoleting the hack that I guess some subs were using. No longer does the NSFW (`over_18`) flag need to do double duty!
This frees the Sopel project from having to maintain a list of spoiler-enabled subreddits (which was apparently never updated, anyway).
Channels can also be marked as "spoiler-free" now, separately from their "sfw" status. You can have a safe-for-work channel that still allows spoilers, or a spoiler-free channel that still allows lewds. Freedom!
This is a draft for now, because it's based on #1505's branch. Once that's merged, I'll promote this to "ready for review". Feel free to bikeshed in the meantime—especially command name.
Additional code cleanup could stand to happen—this plugin doesn't …

reddit: spoiler update

---

.coveragerc
sopel/cli/run.py
sopel/coretasks.py
sopel/modules/etymology.py
sopel/modules/lmgtfy.py
sopel/modules/meetbot.py
sopel/modules/reddit.py
sopel/modules/search.py
sopel/modules/tld.py
sopel/modules/translate.py
sopel/modules/url.py
sopel/modules/wiktionary.py
sopel/tools/web.py
sopel/web.py
test/tools/test_tools_web.py

This is not ready (both merge-conflicted _and_ unfinished), but I'm shamelessly stealing PR number 1616 because it's a cool number. I should have opened a WIP PR for this weeks/months ago, anyway.
I've been talking about this for a while, and already wrote the migration guide section on it a while back. It's definitely happening… once I have a chance to rebase & finish this.

Transition `web` -> `tools.web`

---

dev-requirements.txt

0.4.6 added warnings for the annotations feature (we don't care about it yet), and dropped Python 3.3 support (we care about that still).
We'll make sure to use 0.4.5 or lower in tests.
There haven't been any CI builds on this repo in the last few days, which is why this caused a surprise failure on #1675. `flake8-future-import` 0.4.6 was released only 2 days ago.

dev-requirements: cap flake8-future-import version

---

docs/source/configuration.rst

doc: fix misuse of py:module replaced by py:currentmodule

---

sopel/db.py
test/test_db.py

This aims to resolve issue #1501. 
The one thing I was uncertain of is if we need to bother using `.lower()` like we do with channels.
----
@dgw edit: Closes #1501

db: add methods for values associated with a plugin

---

sopel/bot.py
sopel/module.py
test/test_module.py

Not much to say: fix [main part of] #1619
(editorial by @dgw so GH won't close the other issue)

module: fix decorator multiple-use inconsistency

---

sopel/modules/currency.py

This PR combines the fiat currency rates and the cryptocurrency rates into one global variable `rates` instead of keeping the two separate.
This was done to allow better cross-compatibility between the two sources, allowing one to look up a conversion from a currency in one table, to a currency in the other.
To do this, a change of API was also done, as the old API used a weird and inflexible way to look up conversions.
The code also changed some variable names that I didn't like. mostly the "of" and "to" variables were changed to base and target respectively. 
This change also entirely eliminates the need for a separate crypto rates function.

currency: switched crypto api and combined rates to allow cross-lookup

---

test/test_module.py

For some reason [assertions about compiled regex fail with Python 2](https://github.com/sopel-irc/sopel/commit/8eb80dd39fa703cc8d0379573aa1adc552a95fa0#commitcomment-34920303).
We don't know why, but at least now we make assertions about the patterns, and not the compiled regex objects. This should prevent the false-negative on Travis CI (I hope).

test: fix py2 inconsistency with regex ID

---

sopel/cli/config.py
sopel/cli/run.py
sopel/cli/utils.py
test/cli/test_cli_run.py
test/cli/test_cli_utils.py

I used to left a comment like this:
```
```
But no more. Now, you can use `--config-dir <configdir>` for that. This option provides the location to look for configuration file. Note that this does **not** replace and must **not** be confused with the settings's homedir, which is used internally by Sopel once it is started.
**Edit**: used to be `-H/--homedir <homedir>`

cli: add --config-dir common option

---

docs/source/configuration.rst
sopel/config/types.py
test/test_config.py

See the description of #1626 for more information.
Note: I had to upgrade the `test_config.py` file to use py.test instead of unittest. We should be fine with that.

config: split ListAttribute values on newlines

---

sopel/config/types.py
sopel/modules/admin.py

If the value to be set is ever literally 'None' (string), then the setting is set to actual `NoneType` `None`. When a true `None` is set to a config attribute, the setting will essentially be reset to the default value. I feel this should be the expected behavior; i.e., a user should not be able to set a null value for something with a default, because presumably, that default is there for a reason.
---
Testing: _(see #1554 for steps)_
```python
...
class AdminSetTestSection(StaticSection):
test_setting = ValidatedAttribute('test_setting', default=None)
test_list = ListAttribute('test_list', default=['a','b','c'])
...
@sopel.module._privmsg
@sopel.module.commands('ast-show')
def show(bot, trigger):
bot.say('repr: "{}", type: "{}"'.format(
repr(bot.config.admin_set_test.test_setting), …
```

 admin: add unset command

---

sopel/modules/clock.py
sopel/tools/time.py

Fixes #1591 
**Edit**: after IRC conversation, this PR became bigger and bigger, so its scope is now from "fix an oddity in the clock plugin" to "these clock/time stuff are too odd to keep them like that".
It's a nice revamp that tries to keep the convenience of existing commands with less confusing or odd behaviours.
---
Instead of using the default user/channel/bot's timezone, when `.time` is used **with** a timezone, Sopel displays an error message if this timezone is invalid:
15:12:06 <@Exirel> .time
15:12:07 <Sopel> 2019-05-09 - 13:12:06UTC
15:12:20 <@Exirel> .time CET
15:12:20 <Sopel> 2019-05-09 - 15:12:20CEST
15:12:33 <@Exirel> .time Not/A_Timezone
15:12:33 <Sopel> Could not find timezone Not/A_Timezone.
While I was working on that plugin, I spent the extra time to clean its …

clock: improve timezone guessing and refactor time-related utility

---

sopel/coretasks.py
sopel/loader.py
sopel/modules/admin.py
sopel/modules/find_updates.py
test/test_loader.py

Helped @deathbybandaid with `@event` decorators not working and realized that this specific problem comes up _a lot_, relatively speaking, when Sopel users have trouble writing custom plugins.
Obviously our documentation doesn't do a great job of making sure plugin devs know that `@rule` is required along with `@event`. But rather than fix the documentation, I decided to do the user-friendly (developer-friendly?) thing and make it so `event` is considered triggerable just like a command or rule, and so it will also get the default `.*` rule applied if necessary once registered.
An early version of this patch (pre-publication) also applied this default rule to intents, but:
* There's only one meaningful intent value (`'ACTION'`), which almost always requires an explicit rule anyway.
* …

loader: default rule for events

---

sopel/modules/seen.py

Now that #1560 has been merged, let's use it.
This changes the reply to "seen" commands:
before
`nickname: I last saw other_nickname at 2019-05-29 - 23:04:13UTC in here, saying gotta go`
after
`nickname: I last saw other_nickname in here 45 days, 4 hours ago, saying: gotta go`
I don't know if the timestamp should be included in the reply or not.

seen: Improve readability of information

---

sopel/coretasks.py

When processing the return from a WHO request, it seems that Sopel is not updating the away information for the users.  This pull request adds that update to the user records.
This provides part of the solution to Issue #1659 : User's "away" status always "None"

coretasks: update away status based on values returned from WHO call

---

sopel/coretasks.py
sopel/tools/target.py

Add an interval event to periodically issue a WHO request to keep user information up-to-date.
This provides part of the solution to Issue #1659 : User's "away" status always "None"

coretasks: Periodically send WHO to keep user information up-to-date

---

sopel/tools/_events.py

I've seen some tutorials/docs around the web use the modern spelling of this numeric's name. In the interest of making working with Sopel as easy as possible, I think it's worth including both spellings.
This is akin to HTTP's "Referer", which is spelled incorrectly in the HTTP standard but is sometimes spelled correctly in related standards (for example, the DOM spec).
Because this change was so simple, I decided to just open a one-line PR instead of wasting time with an issue discussing the pros and cons. I'm interested in feedback from any and all parties as to whether this really seems like a good idea.

tools.events: add alternate spelling of 462 numeric

---

sopel/bot.py
sopel/cli/run.py
sopel/cli/utils.py
sopel/config/core_section.py
sopel/coretasks.py
sopel/irc.py
sopel/logger.py
sopel/modules/bugzilla.py
sopel/modules/currency.py
sopel/modules/help.py
sopel/modules/ip.py
sopel/modules/ipython.py
sopel/modules/reload.py
sopel/modules/safety.py
sopel/tools/__init__.py
sopel/tools/jobs.py

Fix #1337 
Python built-in logging package makes a lot of thing way easier: no more raw log manually added to a file, no more a scaffold of try/except because opening a log file could be a problem... everything better now.
Of course, this isn't 100% ISO-functionnal, because that's not the point. And I'm also sure we could spend a ridiculous amount of time to make sure we have a 100% perfectly consistent logging system everywhere.
But I believe it's a good first step. Something that we can be proud of, and build upon. It's still better quality code than it was!

[core] Rework logging

---

sopel/coretasks.py

On servers that don't support away-notify, the _periodic_who task would cause `AttributeError: 'Identifier' object has no attribute 'last_who'` every 30 seconds.

coretasks: fix last_who AttributeError

---

sopel/loader.py
test/test_loader.py

When `clean_callable` runs on a callable, it automatically adds an `event` attribute: until now, the `is_triggerable` would return `True` for that callable after that. The problem is that, upon reloading the bot (after a timeout, a KILL message, etc.), the `event` attribute would cause job callables to be wrongly counted as triggerable. Thus, they would be registered with a 'match-any' rule, and throw errors on every message thereafter.
This bug is the result of a 5+ year old behavior (adding default `event` to all callables), plus a few-week-old change that would allow `event` to be considered as triggerable by default, without `rule`. We caught it because of a lucky Sopel Rockstar whose bot running from `master` happened to receive a KILL message.
This bug was only in master and didn't …

loader: is_triggerable rejects jobs

---

sopel/bot.py
sopel/loader.py
sopel/module.py
sopel/tools/__init__.py
test/test_loader.py
test/test_module.py

As per my idea in Issue #1658, this is my attempt to integrate an `action_commands` command structure to Sopel.
There are still things to work out here, I'm sure. I copied elements I saw in `intents`, `commands`, and `nickname_commands`. I am very well aware the docstrings will definitely need work, as well as tests added.
I'm also not happy with the import line adjusted, and will likely fix that with `()` later.
This is more/less a draft PR, but my brief tests were very successful.

module: add action_commands decorator

---

sopel/config/core_section.py

Without this option specified, we get the Python default format, which is (among other problems) completely devoid of timestamp information.
This format, devised by @Exirel while refactoring the logging mechanism, outputs the timestamp, the package that generated the log line, the log level of the line, and (finally) the actual message.
We'll go from:
Registered 42 plugins, 0 failed, 0 disabled
to:
[2019-10-21 12:47:44,272] sopel.bot            INFO     - Registered 42 plugins, 0 failed, 0 disabled
Once this hits the stable release, it will become quite a bit easier to follow along with bug reports!

config: add a default `logging_format`

---

sopel/config/types.py
test/test_config.py

In a ListAttribute, a value can start with a #, which is then considered as a comment by the Config reader. This is bad news, as channel names usually start with a # (they can start with a & too, which is less common on freenode).
To prevent this, what I do is:
* quote the item only if necessary
* unquote it if it correspond to a very specific pattern `"#<name>"`
This way, we can have this ListAttribute:
channels =
"#sopel"
&private
Edge case like `"&something"` won't be unquoted, because they don't match the exact pattern!
@dgw it replaces your PR #1689 because my first idea wasn't really on point. It would lead to a myriad of edge cases and unforeseen consequences. This one is, I believe, better, and doesn't change how current config are written.

config: quote ListAttribute items when required

---

sopel/modules/dice.py

Uses # to denote comments so users can say `.dice 1d20 # for initiative`. It just discards the comment so the output is cleaner.
Old output: `You roll 1d20 # for initiative: (12) # for initiative = 12`
New output: `You roll 1d20: (13) = 13`

dice: Add better comment functionality

---

sopel/irc/backends.py

Actual behavior was reversed from before: `verify_ssl = True` ignored things like self-signed certs, and `verify_ssl = False` threw errors for self-signed certs instead.
Requesting review directly from @Exirel because he literally wrote the entire affected file.

irc.backends: fix behavior of `core.verify_ssl` setting

---

sopel/bot.py

The added comment describes this, but to recap: Checking if the trigger originator is blocked before knowing if the function passes all the run conditions leads to logging that the triggering user was "prevented from using" something they wouldn't have actually triggered.
Think PRIVMSG from ignored users printing out a list of "prevented" functions like AUTHENTICATE handlers from `coretasks`. That's silly.
----
I didn't want to put this in the commit message (it's kind of unnecessary to describe the problem), but here's a sample log line from my `master`-based bot:
````
[2019-10-26 14:36:46,763] sopel.bot            INFO     - [nick]Amatsukaze-chan prevented
from using unobot.uno_glue, sopel.coretasks.retry_join, sopel.modules.version.ctcp_source,
sopel.modules.version.ctcp_version, …
```

bot: don't spam logs about preventing run of unmatched funcs

---

sopel/coretasks.py

Only update the 'away' value for a user if the value passed to the `_record_who` function is not None.
See the discussion at https://github.com/sopel-irc/sopel/pull/1663

coretasks: Only update user 'away' value if value passed is not 'None'

---

sopel/bot.py

thijseigenwijs on IRC reported that the bot doesn't update privilege tracking when it's the one to change a mode. This is because the server's MODE message is ignored by the echo suppression. This PR changes the echo suppression to only suppress PRIVMSG and NOTICE events.
- Can we assume the event will always be upper case?
- Any others that should be suppressed?

bot: only suppress echo for PRIVMSG and NOTICE

---

sopel/trigger.py

When echo message is simulated it is dispatched the message with '\r\n'
appended to the end. PreTrigger expects the message to not to have any
newline or carriage return characters at the end of the message.

irc: Don't write line ending twice.

---

docs/source/api.rst
sopel/tools/web.py

Draft because it's based on the #1616 branch, which isn't yet merged.
See 6d53ced for the relevant changes. I'll keep an eye on this after merging its parent.

Document `tools.web` package

---

sopel/module.py

Apparently `event` was left out of the `__all__` list. I question whether we should keep it, since it exports literally every name in the module anyway, but that's for another time.
Right now, the important thing is that `event` is now exported properly, and the docstring has been updated to account for the fact that a default `rule` is now set if an event callable does not have one.
How this didn't come up before, I have no idea. Being left out of `__all__` means that `event` wasn't included in the Sphinx docs, and things "should" break when trying to use e.g. `from sopel import module; @module.event('FOO')`… But Python's import machinery is fickle and likes to fill in module dictionaries based on other imports in the program. (Can't quickly find a reference page about this for linking, …

module: fix `__all__` nonsense & docs for `event`

---

sopel/modules/choose.py
sopel/modules/dice.py

Could have moved it to `rand.py`, but it doesn't *really* fit in any better there. There's very little cost to having a standalone file for this command aside from possibly breaking exclude settings in existing Sopel installations (and we're already adding other new modules in 7.0).
Made sure this new file credits all the right people. Namely, I added Exirel to the header, because he did a significant chunk of work on this function last year.

dice, choose: extract `.choose` command into own module

---

docs/source/configuration.rst

After we got a question about that on IRC, I thought it could be a good idea to improve the documentation for nick, user, and name.
Note: I'd like to have #1668 merged so the doc stop complaining about that stupid mistake I made.
Also: `.. highlight:: ini` can be used to remove the usage of `.. code-block:: ini` in the whole file, since we don't show Python code in that particular file, but a lot of `ini`-like code sample.

doc: more about nick, user, and name

---

sopel/modules/calc.py
sopel/modules/search.py
sopel/modules/wikipedia.py
sopel/tools/web.py
test/tools/test_tools_web.py

Also added tests for the old `quote()` function/shim and the new `unquote()` thing. They're even using `@pytest.mark.parametrize`! (And also using a cheeky `zip()` trick that @Exirel might think is "not dumb enough" for using in a test file. 🤐)
Aside from the obvious hope that anyone else still thinks this is a good idea (it's been around for a _while_ in #1346), I also hope that this merges cleanly with #1669, without any need to rebase crap later. It's not a big deal, but I do like the `gitk` graphs we get from merging un-rebased PRs that were developed in staggered parallel and not necessarily merged in order. 😼

tools.web: add `unquote()` function

---

sopel/tools/time.py

Instead of trying to coerce zone names all the way into something we can throw into an `in pytz.all_timezones` statement, all we have to do is rearrange the bits just enough to let `pytz.timezone()` take over. Its built-in normalization routines are plenty comprehensive, and if we make use of them there's no need to reinvent the wheel.
Updated the docstring for `validate_timezone()` to match. We aren't expecting that zone names like "EDT" will actually work. Neither 6.6.x nor the code this replaces will match that example, so we're not losing any functionality. Most of the three- and four-letter zone abbreviations I tried, in fact, fail because they aren't specific enough (might refer to one of multiple zones around the world). This is why we have the `tz` page users can visit if they …

tools.time: fully utilize pytz to validate timezones

---

sopel/modules/remind.py

With tz specified, it will be used if valid. If it's not valid, we fall back to either the user's default timezone (if set) or UTC (if not).
With tz not specified, this fixes UTC being used even if the user has a default timezone set.
Requesting @Exirel's review, as this directly relates to a previous patch of his (from #1590).

remind: fix default_timezone in .at command when tz not specified

---

sopel/coretasks.py

This fixes an issue with similar modes being truncated when the zip is converted into a dictionary.
```
In [1]: modes = ['-o', '-o', '-o']                                                                                                                                                                         
In [2]: nicks = ['a', 'b', 'c']
In [3]: for (mode, nick) in dict(zip(modes, nicks)).items(): 
...:     print(mode, nick) 
...:                                                                                                                                                                                    
-o c
In [4]: for mode, nick in zip(modes, nicks): 
...:     print(mode, nick) 
...: …
```

coretasks: fixing bot truncating users with same mode

---

sopel/loader.py
test/test_loader.py

It turns out there was also a mistake in the `clean_callable_defaults` test (checking `func.rate` again instead of `func.channel_rate` the second time).
This feels messy because of all the duplicated assertions, but I'm too dumb (today?) to think up a better way. Hoping that @Exirel (who is _far_ more familiar with `pytest`) might have a suggestion or two.
(I'm half expecting to completely overwrite this PR at a later date with some much-improved alternative implementation, honestly.)

loader: don't add defaults to non-triggerables in clean_callable

---

sopel/modules/admin.py
sopel/modules/dice.py
sopel/modules/invite.py
sopel/modules/lmgtfy.py
sopel/modules/meetbot.py
sopel/modules/unicode_info.py

The ability to use multiple examples, for instance, means we don't need (or want) examples with "or" in them any more.
Also fixed some "weird" or unclear stuff while I was looking around.
Should resolve #1019.

modules: Tweak some old examples to use new features

---

sopel/config/types.py

There's a lot to parse (ha!) here, but most of it is pretty obvious in purpose. The one thing I think I should explain is why all the `parse()` and `serialize()` instances have their own docstrings now.
It's because I was having fun! Just kidding (sort of). It's actually because Sphinx autodoc pulls the docstring from the parent class's method if a subclass's overriding method doesn't have a docstring of its own. In hindsight, writing new docstrings might have been *more* work than the alternative (setting `autodoc_inherit_docstrings = False` in `docs/conf.py` and checking to see if anything broke), but what's done is done at this point. We can still change the setting later.
Also of note: I removed a reference to some feature of `StaticSection.configure_setting()` that never worked …

config.types: doc ALL the things!

---

sopel/modules/instagram.py

Sometimes Instagram doesn't expose its payload: probably some loading errors or something alike. Since we can't do anything about it - usually all you can do is retry later - the bot now say so (and log an exception).
This fix #1667

instagram: catch parse errors

---

sopel/modules/find_updates.py
sopel/modules/meetbot.py
sopel/modules/translate.py
sopel/modules/url.py
sopel/modules/xkcd.py

plugins: remove nonsense uses of core.verify_ssl

---

sopel/modules/search.py

Bing doesn't need it. Unquoting breaks URLs that contain spaces.
#1265 and associated changes later in the 6.x cycle introduced this unquoting, without any clear reason why. It doesn't appear to fix anything (not that my suite of test queries is _that_ exhaustive).
As a bonus, we shed the entire block of py2/py3 shimming for `unquote`.
Also of note: This reduces the core plugin set's need for #1681, but it'll still be good to have.

search: don't unquote DDG result

---

sopel/modules/remind.py

That was a no-brainer to fix #1644

remind: use reply in case of error fix #1644

---

sopel/modules/tell.py
test/modules/test_modules_tell.py

This fix #1151 
* `config.tell.use_private_reminder` (y/n) [n]: send tell/ask reminders as private messages
* `config.tell.maximum_public` [4]: maximum number of tell/ask reminders to send as public messages before sending them as private messages
As a bonus point: minor refactoring with unit tests.

tell: use config to send reminders as private messages

---

sopel/modules/remind.py
sopel/modules/tell.py
test/modules/test_modules_remind.py

Instead of using the bot's nick and configured host (to connect to), let's use the config `basename`. This matches the default SQLite DB filename and (as of #1547) the names used for Sopel's log files.
Closes #1359. Labeling "Documentation" as I need to write a new section covering this for the upgrade guide in sopel-irc/sopel.chat#17 (already referenced here in the help links given if the migration fails).

remind, tell: Use config name in fake `.db` files

---

sopel/bot.py
sopel/loader.py
sopel/test_tools.py
sopel/web.py

I decided to do a search of the code for things marked to remove for version 7.0
I don't see anywhere else in the repo where this .stats dictionary is used, so it may be as simple as killing this single line?
I also intend on going through the code to see if there are other things that should have been removed in prior releases (I doubt it though)

cleanup: remove things marked for version 7.0

---

docs/source/configuration.rst
sopel/config/__init__.py
sopel/config/types.py

Using the latest stable Sphinx version (2.2.0), I had several errors in the `configuration.rst` file when building the documentation. So I fixed them.
Note that `::`  is the way Sphinx knows that the following block is an example of code, so it syntax highlighting.
Another error (unrelated to Sphinx) was related to the `channels` config: now we escape these with `"#channel"`, so I modified the doc for that.
I've generated the documentation with Python 3.6 and Sphinx 2.2.0.

config: fix documentation errors

---

sopel/module.py
test/test_module.py

Fresh from my well-rested (not really) keyboard\* comes this: a new plugin decorator. It lets you require that a user be authenticated to network services (NickServ or whatever) to use a given function.
I added a test for the new decorator, fixed a mistake in `require_chanmsg`'s test, and made all the `require_*` decorators consistent in terms of code structure. A couple of them were using a silly trick to get the `bot` and `trigger` args by name. Someone please take a good look at those changes too, to make sure I didn't forget something dumb (like how I almost forgot to pass `bot` and `trigger` to the actual function after checking the conditions and had to amend the commit).
Here's a rendered preview of the documentation for `@module.require_account`:
This idea was inspired by an …

module: add `require account` feature

---

sopel/bot.py
sopel/loader.py
sopel/module.py
test/test_module.py

Decorated functions will have anything they output (via the `say` or `notice` wrapper methods; it doesn't make sense for `action` or `reply`) prefixed with the given string.
Closes #1352.

module, bot: add `output_prefix` decorator & feature

---

contrib/rpm/makerpm.py
sopel/cli/config.py
sopel/cli/plugins.py
sopel/cli/utils.py
sopel/config/types.py
sopel/irc/backends.py
sopel/module.py
sopel/modules/admin.py
sopel/modules/help.py
sopel/modules/isup.py
sopel/modules/remind.py
sopel/plugins/handlers.py
sopel/tools/__init__.py

Since it seems running LGTM locally isn't a thing, I have to open this PR and hope that it does everything I think it should. I _think_ this fixes 18 alerts. If the actual results don't match, I'll figure it out Soon™ (but probably not within the next 24 hours).
**Edit:** Looks like easy fixes (only the exception-comment changes failed, and it seems to be an inconsistency in LGTM's documentation about whether a space is allowed).

qa: fix additional LGTM alerts

---

sopel/modules/calc.py
sopel/modules/py.py

This is mostly so it's easier to disable `.py` (which relies on an external web service and may encourage skiddies) while keeping the basic calculation command available.

calc: extract .py command to its own file

---

test/test_bot.py

This will probably generate a very small merge conflict with #1697 in a way that is not a problem, since it adds tests and an import.
My main concern at this point is: will it work as intended with Python 2.7?
Also: yay, tests! :unicorn:

test: URL callbacks (register, search, unregister)

---

sopel/modules/py.py

Adds an option to configure the [Oblique](https://github.com/sopel-irc/oblique) endpoint Sopel should use for `.py` commands.
Based on #1710 branch, so will begin its life as a draft.
Note to self: Rescue the good bits from your last time implementing this (before deciding to split `.py` into its own file). See 0d4fc85a9d98327b6844565373b01a26ce43ca16, e16ae1fb01779f9807ebd0d2e38bc405fb74cb59, & abda3a61549f251b86a5b72d44b8709e8f156c10 from the forgotten `calc-config` branch.

py: configurable endpoint

---

sopel/modules/reddit.py

Got annoyed after pasting yet another Reddit comment link and seeing Sopel spit out the submission (link) info instead. This was something like a 15 minute project. Pretty easy. 😁

reddit: add comment handling

---

sopel/modules/reddit.py

Primary changes: The `reddit` plugin now understands how to detect links to images & videos hosted by Reddit itself (`i.redd.it` and `v.redd.it` URLs), and how to map those back to a submission. For images, it's the oldest submission with that link as the URL; for videos, Reddit itself redirects the short URL to a 'canonical' post (should be the first, excluding all crossposts).
Secondary changes: Enough with the `praw.Reddit()` setup being duplicated, and enough with constructing a new instance every time the plugin wants to do something. Now, it constructs just one PRAW instance at load time, and stores it in Sopel's memory for reuse.
Tertiary changes: `rpost_info()` is now Just Another URL Detector™, like the newly added media link handlers. All of them now pass just the desired …

reddit: media details (+ refactoring)

---

sopel/modules/find.py

This patch is _definitely_ easier to grok if you look at the commits separately. Together, they blend into confusing almost-overlapping changes.
The commit messages themselves are pretty self-explanatory. My main goal was improving the bot's long-term memory usage by making sure lines cached in `bot.memory` would get purged when no longer relevant. Along the way, I noticed some other years-old silliness that was impossible to resist fixing.
Saving 6 lines by optimizing out unnecessary temporary variables isn't much considering that I added ~~45~~ 48 (including whitespace) lines of cleanup handling, but… It felt good. 😛

find: optimizations

---

sopel/modules/seen.py
sopel/modules/tell.py
sopel/modules/translate.py

The `tell`, `translate`, `seen`, and `meetbot` plugins all contain match-any rules to run something on any/every message received. Even with #1724 applied, they still cause log spam whenever any ignored user speaks.
Here, I have made the relevant callables in `tell`, `translate`, and `seen` into `unblockable` functions. There's no reason that ignored users shouldn't receive `tell` messages, and `translate` & `seen` only collect lines passively for use later when commanded by a non-ignored user.
I did *not* make `meetbot`'s callable unblockable, though. That would allow ignored users to appear in meeting logs despite being blocked from using any commands. Unfortunately this means we'll still get log spam on any instance with `meetbot` turned on, but when this is combined with #1721 (which …

plugins: unblock background triggers

---

sopel/bot.py
sopel/module.py

The scenario is:
* dispatch is called for a pretrigger
* it looks into the list of callable by priority
* it triggers one of the first callables, which wants to remove a callable of the same priority
* because Python must not allow a dict to be modified while it is iterated over, Python raises an exception
If we put a lock here, Python won't raise the exception... but we'll get a deadlock. To prevent that, instead, we copy the list of callables, and return the ones that are triggered. If any of them wants to change the callables of the same priority, they won't raise an error, because we are not iterating anymore on the dict.
Hoo-ray!
@dgw have fun with my miserable grammar at 2am.

bot: fix race-condition in dispatch

---

.gitignore
docs/source/index.rst
docs/source/tests.rst
setup.py
sopel/test_tools.py
sopel/tests/__init__.py
sopel/tests/factories.py
sopel/tests/mocks.py
sopel/tests/pytest_plugin.py
test/irc/test_irc_abstract_backends.py
test/test_bot.py
test/test_coretasks.py
test/test_irc.py
test/test_loader.py

I wanted more from Sopel's test tools, for 2 reasons:
* increase the test coverage for the bot, its internals and its plugins
* help plugin authors to test their plugins
My approach in this PR is the following:
* `sopel.tests.mocks`  contains mocks: they generate fake IRC lines (User and IRC Server) or pretend to be a backend of some sort (IRC Connection Backend)
* `sopel.tests.factories` contains factories: they are helper classes, they help to create mock objects with different parameters. Each factory implements a `__call__` method, so they act as callable, like this: `mock_bot = botfactory(...)`
* `sopel.tests.pytest_plugin`: it's a plugin for pytest, that will be automatically loaded by pytest thanks to entry point. It will bring shared fixture for everyone to use, mostly generating …

test: botfactory, UserFactory, and IRCFactory

---

sopel/bot.py

Based on #1728 to avoid future merge conflict.
My initial idea was to join trigger processing threads directly in the `dispatch` method. For several reasons (including the echo-message polyfill), that's not doable.
Instead, since all I want is a way to know, access, and join processing threads in automated tests, I make sure the bot keeps track of its threads. This way, I'll be able to run a dispatch, going through all the bot's internals and machineries, and then wait for the end result in my tests.
It was a bit convoluted, but in the end I think it turned out great!
Quick note about memory consumption: this information generate a very low overhead, since running threads are kept in memory anyway by Python. All that is stored is a reference to the thread object, and every time dispatch …

bot: keep track of trigger processing threads

---

sopel/db.py
sopel/modules/adminchannel.py
test/test_db.py

I have a few places in my plugins where I follow a `get_x_value` with `if value is None: value = ...`. This adds an optional `default` argument to make that easier.

db: allow requesting a default if key not found

---

sopel/bot.py

Assigning the tuple returned by `_is_pretrigger_blocked()` to both vars instead of unpacking the values makes both of them always evaluate to `True` in Boolean contexts. Which magically blocks everyone from doing anything, unless `get_triggered_callables()` decides they're unblockable by virtue of `trigger.admin` being `True` (or if the function is marked unblockable, of course). Fun times!
Introduced by #1728 — `.blame Exirel`! I share no responsibility for missing this in code review. Nope, none at all. :P (I'm requesting his review specifically, instead of just any available Rockstar, because I want him to see this stupid little bug that he made and I missed. 😹)
Let this be a lesson to us all: Test things as a non-admin sometimes. Just in case. (New testing infrastructure should help …

bot: fix bug in blocked user detection

---

sopel/modules/reddit.py

This PR adds to the functionality of `reddit.py` by adding:
* Add a subreddit command as well as url pattern match for subreddits
```
13:32 <@deathbybandaid> https://reddit.com/r/plex
13:32 <reddit-test> [REDDIT] https://www.reddit.com/r/plex | subscribers (124733) | Created at 2008-08-16 - 06:54:02UTC | For questions and comments about the Plex Media Server. The Plex Media Server is smart software that makes playing Movies, TV Shows and other media on your computer simple.
13:32 <@deathbybandaid> .subreddit plex
13:32 <reddit-test> [REDDIT] https://www.reddit.com/r/plex | subscribers (124733) | Created at 2008-08-16 - 06:54:02UTC | For questions and comments about the Plex Media Server. The Plex Media Server is smart software that makes playing Movies, TV Shows and other media on your …
```

reddit: handle subreddits, and `u/` & `r/` references

---

sopel/cli/run.py
sopel/cli/utils.py
test/cli/test_cli_run.py

Related to #1738: I replaced 'module' by 'plugin' where it makes sense to.

cli: replace 'module' by 'plugin'

---

sopel/bot.py
sopel/config/__init__.py
sopel/config/core_section.py

This is mostly for the per-channel configuration stuff, to avoid launching the new feature with config keys that we'd have to deprecate pretty much immediately. But since I was in there, I also updated other docstrings etc. in the config submodule.
High priority because it's a release blocker (see #1738).

bot, config: s/module/plugin/ (where appropriate)

---

sopel/plugins/__init__.py

Related to #1738: I added the `~/.sopel/plugins` folder to the mix, because it's *very* easy to do.

plugins: add ~/.sopel/plugins folder

---

sopel/cli/utils.py

Was:
```
Would you like to see if there are any modules that need configuring (y/n)? [n] y
Configure safety.py - Alerts about malicious URLs (y/n)? [n] (y/n)? [n]  
```
Now:
```
Would you like to see if there are any modules that need configuring (y/n)? [n] y
Configure safety.py - Alerts about malicious URLs (y/n)? [n] 
```

cli: Fix plugin config duplicate y/n prompt

---

sopel/bot.py

When `.reload`ing a bot, hundreds of lines of tracebacks would be logged:
```
--- Logging error ---
Traceback (most recent call last):
<snip>
File "/usr/lib64/python3.7/logging/__init__.py", line 369, in getMessage
msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
<snip>
File "sopel/sopel/bot.py", line 332, in unregister
rule.pattern)
Message: 'Rule callable "%s" unregistered'
Arguments: ('handle_url_callbacks', '(?u).*(.+://\\S+).*')
```
I don't know if it's important to print the pattern that was unregistered, but it's a debug log so meh.

bot: Fix rule callable unload message argument error

---

sopel/coretasks.py

It's a very small change: as discussed in https://github.com/sopel-irc/sopel/issues/1069#issuecomment-548617872 the `TOPIC` command is not required since the server is supposed to send the required information when the bot joins a channel.
This won't fix the bigger problem, but it'll help in some cases.

core: do not send TOPIC on join

---

sopel/modules/safety.py

Details in the commit message, but the gist is implementing exactly what I described previously. This resolves #1572, assuming I haven't made any silly mistakes.

safety: rework cache cleanup logic

---

sopel/modules/reddit.py

This is a regular laundry list, honestly.
* `post_url` was end-anchored to prevent matching the same links as `comment_url`, but didn't allow for the `/post_title_slug/` usually included after the submission ID.
* `comment_url` & `post_url` used `.*` where they should have had `\S+` (whitespace is never present in reddit URLs, nor will any compenent of the link ever contain zero characters).
* `user_url` unnecessarily captured "ser" (or "") as group 1.
* So many unescaped `.`s everywhere!
Fixes post links failing to match and falling back to `url.py` title fetching, and possibly some other silly bugs. I take full responsibility for breaking `post_url` in #1720. Whoops.
Also adds error handling in `video_info()`, in case the hacky hack it uses to get the post URL fails. The errors I saw in …

reddit: cleanup & various fixes

---

sopel/db.py

This should fix the errors @deathbybandaid was seeing in https://github.com/sopel-irc/sopel/pull/1639

db: properly handling threaded sessions

---

sopel/db.py

We can tweak the docstrings and/or attribute names for consistency later. The point is, the function should now work fine no matter the `db_type`.
Closes #1745.

db: fix get_uri() to return the actual connection URI

---

README.rst
setup.py
sopel/cli/run.py

Kind of magic-number-y, but I'd rather this than duplicating `datetime` code in two places.
No, I do not feel like optimizing this out into a function that we'll remove as soon as we start on 8.0.

Prepare Sopel to adapt its output when py2 officially dies

---

sopel/bot.py
sopel/modules/reload.py

This would have saved me a good half-hour of confusion tonight, by showing me that my bot was using an (outdated) plugin file in `.sopel/modules` that shadowed the built-in plugin from `sopel.modules.*`.
I think the added `bot.get_plugin_meta()` function is helpful, and it was necessary to implement the output I wanted in `reload`, but there could be a reason I haven't thought of that makes it a bad idea. Definitely tell me if so!
Even just having the reloaded plugin's metadata in logs, and not on IRC, would have helped. I added it back to `reload` because 1) it used to show the file path before the plugin system rework, and 2) I like not having to check my terminal/log-files for things. 😛
Note: I'm putting this in 7.0 because let's face it: a lot of people are going to make updates to …

bot, reload: log/show plugin source when reloading

---

sopel/modules/reddit.py

Prevents duplicate inline media thumbnails in IRC clients that support those, and also eliminates one potential cause of looping when a channel contains multiple Sopel bots.
Closes #1767.

reddit: hide submitted URL if we matched on a media link

---

sopel/modules/find_updates.py

So I wrote this late one night, forgot to make a pull request for it, and here we are two weeks later. Maybe I held off making a PR, planning to come back and improve something first? Who knows.
Fixes #1643, at least in theory.

find_updates: error handling

---

docs/source/configuration.rst
sopel/config/core_section.py
sopel/coretasks.py
test/test_coretasks.py

This PR is meant to address #1455. It adds a `core` setting that is a `ListAttribute` of commands to perform upon successful connection with the IRC server. These commands are executed at the end of the `startup` sequence (set `MODE`s, `JOIN` channels, and now, _perform_ commands).
It depends on #1460.
**Example setting**
```
perform_commands = NICKSERV identify testbot ThisIsMy\,complexP@$sW0RD!!,JOIN #testing,PRIVMSG #testing :I am here!!
```
`raw.log`, as expected:
```
...
>>1553928396.52 NICKSERV identify testbot ThisIsMy,complexP@$sW0RD!!
>>1553928396.53 JOIN #testing
>>1553928396.53 PRIVMSG #testing :I am here!!
<<1553928396.57 :testbot!sopel@pumba.local JOIN #testing * :Sopel: https://sopel.chat
>>1553928396.57 TOPIC #testing
>>1553928396.57 WHO #testing a%nuachtf,387 …
```

core: perform commands on connect

---

docs/source/configuration.rst
sopel/config/core_section.py
sopel/coretasks.py

(based on #1750 for documentation) (may conflict with #1749)
This PR adds two things:
* `core.throttle_wait`: time waiting between JOIN/WHO batches
* a queue to process JOIN events by batches
This reuse the `_send_who` function which updates the `last_who` flag for the channels, so it fits nicely with the existing code.
That being said, I think I'll take a mental note to refactor the whole start-up sequence, because it's a nightmare to debug it.

core: throttle JOIN and WHO commands

---

docs/source/irc.rst
sopel/coretasks.py
sopel/irc/__init__.py
sopel/irc/isupport.py
test/irc/test_irc_isupport.py
test/test_coretasks.py

WIP to show a bit of the ISupport thing: my idea is to have a storage structure with the basic parsing tools at first. Then, I'll implement an actual callable, triggered by the event `RPL_ISUPPORT`, with the proper machinery to parse, update, and remove ISupport data.
This Draft version aims to open a small conversation about the design and the usability of the ISupport class.
Quick note: the ISupport class will generate immutable object. There is no good reason to mess with that, as every bit of information comes from the server itself.

core: handle 005 RPL_ISUPPORT event

---

docs/source/irc.rst
sopel/coretasks.py
sopel/irc/__init__.py
sopel/irc/isupport.py
sopel/irc/utils.py
test/irc/test_irc_isupport.py
test/test_coretasks.py

This closes #1532 by handling the `RPL_MYINFO` event and storing the info into a `namedtuple`. This PR replaces a part of #1536. (see also #1758)

core: handle 004 RPL_MYINFO event

---

test/test_db.py

This should fix https://github.com/sopel-irc/sopel/issues/1623

tests: migrating db tests to sqlalchemy

---

sopel/test_tools.py
test/modules/test_modules_remind.py
test/test_db.py
test/test_module.py
test/test_regression.py
test/test_trigger.py
test/tools/test_tools_jobs.py

This PR makes test_tools's mocks obsolete, adding deprecation warning on `MockConfig`, `MockSopel`, and `MockSopelWrapper` - replaced by the `configfactory` fixture, the `botfactory` fixture, and by the `sopel.bot.SopelWrapper` class respectively.
As far as I'm concerned, Sopel's codebase doesn't use `MockSopel` nor `MockConfig`, making sure that no part of Sopel assumes `~/.sopel/` as the homedir. We may close issue #946 once this is merged.

test: test_tools's mocks are obsolete

---

sopel/db.py

I really hate being able to execute raw SQL against the database, but this should fix the issue for anyone needing to do it

db: migrate to connectionless execution for raw sql

---

sopel/formatting.py

Skimming IRC backlog for `#sopel` brought up one thing I wanted to fix, and I figured: as long as I'm in this file, I'll just give it the #1565 treatment.

formatting: docstring overhaul

---

sopel/module.py

Part of the ongoing effort to standardize (as best we can) Sopel's docstring formatting and make use of Sphinx features to enhance the public API documentation site. See #1565.
I blame @deathbybandaid for reminding me earlier this week that `@action_commands` didn't have a note in the docs about its current mutual exclusivity with the other command decorators. 😝

module: docstring overhaul & modernization

---

docs/source/api.rst
sopel/tools/__init__.py
sopel/tools/calculation.py
sopel/tools/jobs.py
sopel/tools/target.py
sopel/tools/time.py

Tin. See #1565.
I was surprised that `tools.calculation` took the most time, which was probably mostly wasted on docstrings that don't appear in the public docs anyway, but pretty tables are always worth it… right? 😁

tools: subpackage doc overhaul

---

docs/source/trigger.rst
sopel/bot.py
sopel/irc/__init__.py
sopel/irc/abstract_backends.py
sopel/irc/backends.py
sopel/irc/utils.py

Overhauled docs for both of these modules at once because they're rather intertwined.
Touches the `trigger` docs a bit because some cross-references weren't working without `PreTrigger` being published in the built docs.
Fixed a mistake in the CAP REQ docs telling users to use the wrong prefix for required capabilities.
Even tweaked the code for loading block lists from the config, because it annoyed me that we weren't using the `ListAttribute` type's `default` kwarg. (This change is easy to back out, in case I overlooked a good reason things worked the way they did, as it's a separate commit.)
Of course, lots of other tweaks & fixes, too!

bot, irc: doc overhaul

---

docs/source/conf.py
sopel/db.py

Some of the stuff in `SopelDB` needed to reference SQLAlchemy docs, and adding those intersphinx mappings was trivially easy, so it was done.

db, docs: overhaul docstrings & add SQLAlchemy to intersphinx mappings

---

docs/source/conf.py
docs/source/configuration.rst
sopel/config/__init__.py
sopel/config/core_section.py

Besides the absolute ton of new documentation stuff, this deprecates `config.ConfigSection.get_list()` (which is ancient, unused, and made obsolete by the `ListAttribute` type).
The same intersphinx mapping addition had to be made here as in #1776 to enable easy links to the SQLAlchemy documentation. I'll deal with the merge conflict when the time comes, if Git isn't smart enough to realize that both patches have the same result.
This also enables Sphinx's built-in `autosectionlabel` extension, which turns every section heading into a `:ref:` name in exchange for keeping every section title unique across the whole documentation project. I think it's more than a fair trade.
**Related:** #1565.
**Potential conflict:** #1751 — @Exirel, if you would, please tweak the format of those …

config: doc overhaul

---

sopel/trigger.py
test/test_trigger.py

This is pretty self-explanatory. I'm opening it early to get feedback on my approach to documenting `PreTrigger` (which wasn't really documented before).
Note I'm still working over the existing docstrings in `Trigger` as of PR opening. Y'all can expect force-pushes to this branch as I find more time to work on these updates.
I expect this to be the last major documentation overhaul I do before 7.0, especially since I'm leaving the country for two weeks later this month; the few remaining submodules in #1565 are much less important (either recently written or purely internal) and can wait until 7.1.

trigger: doc overhaul

---

sopel/modules/ip.py

Works with the changes introduced on December 30 (yesterday), which were announced literally the day before I left on an overseas trip for two weeks. Obviously, I didn't see the blog post before I left. I wrote this patch on a motorcoach in the middle of the desert. (Surprisingly, I was able to validate the fix and push the changes using the bus's Wi-Fi.)
Resolves #1796
- Note: Tested the changed file manually, to avoid running the full online test suite on a motorcoach's very slow network. `make quality` is fine; Travis can report any issues in things I didn't touch when it's finished.

ip: update MaxMind GeoLite2 database fetching

---

sopel/modules/url.py
test/modules/test_modules_url.py

Silently ignores invalid URLs like `http:///` and `http://.example.com`. Includes tests.

url: Ignore more invalid URLs

---

setup.py

The check for python 3.3+ was broken, and python 2's last maintenance release is [now](https://mail.python.org/archives/list/python-dev@python.org/thread/APWHFYQDKNVYQAK3HZMBGQIZHAVRHCV2/) [scheduled](https://www.python.org/dev/peps/pep-0373/#maintenance-releases) for "mid-april" 2020.

setup: fix/update python version checks

---

sopel/modules/adminchannel.py

The regex cascade in the configureHostMask function is a little messy.
This adds support for the case in the example:
`.kickban [#chan] user1 user!*@* get out of here`

adminchannel: hostmask configuration fix

---

CREDITS
setup.cfg
setup.py

Barring anything critical, this should be _the last_ PR opened for 7.0.0. 🎉 **Edit:** Except the one with all the changelog (NEWS file) additions that I'll open when that's ready. Forgot we have a changelog. 😅
Any @sopel-irc/rockstars are welcome to review for typos/grammar, but I would like to get 👍 or 👎 from the repeat contributors I took the liberty of adding to CREDITS: @Exirel, @deathbybandaid, @RustyBower, @kwaaak, & @HumorBaby.
I'm happy to leave you off the list if you really want, or change the name shown there! I just want to recognize everyone who's been around for the long haul during the lead-up to 7.0. ❤️
----
Added mention respondents:
- ✔️ Exirel
- ✔️ RustyB
- ✔️ HumorBaby
- ✔️ kwaaak
- ✔️ dbb

Setup metadata overhaul

---

sopel/coretasks.py
sopel/module.py

On inspircd 3 with the operprefix module, as oper, create a channel. You'll have `!`. Add the bot. The bot sees you as having no modes (`0`), and you can't do anything until you +o yourself.
Might not be a 6.6.x thing, but if I don't open this now I'm not going to remember.
Future enhancements:
- Have the symbol/mode/constant stuff in one place instead of 5 (!)
- Just generate this stuff from what the server tells us when we connect

core: add inspircd operprefix !/+y channel mode

---

sopel/modules/safety.py

This fixes the following error when sopel tries to clean up the
`safety_cache`:
ERROR    - Unexpected error (unsupported operand type(s) for -: 'SopelMemory' and 'int')
Signed-off-by: Rafael Fonseca <r4f4rfs@gmail.com>

safety: properly check whether cache is too big

---

NEWS

This is a large changeset (almost 700 lines), but I'd really appreciate it if _multiple_ @sopel-irc/rockstars could look it over. Y'all are pretty likely to notice if a fix/change is missing or incorrectly described, on top of the usual proofreading for grammar/spelling. There are only a very few PRs left for 7.0.0, so it's time to get this ready.
PS: I changed my mind in the months since 0d571f8, and will probably keep all of these commits (maybe with the silly "PR 1234" references in the commit log changed to `#1234` instead—I did that to avoid spamming mentions in PR timelines during rebases).

Changelog for 7.0.0

---

sopel/coretasks.py

This allows `.block` to prevent a user from using URL handling.

coretasks: make handle_url_callbacks blockable

---

NEWS
requirements.txt

`xmltodict` technically dropped Python 3.3 in 0.12, and while it likely doesn't matter, we should try to ask for what's correct. We're also asking for 0.12.x specifically on all other versions because we don't know when upcoming EOL Python releases (e.g. 3.5) will get dropped.
`geoip2` killed off Python 3.3 & 3.4 in its 3.0.0 release. Nobody could tell from the CI tests, which kept humming along and passing (yes, THEY DO test our `ip` plugin, which uses geoip2) on all Python versions somehow, but let's be safe. We don't need any of the minor new features in geoip2 3.x, and a future release could actually break things. Being more specific about Python versions here is a non-starter for me, given that the maintainers have already shown they're willing to drop Python versions in "minor" …

requirements: tighten up version ranges

---

sopel/bot.py
sopel/modules/bugzilla.py
sopel/test_tools.py
test/test_bot.py

Introduces the API change #1805 will require. The test diff isn't particularly minimal because this is a reduction of that patchset for 7.0.

bot: require callback to unregister URL handler

---

NEWS
docs/source/api.rst
docs/source/conf.py
docs/source/trigger.rst
sopel/bot.py
sopel/config/__init__.py
sopel/config/types.py
sopel/db.py
sopel/irc/abstract_backends.py
sopel/module.py
sopel/plugins/handlers.py
sopel/test_tools.py
sopel/tests/factories.py
sopel/tools/__init__.py
sopel/tools/time.py
sopel/trigger.py

After updating the preview site to build with 7.0.0 RC2, I noticed a broken cross-reference in the new docstring for `db.connect()`. So of course, I went in search of a way to make Sphinx check for broken references and warn about them automatically. And of course, that led to fixing all the other broken or wrongly formatted references in our documentation.
Perfectionism at its finest? 😁
The only thing that I don't really love is that hack to link `pytest` *with monospace formatting* in `module.py`. Such a shame reST doesn't support nested inline markup…

Final 7.0 docs cleanup

---

sopel/modules/reddit.py

Not going to shoehorn this one into 7.0.0 (which I want to release tomorrow, since our RCs have been running well over the last week), but it can go into our very first 7.0 bugfix release.
Makes it much easier to go view the comments when someone shares a direct link to some image/video from Reddit on IRC.
Before:
```
[REDDIT] Title of post to r/subreddit | 193 points (100.0%) | 8 comments |
Posted by username | Created at 2020-01-23 - 19:05:19UTC
```
After:
```
[REDDIT] Title of post to r/subreddit | 193 points (100.0%) | 8 comments |
Posted by username | Created at 2020-01-23 - 19:05:19UTC | https://redd.it/123456
```

reddit: show shortlink of post when expanding media URLs

---

sopel/irc/backends.py

Inaccidently broken of connection leads to 'cannot join current thread'
What does this do? What problem does it solve? Does it resolve any GitHub issues?

irc.backends: Hotfix thread error on connection loss

---

sopel/cli/run.py

We can bikeshed exact wording or placement of blank lines, if anyone has a better idea.
Example output:
```
$ sopel
Sopel 7.0.1.dev0 (running on Python 3.6.9)
https://sopel.chat/
Loaded config file: /home/dgw/.sopel/default.cfg
[2020-03-18 19:22:05,142] sopel.bot    INFO     - Loading plugins...
[startup sequence continues]
```
Note: This will need to be done somewhere else, later in the sequence, if we want the config file to appear in logs. It could be worth delaying all the startup messaging (welcome, version number, etc.) until logging has been set up, to be fair.

cli.run: Show loaded config file at startup

---

sopel/cli/utils.py

See #1819. @Exirel please give this a quick once-over for dumb typos. 🙏

cli.utils: fix outdated `find_config()` docstring example

---

sopel/modules/clock.py

Adds an error message to the setchanneltz function if you are not opped up.

clock: add feedback to `.setchanneltz` if not OP

---

sopel/modules/units.py

Reported on IRC by sukil.
Before:
```
<dgw> .mass 16 oz
<Sopel> dgw: 453.60g = 0.00 oz
<dgw> .mass 17 oz
<Sopel> dgw: 481.95g = 1.00 oz
```
After:
```
<dgw> .mass 16oz
<SopelTest> dgw: 453.60g = 1 pound
<dgw> .mass 17oz
<SopelTest> dgw: 481.95g = 1 pound 1.00 ounces
```
- Relying on Travis for this. My local `make quality` reports a _ton_ of errors because I'm in the middle of adding another style-checking plugin. 😁

units: fix mass when given exactly 1 pound

---

sopel/modules/remind.py
sopel/modules/tell.py
test/modules/test_modules_remind.py
test/modules/test_modules_tell.py

I don't get the satisfaction of tagging this "closes #&lt;number&gt;", but it does fix a bug with loading stored reminders when certain IRC formatting (I encountered it with italics) is included in the message.
@Exirel will be glad to see I added a test for this bug to help keep it from being reintroduced. :)

remind: fix loading DB when a reminder contains italics

---

sopel/bot.py
sopel/plugins/handlers.py

Annotate callables with the source plugin name during plugin registration. Use that name when applying per-channel configuration settings instead of the Python module name.
Old solution: ~~Translates plugin names given in the config to the module names that would/will be returned by `func.__module__`, and uses those when filtering per-channel configuration.~~
Resolves #1839.
- I can't reasonably run `make quality` locally due to other long-term work on adding new flake8 checks that currently generate hundreds of warnings, so I'll leave this unchecked even though `make test` does pass.
- ~~Most of it. I made sure it works for core plugins and entry-point plugins, and the debug log output of module names I used to get this far tells me it _should_ also work for `sopel_modules` plugins and …

bot: fix per-channel configuration by plugin names

---

sopel/__init__.py

This patches the `_version_info` function to ACTUALLY use the version variable passed to it in the regex match.
This should make the `find_updates` module do a better job checking that `version < latest_version`.
The current situation would always compare the local version to itself.

Patch `version` variable not being used in regex

---

sopel/bot.py
sopel/coretasks.py

With this change, URL callbacks are no longer called outside the enforcement area of rate-limits, per-channel configuration, etc.
See #1812.
I'm initially ignoring the checklist below because I expect @Exirel will look at this Soon™. He'll either use it as a starting point and add tests, or propose an alternative implementation (and add tests).

bot: route URL callbacks through `bot.call()` too

---

sopel/tools/time.py

Patch looks big, but that's because Python doesn't have braces. 😏 (Just kidding, I'd update the indentation even if it did. I'm not a monster.)
Fixes #1841.
Setup:
```
>>> from sopel.tools.time import seconds_to_human
```
Before:
```
>>> seconds_to_human(0)
' ago'
```
After:
```
>>> seconds_to_human(0)
'0 seconds ago'
``` 
- Caveats apply as with all my recent PRs: `make quality` is currently useless in my local environment

tools.time: zero is a special case for `seconds_to_human()`

---

docs/source/configuration.rst
sopel/config/core_section.py
sopel/tools/time.py

Someone asked on IRC if Sopel supports channel "keywords", which I took to mean `+k` "key" or password. I noticed the documentation didn't show any examples of that, so I made some tweaks.
Whether that was the right interpretation of the question or not, we should include keys in the docs.
- Kinda N/A; doesn't touch code. I tested the docs build locally.

docs: modify channel config examples to show password/key usage

---

sopel/modules/xkcd.py

This is the smallest patch I could devise, at the expense of being kinda messy. Ideally only one function would need to handle the `commanded` argument, but due to how the code is already structured it has to get passed around a bit first.
We could probably do with a small rewrite of this plugin, but not for a bugfix release. It might happen later if someone feels like it.
Closes #1847.
- [Insert my recent standard disclaimer about local flake8 warnings]

xkcd: suppress link if triggered by a URL match

---

sopel/modules/search.py

Bing results look different than they used to; the HTML has changed a little. Seems like Bing also sends fake "No results" pages to the default requests user-agent, so we now spoof for both DDG and Bing.
Not knowing how long this was broken, I added an example test for Bing. Hopefully it will help us catch future breakage, while not becoming an annoyance. If it starts failing at random too often, I'll nuke it.
This should also fix the xkcd plugin not being able to find comics by keyword, since it relies on the search plugin's Bing function.
- I ran tests with `coverage3` and `-k 'test_example_bing'`, so I only paid attention to tests directly related to this change.

search: some Bing fixes (UA spoofing, example test, regex)

---

sopel/modules/search.py

The OL element isn't always in the same place. Sometimes there are other things between it and the first LI.

search: Bing regex needs to be less specific

---

sopel/loader.py
test/test_loader.py

Non-admins hit an AttributeError on URL callbacks: 'function' object has no attribute 'unblockable'. The loader wasn't passing them through `clean_callable` to apply default attributes during `clean_module`.
This could be done without a new "limitable" category (just let URL callbacks live under the "triggerable" umbrella), but... it's more fun to micro-optimize memory usage for no reason.
Also: Fixed a stray assertion in loader tests that was checking a variable's identity property instead of equality.

loader: make sure URL callbacks are ready to pass through `bot.call()`

---

docs/source/bot.rst
sopel/irc/__init__.py

Sphinx 3 started complaining about duplicate object descriptions. I'm too lazy to keep updating my local Sphinx (was still on 1.8.x until today), but I spotted the warnings in Netlify site build logs.
Resolves these warnings (taken from the sopel-irc/sopel.chat#29 merge build on Netlify):
```
6:45:58 AM: /opt/build/repo/_sopel/sopel/bot.py:docstring of sopel.bot.Sopel.name:1:
WARNING: duplicate object description of sopel.bot.Sopel.name, other instance in bot,
use :noindex: for one of them
6:45:58 AM: /opt/build/repo/_sopel/sopel/bot.py:docstring of sopel.bot.Sopel.nick:1:
WARNING: duplicate object description of sopel.bot.Sopel.nick, other instance in bot,
use :noindex: for one of them
6:45:58 AM: /opt/build/repo/_sopel/sopel/bot.py:docstring of sopel.bot.Sopel.user:1:
WARNING: duplicate …
```

docs: remove duplicate entries for `bot.{name,nick,user}`

---

sopel/modules/xkcd.py

Add a special rule to respond to vanilla `https://xkcd.com` links with data for the latest comic.

xkcd: Parse latest comic when base URL is linked

---

sopel/modules/wikipedia.py

Module will now retrieve text from the relevant section
instead of the beginning of the article irrespective of
section designations in the URL.

wikipedia: retrieve section summaries

---

sopel/bot.py

The "_command_groups" attribute is used to generate the documentation for plugin's command (there is an old piece of code for some undocumented feature here but that's something else).
The problem is that it tries to derive the plugin's name from the Python module the callable come from, instead of, you know, the actual plugin's name.
Since we added the "plugin_name" attribute on all callable back in 8776354b7aae7087f090a0989181400899f6c0d0 (see #1840) we can now use it safely for the command group.
One-line fix for you all!

bot: fix plugin name in _command_groups

---

docs/source/configuration.rst

Tin.
Current (as of 7.0.3):
New (this PR):
- This doesn't touch code.
- Ditto.

docs: add examples for owner/admins config values

---

sopel/modules/url.py

What does this do? What problem does it solve? Does it resolve any GitHub issues?
> Adds 'Accept' and 'Accept-Language' headers and spoofs 'User-Agent' while increasing max_bytes so that problematic sites work better for fetching titles

url: tweak default_headers and max_bytes for improved URL titles

---

sopel/tools/__init__.py

* New `warning_in` parameter to `@deprecated` decorator to allow documenting & decorating a deprecated function all at once even if it shouldn't warn until some future version of Sopel
* `tools.get_input` will become unnecessary in Sopel 8.0 (it's a py2 compatibility shim), so it's now deprecated—but won't emit warnings until we actually do drop py2 in Sopel 8
Yeah, this is a messy diff. We probably should have just moved `@deprecated` to the top _last_ time there was an issue with using it to decorate something defined earlier in the same file, but didn't. Viewing this one commit-by-commit will help.

tools: add `warning_in` arg to `@deprecated`; deprecate `get_input`

---

sopel/modules/ping.py

ping: add .ping command

---

sopel/modules/admin.py

Just fixing a bit of silly code I noticed while looking for something else. This blatantly does nothing except make the code look less ridiculous. Even the "Tweak" label sounds too significant, lol.

admin: refactor silly nested `if` in hold_ground()

---

sopel/cli/run.py
sopel/cli/utils.py
test/cli/test_cli_run.py
test/cli/test_cli_utils.py

The code around config loading for command lines didn't work properly: it ignored the `SOPEL_CONFIG` env var. So I fixed it, and added some tests too.
Its usage is now documented in the help message for the `-c/--config` option.

cli: fix SOPEL_CONFIG env var broken usage

---

docs/source/configuration.rst
sopel/config/core_section.py

I'm tired of user asking "how to provide multiple values?" for list, and I think our users are probably tired of asking, too! So I tried to add more examples whenever possible.
I'm sure I've miss a lot, and @dgw will probably have to fight my Nemesi**S**.
Oh well.

doc: add more examples to core_section

---

sopel/modules/clock.py

Closes #1793
* Add help prefix in output examples, as required by #1793
* Improve and tweak help examples and docstrings

clock: add help prefix to output examples

---

sopel/bot.py
sopel/loader.py
sopel/module.py
sopel/plugins/rules.py
test/plugins/test_plugins_rules.py
test/test_bot.py
test/test_loader.py
test/test_module.py

Fixes #1757 
Draft PR for now, until #1873 is at least approved.
Based on #1873 this PR adds two new rules:
- **Find rules**: an anonymous rule that executes its handler for every instance found in the line, allowing to execute a function multiple times for a single trigger object
- **Search rules**: an anonymous rule that works like the original rule, but matches from anywhere in the line, allowing to execute a function exactly once on any word or pattern contained within a line, not just from its beginning

rules: add find and search rules

---

sopel/modules/reddit.py

Tin. @kwaaak pointed out on IRC that inline reddit stuff generates a response even if the user/subreddit doesn't exist, when it would make more sense to fail silently. Looks like that was the intent, but the implementation was wrong.

reddit: fix slash-info wrongly calling output funcs as `commanded`

---

sopel/bot.py
sopel/irc/abstract_backends.py
sopel/irc/backends.py
sopel/logger.py
sopel/tests/mocks.py
test/irc/test_irc_abstract_backends.py

We used `async_chat.connected` attribute directly in the code, which we shouldn't, so I replaced it with a new method, added to the abstract IRC backend interface.
Also, after further inspection, async_chat's `close` method can be used safely, so now we call it first, then we ask the bot to do whatever is needed with its `on_close` method. Since this method expect the connection to be closed already, it shouldn't be a problem.
The timeout scheduler doesn't need to be joined, since none of its jobs requires to wait that much. I also modified the bot's interface to have a new method (`irc_send`) which will ensure that 1) we don't have any conflict with the `async_chat.send` method, and 2) makes sure to be thread-safe - the abstract class doesn't need to care about that, it's not its job. …

irc: tweak backend interface

---

sopel/modules/reddit.py

We're no longer restricted to matching only one `u/` or `r/` reference per line thanks to #1881.
Closes no issue, because I knew I'd remember without one. 😝

reddit: use new `find` rule type to get all slash-refs in line

---

sopel/bot.py
sopel/cli/run.py
sopel/irc/__init__.py
sopel/irc/backends.py

Closes #1705 
(based on #1890)
I moved the signal handler to `sopel.bot.Sopel`, and made sure that it sends QUIT message only if the bot is connected. When the bot is not connected, it raises `KeyboardInterrupt` instead, which is properly handled (hopefully).

bot: signal handler now checks if the bot is connected

---

sopel/module.py
sopel/modules/emoticons.py
test/test_module.py

All I wanted was to do `/me flips table` and have the bot to reply to me with the best emote ever.
However, I forgot just one little detail in my last PR about rules & commands, which is to not set the `intents` attribute in `action_commands`. Everything else was done and ready to work as intended, it was just this dumb line I forgot.
Oh well, what one can do about it?
```
/me flips table
(╯°□°）╯︵ ┻━┻
```

rules, emoticons: action commands & commands working together at last

---

sopel/config/core_section.py
sopel/config/types.py
sopel/modules/admin.py

Fixes #819; closes #1571 
This PR doesn't try to auto-detect a password/secret attribute, it relies on plugin author to explicitly use a `SecretAttribute`, or to use the `is_secret` parameter. I don't know how it was done before Sopel 6, and the issue #819 doesn't tell either.
When `is_secret` is `True`, the `configure` mehtod uses `getpass.getpass` instead of `input`.

config: add is_secret attribute to use getpass hidden input

---

docs/source/api.rst
docs/source/plugin.rst
sopel/bot.py
sopel/coretasks.py
sopel/irc/backends.py
sopel/plugins/jobs.py
sopel/tools/jobs.py
test/tools/test_tools_jobs.py

Closes #1144 
Initially, it was only about preventing parallel execution of jobs, but then I realized I needed way more than that:
* changed the job object to be registered only once for any set of intervals,
* changed the job object to have similar meta-data than plugin's rules
* added a new scheduler, that can be used in a plugin-specific context (similar to the plugin's rules manager)
Also, I realized that the "catch up" mechanism makes no sense: either the job can be run in time, or it can't, but it won't try to run it more than once because it's late. I can see why it was like that before, but there are several problems with how it was implemented:
* the scheduler is not reliable: it ticks at best every second, at worst every now and then
* a job isn't aware of the catch up …

jobs: prevent parallel execution and plugin specific scheduler

---

sopel/modules/url.py

Now with `url.enable_auto_title` it is possible to deactivate the auto-title feature from the `url` plugin. It is activated by default, so no breaking change.
I used this occasion to add some debug & error logs, because bot owner are not the only ones to get quality of life improvement.

url: add auto-title config option & debug logging

---

sopel/modules/emoticons.py

Tin. Adds `(¬‿¬)` as a "smirk" emote.

emoticons: add smirk command + action command

---

sopel/cli/utils.py
test/cli/test_cli_utils.py

Really, it's just the one thing described in the PR title.
In hindsight, adding `SOPEL_CONFIG` and `SOPEL_<SECTION>_<OPTION>` support without also adding this seems kinda silly.
Draft for now because the tests haven't been updated yet. Hopefully I'll have a chance to talk to @Exirel on IRC tomorrow (my time; he's +7 hours from me), but there's also a review request in case he has any quick suggestions that don't need to wait for a synchronous chat opportunity. 😉

cli: support `SOPEL_CONFIG_DIR` envvar to override `--config-dir` default

---

docs/source/cli.rst
docs/source/plugin.rst
sopel/config/__init__.py
sopel/config/types.py

We had a couple spots in the documentation that mentioned the `SOPEL_CONFIG` var in passing, but no _real_ documentation about it or the ability to override individual settings with envvars.
Now we'll have a whole section (in the CLI chapter) about all supported environment variables.
This is forked off of #1900's WIP branch, so the first commit can be ignored for now. (GitHub may hide it from this PR once #1900 is merged, if its smarts hold up.)

doc: cover environment variable support

---

sopel/coretasks.py

This is a hotfix, this code should have been modified by #1898 and not merged with this error. My bad.

coretasks: replace module.label by plugin.label

---

sopel/plugins/handlers.py
test/plugins/test_plugins_handlers.py

This soothes my perfectionism.
Specifically requesting Exi's review because he wrote this module, and did so relatively recently, so he's the best person to tell me if I overlooked another thing that needs tweaking for this.

plugins.handlers: thEy'Re CaLleD pLuGInS tHoUGh

---

sopel/test_tools.py

The decorator `example` generates a test function when used with pytest and an expected output. When a regex is used for said test, a fake `assert expected == output` was used to mark the test as failed. It is not adapted because a) if the assert pass, it means the test should not use a regex in the first place and b) it creates a confusing test output. So now, it raises an `AssertionError` with a proper error message, which is well understood by any test runner - after all, `assert` is a way to raise the exact same error.
Note: I use `plugin: ...` in the commit message because it's related to the `sopel.plugin.example` decorator, so it makes more sense to me.

plugin: example raises AssertionError when regex does not match

---

requirements.txt
sopel/modules/ip.py
sopel/modules/search.py

Split `geoip2` requirement into ranges based on Python release.
Capped `maxminddb` version on old Pythons now that v2.0 dropped them.
I'm planning to cut a 7.0.5 release with this unless any @sopel-irc/rockstars strenuously object. We're still too far off from finishing 7.1 to wait for that release. This is going to cause issues with new installs of 7.0.4.

build: fix/upgrade `geoip2` requirements where possible

---

sopel/modules/instagram.py

This fixes Sopel parsing instagram links when blocked using the traditional method.

instagram: fix for being blocked

---

sopel/modules/admin.py

This replies to the owner/admin with a message when `.save`ing the configuration file. Pretty simple.

admin: reply on save

---

requirements.txt

Fixes CI builds on Python <3.6 and may or may not help with new installs on the same (depending on pip version in use).
N.B.: I'm letting Travis test all the Python versions so I don't have to install them locally.

build: cap `update-checker` version on older Pythons without f-strings

---

sopel/modules/ip.py

Fixes problem with .ip not working when uppercase letters in queried nick. 
The DB stores users in lowercase, so it does not get a match otherwise.
Ex. when quering user "GLaDER"(hiding successful query output because privacy) 
Found in 7.0.4, running in docker.
Currently not linked to any issue.  
<erikpi> | .ip GLaDER
<sopel> | I'm not aware of this user.
<erikpi> | .ip glader
<sopel> | [IP/Host Lookup] Hostname: XXXX \| Location: XXX\| Region: XXXX \| City: XXXX \| ISP: XXXXX

ip: fix case sensitivity of querying by nickname

---

sopel/modules/find.py

Besides giving us roughly O(1) performance for appends instead of O(n), we also get automatic trimming of old entries.
Since I was already switching things up, I also eliminated the need to reverse the list (now deque) of lines before iterating through it when executing the find-and-replace operation. Lines are now stored in reverse chronological order.
I'm letting Travis do the QA checks, and will update that checkbox later.
@cottongin first suggested the idea, and expressed interest in helping test this change. I did do basic testing myself (including inspecting the data in memory with the ol' ipython plugin).
Probably should revisit a couple of my own plugins that also store recent messages like this and convert them over, since I just lazily copied find's logic.

find: switch to deque for recent line storage

---

sopel/modules/reddit.py

Might or might not be useful to try and fetch all the image URLs from the gallery instead, but initially let's just show the title & subreddit. A quick look at the raw data Reddit provides in the API payload for a gallery submission yielded pretty useless URLs (`preview.redd.it`, with resizing & format conversion embedded).

reddit: handle new gallery view by showing submission info

---

sopel/modules/wikipedia.py

If the DB does not contain any relevant settings for the calling nick or the channel in which the command was run, falls back to the existing `lang_per_channel` config value (if set), then `default_lang`.
Note that the `lang_per_channel` setting is considered deprecated after this change. It has to stay defined in the section class (or it wouldn't be loaded), but it's been removed from everywhere possible and documented as deprecated in the code.
Upon merging this PR, update #827 to request removal of fallback to deprecated `lang_per_channel` setting for 8.0 milestone.

wikipedia: implement language preferences in DB for channels & nicks

---

sopel/tools/jobs.py

For some reason it was broken? I don't understand what happened here. I'll probably have to investigate further to understand the "why did I do that?" later. That will do at the moment, so no worries.

jobs: fix job 'running state'

---

sopel/formatting.py
sopel/trigger.py
test/test_formatting.py
test/test_trigger.py

- `sopel.formatting.plain` to strip known control codes from a text
- `sopel.trigger.PreTrigger.plain` is `args`'s last item without its control code
- `sopel.trigger.Trigger.plain` exposes `sopel.trigger.PreTrigger.plain`
- Closes #1768

trigger: add a plain attribute to PreTrigger and Trigger

---

sopel/tools/__init__.py

If the placeholder is followed by a space, replace it with a pattern that will consume extra whitespace but doesn't require any.
If the placeholder is NOT followed by a space, use the original pattern that requires at least one space to match.
Meant to resolve #1885.

tools.compile_rule: better whitespace handling for `$nick` placeholder
