willie/modules/seen.py

- use willie.db instead of a Ddict to store seen information for a nick

[seen] fix #653 make .seen persist over restarts

---

willie/modules/admin.py

Yeah..... Surprised I didn't notice that..... Oops.

[admin] Make both references to auto_accept_invite be the same.

---

willie/modules/reddit.py

I've implemented creation time inclusion and cake day detection, as mentioned in Issue #119. I've also made the module more PEP8 compliant and added an example to .redditor.
Cake days present a bit of a problem. Their exact implementation on reddit is explained here: http://www.reddit.com/r/AdviceAnimals/comments/1v6xam/seriously/cepjnfg (I linked the submission, not the comment in commit 2dbaf77). The API doesn't make accessible a user's last login time, so we cannot delay cake days as reddit.com does. Unfortunately this means that users may have the cake day flair on reddit.com but not be labelled as having their cake day by Willie, or vice versa.
I have yet to add the 'kick on NSFW tag' feature from #119 as I was unsure of exactly what was meant. If @embolalia could clarify their …

[WIP] Additional reddit features, addressing Issue #119

---

willie/modules/dice.py

Added sorting to drop_lowest to enable dropping of the lowest n results rather than just the first n results

Added sorting to drop_lowest to enable dropping of the lowest n results

---

willie/module.py

require_privmsg and require_chanmsg are identical in the code.
This makes require_chanmsg do what it sounds like it's supposed to do. :-)

Fixes require_chanmsg

---

test/test_db.py
willie/db.py

Also fixed broken test for merge_nick_groups() which allowed this bug to persist.
PR'd per @embolalia's response on IRC.

Merge nickname IDs when merging nick groups

---

willie/modules/tld.py

Like @embolalia said, it was an easy fix. Tested and working on my instance of 5.4.1.

[tld] Strip leading '.' on queries. Fixes #836.

---

sopel/modules/ping.py

Ain't nobody got time fo' punctuation!

[ping] Make using a comma optional

---

sopel/modules/remind.py

Handle missing args for .at & .in

---

sopel/coretasks.py

changed the name of the wiki page to reflect Sopel and updated link here.

update link to wiki

---

sopel/modules/ping.py

Stop Sopel from replying rudely to the bot's owner in ping.py:
<@dmzda> hi dmbot 
<dmbot> Fuck off, dmzda

[ping] Stop Sopel from replying rudely to the bot's owner.

---

README.rst

Changed all willie references to Sopel and fixes all links to point to correct repository.

Willie -> Sopel

---

sopel/modules/countdown.py

Correct expression in the "If" statement.

Fixed some error messages to main chat. Checks parameters before using it.

---

contrib/rpm/willie.spec.in
requirements.txt
setup.py
sopel/modules/bugzilla.py
sopel/modules/currency.py
sopel/modules/weather.py

lxml is one of the harder parts of Sopel to get running correctly, and it's really a lot more than what's needed for the situations it has been used in.

Replace lxml with a pure python solution

---

sopel/modules/currency.py

".cur 1 cad in usd" should be possible

Make CAD currency code case-insensitive

---

sopel/config/types.py

Reported by aam in IRC, http://pastebin.com/0rAQb7Kp

Fix crash during configure

---

sopel/modules/translate.py

Fixes TypeError: 'NoneType' object is not iterable when an invalid language hint abbreviation was given.
Fixes another TypeError: 'NoneType' when no string was given to translate.

[translate] Fix some edge cases

---

sopel/modules/meetbot.py

[meetbot] fix crash when starting meeting

---

sopel/modules/adminchannel.py

Most of these commands throw exceptions if run sent in a PM at the moment.

[adminchannel] require_chanmsg

---

sopel/modules/meetbot.py

was a bad link, updated to correct one

Updated link for meetbot help command

---

CREDITS

[docs] Update project name in CREDITS

---

sopel/coretasks.py
sopel/trigger.py

Resolves #868, progress towards #971

[trigger] IRCv3 server-time support

---

.gitignore
.travis.yml
sopel/modules/translate.py
test/test_db.py
test/test_formatting.py
test/test_module.py
test/test_trigger.py

Adds a bunch of tests for trigger/modules/formatting and makes some minor cleanup to db tests. 
Updated the .travis.yml to test style, but ignore the result. Made the tests run in verbose mode so you can see the exact test that failed. Runs coveralls after a successful build. 
It will currently fail the tests, as there's an issue in web.py.

[tests] Add a bunch of tests

---

sopel/modules/reload.py

Fix Issue #1048: lockup when calling .reload *.

Fix issue #1048

---

sopel/modules/calc.py

Will be moved to an external module that supports the new API, which I intend to cookiecutter from @maxpowa's code later tonight after I get to a computer. See #1041

[calc] Remove .wa, as API now requires a key

---

sopel/modules/ipython.py
sopel/run_script.py

Typo correction

---

sopel/trigger.py
test/test_trigger.py

Allows access to dict results when using named groups.

Add groupdict function to triggers

---

sopel/modules/search.py

A slight regex change to avoid yahoo ad results from duck duck go if it ends up using the HTML search

slight change to avoid ad results

---

sopel/web.py

web: fix header bleed

---

sopel/module.py

module: ignore privilege requirement in privmsg

---

sopel/modules/find_updates.py
sopel/modules/movie.py
sopel/modules/translate.py
sopel/modules/xkcd.py

- `verify_ssl` param was missing in few function calls
- Fixed few linting errors. I think, linting should be addressed in a  separate commit
Closes-Bug: #1118
Signed-off-by: Sachin Patil psachin@redhat.com

Fixed missing `verify_ssl` param

---

sopel/modules/xkcd.py

Added missing default value of "True" for "verify_ssl" parameter on "number_result".

XKCD: Added default value to numbered_result

---

sopel/modules/ip.py

Fixed broken IP module example

IP example

---

sopel/modules/wikipedia.py

Fix https://github.com/sopel-irc/sopel/issues/1182

Exclude Wikipedia File links from regex matching

---

contrib/sopel.cfg
sopel/coretasks.py
sopel/formatting.py
sopel/modules/calc.py
sopel/modules/currency.py
sopel/modules/find.py
sopel/modules/lmgtfy.py
sopel/modules/meetbot.py
sopel/modules/pronouns.py
sopel/modules/wikipedia.py

A few minor fixes to comments that I came across while looking at other stuff.
(I have now, after the fact, learned that Travis has a "skip CI" feature. Which I should use when tweaking documentation, in the future.)

Comment housekeeping

---

sopel/modules/url.py

Work around websites in the Gawker family with their HTTP title gore

---

sopel/modules/remind.py

Add correct timezone time in the .in sub-module of the remind module

---

.gitmodules

I've updated the wiki submodule reference to point to the correct url.

updated wiki submodule

---

sopel/modules/wikipedia.py

Fixes #1255
@kwaaak, this is the change you closed #1252 in favor of. Look good?

Quote Wikipedia query for use in API call

---

sopel/config/core_section.py

Hi there,
I documented and rewrote `_find_certs()` to support more platforms and be easier to extend. This PR was inspired by issue #1246.
Cheers
tpltnt

TLS root cert fixes

---

sopel/modules/reload.py

[reload] Prevent reloading nonexistent module

---

sopel/modules/calc.py

Needed to make the `.py` command more fault-tolerant in a future patch.

[calc] Switch from sopel.web to requests

---

sopel/modules/wikipedia.py

Method adapted from our own url.py.
Resolves #1109

wikipedia: Prevent triggering on other Sopel bots

---

sopel/modules/search.py

No particular reason for using Google except it's the first search query suggestion API I could find. The one that was in Sopel died (404 error), and having something is better than nothing.
Along with fixing the suggestions in the first place, I also added tests (which would have made it evident much sooner that the API this function used had gone away).
If anyone has strenuous objections to sending anything to Google, that's useful feedback to have. I don't think it's possible to profile any specific user based on this API (especially since it's intended to be representative of queries being typed, not actual submitted searches). But there's no reason not to use another suggestion API if someone finds a usable one.

search: Fix .suggest with Google suggestion API

---

requirements.txt
sopel/modules/reddit.py

Work with a wide range of praw versions

reddit: Cross-compatibility for praw

---

.coveragerc
.travis.yml
dev-requirements.txt
pytest.ini
pytest_run.py
setup.py

Moved coveralls and flake8 install to dev-requirements.txt
Moved coverage parameters to .coveragerc config file
Added .pytest_cache to .gitignore
Updated "willie" to "sopel" in comments
Added dev extras_require to setup.py

Update to testing process

---

sopel/config/core_section.py
sopel/coretasks.py

Add option to authenticate using userserv

---

sopel/loader.py
sopel/module.py
sopel/tools/__init__.py
test/test_commands.py
test/test_module.py

I'm still experimenting with different places to insert tests, but the actual bug fix is super easy.
See #1343, which is why I'm not just pushing this fix directly to `master` and calling it done. (The short version is, this fixes a regression introduced by #1052 that the tests can't possibly catch at present, and I'm not happy just moving on until the tests _can_ catch it.)

Nickname commands fix & testing

---

sopel/config/core_section.py

config: do not enable raw log by default

---

sopel/modules/emoticons.py

Basic emoticons added for various feelings. Includes shrug, table-flipping, and unflipping tables.

Added bot emoticons command

---

requirements.txt
sopel/modules/ip.py

The search for the database path seems unnecessary to me, as well as the config option to specify the path.
It is still intact, and should work, but not tested whether it still works with GeoLite2.
It would be easy enough to add an update function to the module which downloads new versions every week or month respectively. Would this be the desired behaviour?
https://dev.maxmind.com/geoip/geoip2/geolite2/

ip: Switch to GeoLite2

---

sopel/modules/translate.py

I'm going to slowly go through the code changing HTTP API calls to HTTPS. This is the first one. They'll be separate PRs for changelog and merge-conflict reasons.

translate: use HTTPS endpoint

---

sopel/modules/url.py

This change doesn't alter the user experience at all on its own, but it will make enhancing the URL matching behavior easier in the long run.
See #1390, for example. I plan to fix that and a few other edge cases by extending this new `find_urls()` function. (My local code has some of this implemented already.)

url: refactor url_finder regex into a function

---

sopel/modules/instagram.py

Instagram module

---

sopel/modules/wiktionary.py

Originally part of #1178, but I decided to pull it out into a separate PR. Who knows how long it'll be before I'm satisfied with that rewrite, but this is ready any time.

wiktionary: Use HTTPS API

---

sopel/modules/weather.py

Missed this API call when I was refactoring the other code in 3d810c2…

weather: convert WOEID lookup to HTTPS too

---

sopel/formatting.py
test/test_formatting.py

formatting: add hex color support

---

sopel/modules/weather.py

This is stuff that at one point I meant to commit in #1187, but forgot about. Found the changes sitting in an old `git stash` and pulled them out.

weather: Bundle of small tweaks

---

sopel/modules/wiktionary.py

Fixes the issue sopel-irc/sopel#1361 where certain words do not return
a definition when one is available.
Words that include references in definitions expose a missed condition
check in parsing that is not relevant for most cases. References use the
`<sup>` tag, which in reference has its own `'id="'` attribute, causing
the `mode` variable in the loop to be reset, even though a definition
should be parsed from that line. These superscript references are also
now parsed out of the definition line.

wiktionary: fix failed lookup for certain words

---

sopel/modules/url.py

Resolves #726
Resolves #1390
I'm still prodding the code for a good way to handle parentheses/brackets, but it'll be done soon™.

url: add punctuation cleaning

---

README.rst

Hi, I'm making updates for Open Collective. Either you or a supporter signed this repo up for Open Collective. This pull request adds backers and sponsors from your Open Collective https://opencollective.com/sopel❤️
It adds two badges at the top to show the latest number of backers and sponsors. It also adds placeholders so that the avatar/logo of new backers/sponsors can automatically be shown without having to update your README. [more info](https://github.com/opencollective/opencollective/wiki/Github-banner). See how it looks on this [repo](https://github.com/apex/apex#backers).
You can also add a postinstall script to let people know after npm|yarn install that you are welcoming donations (optional). [More info](https://github.com/OpenCollective/opencollective-cli)
You can also add a …

docs: Add Open Collective to README.rst

---

sopel/modules/lmgtfy.py

Adds 3 examples for testing purpose.

lmgtfy: add examples with tests

---

sopel/modules/etymology.py

etymology: Back to basics

---

setup.py

From classifiers listed here: https://pypi.org/pypi?%3Aaction=list_classifiers
It's half the work required for #1311 so even if it isn't much I'm happy with it.

setup.py: add Trove classifiers

---

sopel/coretasks.py

Fix #975
Link to the [AUTHENTICATE specification](https://ircv3.net/specs/extensions/sasl-3.1.html#the-authenticate-command).
> The response is encoded in Base64 (RFC 4648), then split to 400-byte chunks, and each chunk is sent as a separate AUTHENTICATE command. Empty (zero-length) responses are sent as AUTHENTICATE +. If the last chunk was exactly 400 bytes long, it must also be followed by AUTHENTICATE + to signal end of response.

coretasks: split AUTHENTICATE token in 400-byte chunks

---

sopel/modules/calc.py

Before:
> <user> .py "↑" * 50
<Sopel> user: ââââââââââââââââââââââââââââââââââââââââââââââââââ
After:
> <user> .py "↑" * 50
<Sopel> user: ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

calc: Make emoji spam possible (support Unicode characters)

---

sopel/modules/help.py

ptpb.pw has shutdown
ptpb/pb#245
ptpb/pb#240

Replace pastebin service for help

---

sopel/modules/reddit.py

praw 4.0.0 changes get_redditor() to redditor(). This patch fixes sopel's reddit module for all versions of praw until a permanent fix can be implemented in sopel 7.

reddit: adding praw compatibility

---

sopel/modules/reddit.py

- Adding support for shortlinks (e.g. https://redd.it/b1j30r)
Fixes #1502

reddit: short url functionality

---

sopel/db.py

db: fixing db initialization bug

---

sopel/modules/instagram.py

The comment section on the website has been redesigned and one of the keys in the embedded JSON has been changed. This PR addresses it.

instagram: Fix for altered JSON key

---

sopel/modules/ip.py

Probably won't happen once #1630 gets merged anyway, but… better safe.

ip: bail on user lookup if host is None

---

sopel/bot.py
sopel/modules/invite.py

This is based on #1157, which stalled after its original author deleted their fork.
Commits added in this version of the patch address feedback left in that original pull request, and make the end product a bit cleaner & more user-friendly (error messages, argument defaults, etc.).
Resolves #1145.

Add .invite command

---

CONTRIBUTING.md
Makefile
contrib/githooks/install-hooks.sh
contrib/githooks/main-hook.sh
contrib/githooks/pre-commit
contrib/githooks/pre-push
contrib/githooks/uninstall-hooks.sh

Please allow me to sell this PR to you:
**INFORMERCIAL**
_Based on true stories of HumorBaby's own experiences_
```
INT. A SOPEL DEVELOPER'S DESK
A developer is happily Sopelunking away. The developer pushes a commit to a PR branch, 
opens the PR in a broswer and sit's back waiting for CI (and more importantly, reviews!)...
VOICEOVER
Has this ever happened to you?!
The status check changes to "[X] Travis CI - Pull Request — Build Failed". 
The developer starts frantically checking the Travis logs to see what went wrong.
The developer is not physically hurt, but is emotionally devastated.
VOICEOVER (CONT'D)
You wrote some code, but various checks failed after you pushed to your repo?
The developer looks towards the screen.
DEVELOPER
I always forget to run code quality and tests! **Travis …
```

dev: adds (optional) pre-commit and pre-push Git hooks

---

sopel/modules/isup.py
test/modules/test_modules_isup.py

Just A Small PR.©
I didn't want to change how the "is this an URL?" checks are performed, but at least they are tested now.

isup: minor cleanup with tests

---

sopel/modules/url.py

Fixes for https://github.com/sopel-irc/sopel/issues/1622

url: minor bug fixes

---

sopel/modules/etymology.py

Fix #1657 
Changed the etymology.py file to solve the issue with no or an empty argument.
Thank you.

etymology: handle empty argument

---

sopel/bot.py

bot: replace deprecated memory.contains call

---

sopel/db.py

This should fix the issue that some users are having with DB timeouts when there is no activity for 8 hours.

db: add pool_recycle to db creation

---

sopel/modules/clock.py

clock: remove obsolete config options

---

sopel/plugins/__init__.py
sopel/plugins/exceptions.py
sopel/plugins/handlers.py

I forgot to add these the first time. There are probably more here and there, but these ones bothered me.

plugins: add licence and author

---

sopel/config/__init__.py
sopel/config/types.py
sopel/irc/backends.py
sopel/irc/utils.py
sopel/modules/adminchannel.py
sopel/modules/clock.py
sopel/modules/help.py
sopel/modules/safety.py

Thanks to [LGTM](https://lgtm.com/projects/g/sopel-irc/sopel/alerts/?mode=list) for these quick fixes.

qa: quick fixes via LGTM

---

sopel/cli/run.py

cli.run: print version info at startup

---

sopel/modules/help.py

Allows forcing help output into query, notice, or the original channel (in most cases). Intended to give bot admins more flexibility in accommodating different communities' opinions about "help spam".
Closes #1220.

help: add `reply_method` option

---

sopel/modules/py.py

Depends on #1701. Based on #1710 branch, so will begin life as a draft PR.
~~Changes unique to this PR are in 3937bd7.~~ Rebased to one commit after upstream merge.

py: use output_prefix

---

sopel/db.py
sopel/tools/__init__.py
test/test_db.py

Resolves #1389.
@RustyBower do you have any thoughts on a better migration scheme? Doing it opportunistically, as needed, seems elegant—but I wonder if it might cause problems somewhere.

tools: Fix Identifier lowercase

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

See what the issue ones look like at https://github.com/half-duplex/sopel/issues/new/choose (or fork it to see what the PR one looks like).
Phrasing and structure comments welcome.

docs: Bug, feature, and issue templates

---

docs/source/api.rst
sopel/logger.py

Also, actually document the stuff somewhere. Perhaps it will be moved to another page later; we could stand to restructure things some more.
See #1565.

logger: doc overhaul

---

setup.py
sopel/cli/run.py

This was @half-duplex's suggestion, so I'll specifically ask him to review. I ended up doing it because I got impatient, and the number 1800 was calling to me. 😛

setup, cli.run: parity between py2 checks & code cleanup

---

sopel/modules/reddit.py

This PR does:
* severely reduce the size of the giant try/except that is `redditor_info`
* move the `is_cakeday` logic to it's own function for potential reusability in future PRs
While `u.id` is not a used variable for `redditor_info`, this PR uses Reddits ID system to verify that a user does exist. Simply put, if a username doesn't have an ID it won't have `.gold` or `.link_karma` or other attributes that would be associated with a redditor.
This also adds a `u.is_employee` check for the message to display when the user is a Reddit employee.

reddit: Reduce try/except size for redditor_info

---

sopel/modules/reddit.py

reddit: Allow `%` in post URLs

---

sopel/modules/safety.py

Skip caching the VT result if the two keys we need aren't present. Access those keys using `.get()` with a default value for `KeyError` protection. Fixes #1850.
- Insert my standard disclaimer about local flake8 checks.
- I requested that @adamus1red try this out in my stead, since it's most important to me that this bug is fixed for the user who reported it.

safety: handle missing VirusTotal scan data

---

sopel/modules/reddit.py

Tin.
I have seen "1 points" for the last time, dammit.
- `make quality` skipped for the usual reason (that big flake8-related project I'm procrastinating on locally and probably should have finished weeks ago)

reddit: grammatically correct point/points depending on score

---

sopel/modules/reddit.py

As per my comment in #1722 here's handling for the two non-subreddit subreddits!

reddit: subreddit handling for r/all and r/popular

---

sopel/modules/search.py

* Remove unused `formatnumber()` function
* Remove `google_search` alias to DuckDuckGo
* Consolidate global "constants" at top of file

search: cleanup dead stuff

---

CONTRIBUTING.md

This is a work-in-progress, which I'm adding to as I get time on my holiday trip overseas.

Docstring style guide

---

sopel/modules/reddit.py

Tin. I didn't scrutinize #1937 hard enough to catch this; it was too far from any lines touched in the diff.

reddit: remove stray hard-coded message prefix missed in #1937

---

sopel/modules/reddit.py

reddit: fix floating point issue on %

---

sopel/modules/tld.py

Instead of the plugin failing to load, it now merely assumes the cached TLD information is outdated. The cache will repopulate as normal when:
* any user calls `.tld` for the first time
* an admin calls `.tldcache update`
* the `update_caches()` job runs (first expected ~1 hour after startup)

tld: fix parsing stored cache timestamps that are invalid or on py2

---

sopel/modules/tld.py

Instead of fetching one big wiki page with everything in it, we have to fetch the gTLD tables from the same place as before, and then get the ccTLD lists separately.
This _could be_ the first of several splits, since the "List of Internet top-level domains" page has a maintenance tag at the top decrying that it's long and hard to navigate. I've made it rather easy to add more pages if the different types of TLD do continue getting split out into their own pages.
SopelTest is this branch; Kaede is current master (12f8640525d2e8eaa716c07abcfafd3a851604a4).
```irc
<~dgw> ;tld md
<&Kaede> [tld] The top-level domain 'md' exists, but no details about it could be found.
<~dgw> ,tld md
<SopelTest> [tld] Name: .md | Entity: Moldova | DNSSEC: Yes | SLD: Yes | Notes: Restricted to individuals
or …
```

tld: ccTLD data moved to its own wiki page

---

sopel/modules/reddit.py

We are going to overhaul the pinned version range for 8.0 (or rather, probably just move the whole reddit plugin to its own package). Meanwhile, PRAW printing a message to stderr in the middle of Sopel's startup sequence is kind of annoying.

reddit: stop PRAW checking for updates

---

sopel/coretasks.py

This should make it so that, even on networks with `away-notify` support (where Sopel disables its regular WHO polling), users who were not in a given channel when Sopel joined will still have a `realname` value set in relatively short order.
The WHO command can take a nickname, a channel name, or a pattern mask. Sopel previously made use of only the channel name type. I refactored the `_send_who()` helper a bit so it can take either a channel or nick, and tweaked the JOIN handler to send a WHO for any user Sopel didn't already know about (wasn't present in `bot.users` at the time of the JOIN event).
Patches #2383; resolves #2387
- Lazily letting GHA do this for me
- Hopped onto Rizon (which has `away-notify`) with my testbot, used `sopel-ipython` to inspect the `bot.users` list, then …

coretasks: send WHO to get realname for never-seen users on JOIN

---

sopel/bot.py

This seems like a pretty obvious gotcha, but I'll bet most people don't take a list of *every available plugin* and blindly paste it into the `disable_plugins` setting for a channel.
That said, if `coretasks` is present in the `core.exclude` list, it'll be loaded anyway. This is the same idea; Sopel NEEDS it to work, so it shouldn't be possible to disable.
I'm not 100% sure that I needed to add checks in both of these functions but it felt OK to be extra careful.
Will prevent anyone else running into a confusing situation like #2398.
- This is why we have GHA pipelines 😛

bot: don't let per-channel config skip coretasks handlers

---

.github/ISSUE_TEMPLATE/bug_report.yml

This is the follow-up I mentioned in #2574. The time to test it out will come later, after 8.0.0 is out and the website has updated.

meta: update bug report issue template with logs FAQ link
